// frontend/src/components/server/ServerPerformance.vue
<template>
    <div class="grid gap-4" :class="gridColsClass">
        <Card v-if="showCpu !== false" class="relative overflow-hidden">
            <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
                <CardTitle class="text-sm font-medium text-gray-900 dark:text-white">{{
                    t('serverConsole.cpuLoad')
                }}</CardTitle>
                <div class="flex items-center gap-2">
                    <div class="w-2 h-2 bg-red-500 rounded-full animate-pulse"></div>
                    <Cpu class="h-4 w-4 text-muted-foreground" />
                </div>
            </CardHeader>
            <CardContent class="space-y-3">
                <div class="flex justify-between items-center">
                    <span class="text-xs text-muted-foreground">Limit: {{ server?.cpu || 0 }}%</span>
                    <span class="text-xs font-medium text-red-600 dark:text-red-400"
                        >{{ getCurrentValue(cpuData) }}%</span
                    >
                </div>
                <div class="w-full h-20">
                    <PerformanceChart
                        :data="cpuData"
                        :color="dataColors.cpu"
                        unit="%"
                        :max-value="server?.cpu || 100"
                    />
                </div>
            </CardContent>
        </Card>

        <Card v-if="showMemory !== false" class="relative overflow-hidden">
            <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
                <CardTitle class="text-sm font-medium text-gray-900 dark:text-white">{{
                    t('serverConsole.memory')
                }}</CardTitle>
                <div class="flex items-center gap-2">
                    <div class="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
                    <MemoryStick class="h-4 w-4 text-muted-foreground" />
                </div>
            </CardHeader>
            <CardContent class="space-y-3">
                <div class="flex justify-between items-center">
                    <span class="text-xs text-muted-foreground">Limit: {{ formatMemory(server?.memory || 0) }}</span>
                    <span class="text-xs font-medium text-blue-600 dark:text-blue-400"
                        >{{ getCurrentValue(memoryData) }} MiB</span
                    >
                </div>
                <div class="w-full h-20">
                    <PerformanceChart
                        :data="memoryData"
                        :color="dataColors.memory"
                        unit="MiB"
                        :max-value="server?.memory || 100"
                    />
                </div>
            </CardContent>
        </Card>

        <Card v-if="showDisk !== false" class="relative overflow-hidden">
            <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
                <CardTitle class="text-sm font-medium text-gray-900 dark:text-white">{{
                    t('serverConsole.disk')
                }}</CardTitle>
                <div class="flex items-center gap-2">
                    <div :class="getDiskStatusColor()" class="w-2 h-2 rounded-full animate-pulse"></div>
                    <HardDrive class="h-4 w-4 text-muted-foreground" />
                </div>
            </CardHeader>
            <CardContent class="space-y-3">
                <div class="flex justify-between items-center">
                    <div class="flex flex-col">
                        <span class="text-xs text-muted-foreground">
                            Limit: {{ formatDisk(server?.disk || 0) }}
                            <span v-if="server?.disk === 0" class="text-yellow-500">(unlimited)</span>
                            <span v-else-if="getDiskUsagePercentage() > 95" class="text-red-500">(critical!)</span>
                            <span v-else-if="getDiskUsagePercentage() > 80" class="text-yellow-500">(warning)</span>
                        </span>
                    </div>
                    <span class="text-xs font-medium" :class="getDiskValueColor()"
                        >{{ getCurrentValue(diskData) }} MiB</span
                    >
                </div>
                <div class="w-full h-20">
                    <PerformanceChart
                        :data="diskData"
                        :color="getDiskChartColor()"
                        unit="MiB"
                        :max-value="server?.disk || 100"
                    />
                </div>
            </CardContent>
        </Card>

        <Card v-if="showNetwork !== false" class="relative overflow-hidden">
            <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-3">
                <CardTitle class="text-sm font-medium text-gray-900 dark:text-white">{{
                    t('serverConsole.network')
                }}</CardTitle>
                <div class="flex items-center gap-2">
                    <div class="flex gap-1">
                        <div class="w-2 h-2 bg-yellow-500 rounded-full animate-pulse"></div>
                        <div class="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></div>
                    </div>
                    <Globe class="h-4 w-4 text-muted-foreground" />
                </div>
            </CardHeader>
            <CardContent class="space-y-3">
                <div class="flex justify-between items-center">
                    <div class="flex gap-4 text-xs text-muted-foreground">
                        <span class="flex items-center gap-1">
                            <span class="w-1 h-1 bg-yellow-500 rounded-full"></span>
                            ↑ {{ networkStats.upload }}
                        </span>
                        <span class="flex items-center gap-1">
                            <span class="w-1 h-1 bg-blue-500 rounded-full"></span>
                            ↓ {{ networkStats.download }}
                        </span>
                    </div>
                    <span class="text-xs font-medium text-orange-600 dark:text-orange-400">{{
                        getCurrentValue(networkData)
                    }}</span>
                </div>
                <div class="w-full h-20">
                    <PerformanceChart :data="networkData" :color="dataColors.network" unit="B" />
                </div>
            </CardContent>
        </Card>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { computed } from 'vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Cpu, MemoryStick, HardDrive, Globe } from 'lucide-vue-next';
import { useI18n } from 'vue-i18n';
import PerformanceChart from '@/components/charts/PerformanceChart.vue';
import type { Server, NetworkStats } from '@/types/server';

const { t } = useI18n();

interface Props {
    server: Server | null;
    cpuData: Array<{ timestamp: number; value: number }>;
    memoryData: Array<{ timestamp: number; value: number }>;
    diskData: Array<{ timestamp: number; value: number }>;
    networkData: Array<{ timestamp: number; value: number }>;
    networkStats: NetworkStats;
    showCpu?: boolean;
    showMemory?: boolean;
    showDisk?: boolean;
    showNetwork?: boolean;
}

const props = defineProps<Props>();

// Compute grid columns based on visible charts with better responsive design
const gridColsClass = computed(() => {
    const visibleCharts = [
        props.showCpu !== false,
        props.showMemory !== false,
        props.showDisk !== false,
        props.showNetwork !== false,
    ].filter(Boolean).length;

    if (visibleCharts === 1) return 'grid-cols-1';
    if (visibleCharts === 2) return 'grid-cols-1 sm:grid-cols-2';
    if (visibleCharts === 3) return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-3';
    return 'grid-cols-1 sm:grid-cols-2 lg:grid-cols-4';
});

const dataColors = {
    cpu: '#ef4444',
    memory: '#3b82f6',
    disk: '#10b981',
    network: '#f59e0b',
};

function formatMemory(memory: number): string {
    if (memory >= 1024) {
        return `${(memory / 1024).toFixed(1)} GiB`;
    }
    return `${memory} MiB`;
}

function formatDisk(disk: number): string {
    if (disk >= 1024) {
        return `${(disk / 1024).toFixed(1)} GiB`;
    }
    return `${disk} MiB`;
}

function getDiskUsagePercentage(): number {
    const diskLimit = props.server?.disk || 0;
    const currentUsage = props.server?.diskUsage || 0;

    if (diskLimit === 0) return 0; // Unlimited disk

    return (currentUsage / diskLimit) * 100;
}

function getDiskChartColor(): string {
    const usagePercentage = getDiskUsagePercentage();

    if (usagePercentage > 95) return '#ef4444'; // Red for critical
    if (usagePercentage > 80) return '#f59e0b'; // Yellow for warning
    return '#10b981'; // Green for normal
}

function getDiskStatusColor(): string {
    const usagePercentage = getDiskUsagePercentage();

    if (usagePercentage > 95) return 'bg-red-500'; // Red for critical
    if (usagePercentage > 80) return 'bg-yellow-500'; // Yellow for warning
    return 'bg-green-500'; // Green for normal
}

function getDiskValueColor(): string {
    const usagePercentage = getDiskUsagePercentage();

    if (usagePercentage > 95) return 'text-red-600 dark:text-red-400'; // Red for critical
    if (usagePercentage > 80) return 'text-yellow-600 dark:text-yellow-400'; // Yellow for warning
    return 'text-green-600 dark:text-green-400'; // Green for normal
}

function getCurrentValue(data: Array<{ timestamp: number; value: number }>): string {
    if (data.length === 0) return '0';
    const lastValue = data[data.length - 1];
    if (!lastValue) return '0';

    if (lastValue.value >= 1024 * 1024 * 1024) {
        return (lastValue.value / (1024 * 1024 * 1024)).toFixed(1) + ' GB';
    } else if (lastValue.value >= 1024 * 1024) {
        return (lastValue.value / (1024 * 1024)).toFixed(1) + ' MB';
    } else if (lastValue.value >= 1024) {
        return (lastValue.value / 1024).toFixed(1) + ' KB';
    }
    return lastValue.value.toFixed(1);
}
</script>

<style scoped>
/* Card hover effects */
.relative:hover {
    transform: translateY(-1px);
    transition: transform 0.2s ease-in-out;
}

/* Pulse animation for status indicators */
@keyframes pulse {
    0%,
    100% {
        opacity: 1;
    }
    50% {
        opacity: 0.5;
    }
}

.animate-pulse {
    animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

/* Chart container styling */
.w-full.h-20 {
    min-height: 80px;
    position: relative;
}

/* Responsive text sizing */
@media (max-width: 640px) {
    .text-xs {
        font-size: 0.75rem;
    }

    .text-sm {
        font-size: 0.875rem;
    }
}
</style>

// featherpanel-frontendv2/src/components/server/ServerPerformance.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React from 'react';
import { LineChart, Line, ResponsiveContainer, YAxis, Tooltip } from 'recharts';
import { Cpu, Database, HardDrive, Globe } from 'lucide-react';
import { useTranslation } from '@/contexts/TranslationContext';

interface PerformanceDataPoint {
    timestamp: number;
    value: number;
}

interface ServerPerformanceProps {
    cpuData: PerformanceDataPoint[];
    memoryData: PerformanceDataPoint[];
    diskData: PerformanceDataPoint[];
    networkData: PerformanceDataPoint[];
    cpuLimit: number;
    memoryLimit: number;
    diskLimit: number;
}

export default function ServerPerformance({
    cpuData,
    memoryData,
    diskData,
    networkData,
    cpuLimit,
    memoryLimit,
    diskLimit,
}: ServerPerformanceProps) {
    const { t } = useTranslation();

    const formatMemory = (value: number): string => {
        if (value >= 1024) {
            return `${(value / 1024).toFixed(1)} GiB`;
        }
        return `${value.toFixed(1)} MiB`;
    };

    const formatBytes = (bytes: number): string => {
        if (bytes >= 1024 * 1024 * 1024) {
            return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
        } else if (bytes >= 1024 * 1024) {
            return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
        } else if (bytes >= 1024) {
            return `${(bytes / 1024).toFixed(2)} KB`;
        }
        return `${bytes.toFixed(2)} B`;
    };

    const getCurrentValue = (data: PerformanceDataPoint[]): number => {
        if (!data.length) return 0;
        return data[data.length - 1].value;
    };

    const getDiskUsagePercentage = (): number => {
        if (diskLimit === 0) return 0;
        const currentUsage = getCurrentValue(diskData);
        return (currentUsage / diskLimit) * 100;
    };

    const getDiskColor = (): string => {
        const usage = getDiskUsagePercentage();
        if (usage > 95) return '#ef4444'; // red
        if (usage > 80) return '#f59e0b'; // yellow
        return '#10b981'; // green
    };

    const charts = [
        {
            title: t('servers.console.performance.cpu_load'),
            data: cpuData,
            color: '#ef4444',
            icon: Cpu,
            currentValue: `${getCurrentValue(cpuData).toFixed(1)}%`,
            limit: cpuLimit > 0 ? `${cpuLimit}%` : t('servers.console.info_cards.unlimited'),
            max: cpuLimit > 0 ? cpuLimit : undefined,
        },
        {
            title: t('servers.memory'),
            data: memoryData,
            color: '#3b82f6',
            icon: Database,
            currentValue: formatMemory(getCurrentValue(memoryData)),
            limit: memoryLimit > 0 ? formatMemory(memoryLimit) : t('servers.console.info_cards.unlimited'),
            max: memoryLimit > 0 ? memoryLimit : undefined,
        },
        {
            title: t('servers.disk'),
            data: diskData,
            color: getDiskColor(),
            icon: HardDrive,
            currentValue: formatMemory(getCurrentValue(diskData)),
            limit: diskLimit > 0 ? formatMemory(diskLimit) : t('servers.console.info_cards.unlimited'),
            max: diskLimit > 0 ? diskLimit : undefined,
        },
        {
            title: t('servers.console.performance.network'),
            data: networkData,
            color: '#f59e0b',
            icon: Globe,
            currentValue: formatBytes(getCurrentValue(networkData)),
            limit: 'N/A',
            max: undefined,
        },
    ];

    return (
        <div className='grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4'>
            {charts.map((chart) => {
                const Icon = chart.icon;
                return (
                    <div
                        key={chart.title}
                        className='rounded-xl border border-border bg-card p-6 shadow-sm hover:shadow-md transition-all'
                    >
                        <div className='flex items-center justify-between mb-3'>
                            <h3 className='text-sm font-medium text-gray-900 dark:text-white'>{chart.title}</h3>
                            <div className='flex items-center gap-2'>
                                <div
                                    className='w-2 h-2 rounded-full animate-pulse'
                                    style={{ backgroundColor: chart.color }}
                                />
                                <Icon className='h-4 w-4 text-muted-foreground' />
                            </div>
                        </div>

                        <div className='space-y-3'>
                            <div className='flex justify-between items-center text-xs'>
                                <span className='text-muted-foreground'>
                                    {t('servers.console.info_cards.limit', { limit: chart.limit })}
                                </span>
                                <span className='font-medium' style={{ color: chart.color }}>
                                    {chart.currentValue}
                                </span>
                            </div>

                            <div className='h-[200px] w-full mt-4 min-h-[200px]'>
                                {chart.data.length > 0 ? (
                                    <ResponsiveContainer width='100%' height='100%'>
                                        <LineChart data={chart.data}>
                                            <YAxis domain={[0, chart.max || 'auto']} hide />
                                            <Tooltip
                                                content={({ active, payload }) => {
                                                    if (!active || !payload || !payload.length) return null;
                                                    const value = payload[0].value as number;
                                                    let formattedValue = '';

                                                    if (chart.title === t('servers.console.performance.cpu_load')) {
                                                        formattedValue = `${value.toFixed(1)}%`;
                                                    } else if (
                                                        chart.title === t('servers.console.performance.network')
                                                    ) {
                                                        formattedValue = formatBytes(value);
                                                    } else {
                                                        formattedValue = formatMemory(value);
                                                    }

                                                    return (
                                                        <div className='bg-background border border-border rounded-lg p-2 shadow-lg'>
                                                            <p className='text-xs font-medium'>{formattedValue}</p>
                                                        </div>
                                                    );
                                                }}
                                            />
                                            <Line
                                                type='monotone'
                                                dataKey='value'
                                                stroke={chart.color}
                                                strokeWidth={2}
                                                dot={false}
                                                animationDuration={0}
                                            />
                                        </LineChart>
                                    </ResponsiveContainer>
                                ) : (
                                    <div className='flex items-center justify-center h-full text-muted-foreground text-sm'>
                                        {t('servers.console.performance.no_data')}
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                );
            })}
        </div>
    );
}
