// featherpanel-frontendv2/src/app/admin/tickets/categories/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import axios from 'axios';
import { Plus, Search, Pencil, Trash2, Ticket as TicketIcon, Tags, Info, HelpCircle } from 'lucide-react';
import Image from 'next/image';
import { PageHeader } from '@/components/featherui/PageHeader';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { TableSkeleton } from '@/components/featherui/TableSkeleton';
import { EmptyState } from '@/components/featherui/EmptyState';
import { Button } from '@/components/featherui/Button';
import { Input } from '@/components/featherui/Input';
import { Sheet, SheetDescription, SheetHeader, SheetTitle, SheetFooter } from '@/components/ui/sheet';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { PageCard } from '@/components/featherui/PageCard';
import { cn } from '@/lib/utils';

interface Category {
    id: number;
    name: string;
    icon: string | null;
    color: string;
    support_email: string;
    open_hours: string | null;
}

export default function TicketCategoriesPage() {
    const { t } = useTranslation();
    const [categories, setCategories] = useState<Category[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [createOpen, setCreateOpen] = useState(false);
    const [editOpen, setEditOpen] = useState(false);
    const [selectedCategory, setSelectedCategory] = useState<Category | null>(null);

    const [formData, setFormData] = useState({
        name: '',
        icon: '',
        color: '#3B82F6',
        support_email: '',
        open_hours: '',
    });
    const [iconFile, setIconFile] = useState<File | null>(null);
    const [iconPreview, setIconPreview] = useState<string | null>(null);

    const fetchCategories = useCallback(async () => {
        setLoading(true);
        try {
            const response = await axios.get('/api/admin/tickets/categories');
            setCategories(response.data.data.categories || []);
        } catch (error) {
            console.error('Error fetching categories:', error);
            toast.error(t('admin.tickets.categories.fetch_error'));
        } finally {
            setLoading(false);
        }
    }, [t]);

    useEffect(() => {
        fetchCategories();
    }, [fetchCategories]);

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            let iconUrl = formData.icon;

            if (iconFile) {
                const uploadFormData = new FormData();
                uploadFormData.append('icon', iconFile);
                const uploadRes = await axios.post('/api/admin/tickets/categories/upload-icon', uploadFormData, {
                    headers: { 'Content-Type': 'multipart/form-data' },
                });
                if (uploadRes.data.success) {
                    iconUrl = uploadRes.data.data.url;
                } else {
                    toast.error(t('admin.tickets.categories.upload_error') || 'Failed to upload icon');
                    return;
                }
            }

            await axios.put('/api/admin/tickets/categories', { ...formData, icon: iconUrl });
            toast.success(t('admin.tickets.categories.create_success'));
            setCreateOpen(false);
            fetchCategories();
            resetForm();
        } catch (error) {
            console.error('Error creating category:', error);
            toast.error(t('admin.tickets.categories.create_error'));
        }
    };

    const handleUpdate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedCategory) return;
        try {
            let iconUrl = formData.icon;

            if (iconFile) {
                const uploadFormData = new FormData();
                uploadFormData.append('icon', iconFile);
                const uploadRes = await axios.post('/api/admin/tickets/categories/upload-icon', uploadFormData, {
                    headers: { 'Content-Type': 'multipart/form-data' },
                });
                if (uploadRes.data.success) {
                    iconUrl = uploadRes.data.data.url;
                } else {
                    toast.error(t('admin.tickets.categories.upload_error') || 'Failed to upload icon');
                    return;
                }
            }

            await axios.patch(`/api/admin/tickets/categories/${selectedCategory.id}`, { ...formData, icon: iconUrl });
            toast.success(t('admin.tickets.categories.update_success'));
            setEditOpen(false);
            fetchCategories();
            resetForm();
        } catch (error) {
            console.error('Error updating category:', error);
            toast.error(t('admin.tickets.categories.update_error'));
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm(t('admin.tickets.categories.delete_confirm'))) return;
        try {
            await axios.delete(`/api/admin/tickets/categories/${id}`);
            toast.success(t('admin.tickets.categories.delete_success'));
            fetchCategories();
        } catch (error) {
            console.error('Error deleting category:', error);
            toast.error(t('admin.tickets.categories.delete_error'));
        }
    };

    const resetForm = () => {
        setFormData({
            name: '',
            icon: '',
            color: '#3B82F6',
            support_email: '',
            open_hours: '',
        });
        setSelectedCategory(null);
        setIconFile(null);
        setIconPreview(null);
    };

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setIconFile(file);
            const reader = new FileReader();
            reader.onload = (e) => {
                setIconPreview(e.target?.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const openEdit = (category: Category) => {
        setSelectedCategory(category);
        setFormData({
            name: category.name,
            icon: category.icon || '',
            color: category.color,
            support_email: category.support_email,
            open_hours: category.open_hours || '',
        });
        setIconPreview(category.icon);
        setEditOpen(true);
    };

    const filteredCategories = categories.filter(
        (c) =>
            c.name.toLowerCase().includes(search.toLowerCase()) ||
            c.support_email.toLowerCase().includes(search.toLowerCase()),
    );

    return (
        <div className='p-6 space-y-8 max-w-[1600px] mx-auto animate-in fade-in duration-700'>
            <PageHeader
                title={t('admin.tickets.categories.title')}
                description={t('admin.tickets.categories.description')}
                icon={Plus}
                actions={
                    <Button
                        onClick={() => {
                            resetForm();
                            setCreateOpen(true);
                        }}
                        className='rounded-2xl h-14 px-8 shadow-2xl shadow-primary/20 gap-3 text-lg font-black uppercase tracking-tighter transition-all hover:scale-[1.02] active:scale-[0.98]'
                    >
                        <Plus className='h-6 w-6' />
                        {t('admin.tickets.categories.create')}
                    </Button>
                }
            />

            <div className='flex flex-col md:flex-row gap-4 items-center justify-between bg-card/40 backdrop-blur-md p-4 rounded-4xl border border-border/5 shadow-xl shadow-primary/5'>
                <div className='relative w-full md:w-96 group'>
                    <Search className='absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors' />
                    <Input
                        placeholder={t('admin.tickets.categories.search_placeholder')}
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className='pl-11 h-12 bg-background/50 border-border/10 rounded-2xl focus:ring-primary/20 transition-all'
                    />
                </div>
            </div>

            {loading ? (
                <TableSkeleton count={5} />
            ) : filteredCategories.length === 0 ? (
                <EmptyState
                    title={t('admin.tickets.no_results')}
                    description={t('admin.tickets.search_placeholder')}
                    icon={Search}
                />
            ) : (
                <div className='grid grid-cols-1 gap-4'>
                    {filteredCategories.map((category) => (
                        <ResourceCard
                            key={category.id}
                            icon={({ className }: { className?: string }) => (
                                <div
                                    className={cn(
                                        'flex items-center justify-center rounded-xl bg-primary/10 overflow-hidden relative',
                                        className,
                                    )}
                                >
                                    {category.icon ? (
                                        <Image src={category.icon} alt={category.name} fill className='object-cover' />
                                    ) : (
                                        <div className='h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary'>
                                            <TicketIcon className='h-4 w-4' />
                                        </div>
                                    )}
                                </div>
                            )}
                            title={category.name}
                            subtitle={category.support_email}
                            style={{ borderLeft: `4px solid ${category.color}` }}
                            description={
                                <div className='flex items-center gap-4 text-sm text-muted-foreground'>
                                    <span>
                                        {t('admin.tickets.categories.form.open_hours')}: {category.open_hours || 'N/A'}
                                    </span>
                                </div>
                            }
                            actions={
                                <div className='flex items-center gap-2'>
                                    <Button size='sm' variant='ghost' onClick={() => openEdit(category)}>
                                        <Pencil className='h-4 w-4' />
                                    </Button>
                                    <Button
                                        size='sm'
                                        variant='ghost'
                                        className='text-destructive hover:text-destructive hover:bg-destructive/10'
                                        onClick={() => handleDelete(category.id)}
                                    >
                                        <Trash2 className='h-4 w-4' />
                                    </Button>
                                </div>
                            }
                        />
                    ))}
                </div>
            )}

            {/* Create/Edit Sheet */}
            <Sheet
                open={createOpen || editOpen}
                onOpenChange={(open) => {
                    if (!open) {
                        setCreateOpen(false);
                        setEditOpen(false);
                    }
                }}
            >
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>
                            {createOpen ? t('admin.tickets.categories.create') : t('admin.tickets.categories.edit')}
                        </SheetTitle>
                        <SheetDescription>{t('admin.tickets.categories.description')}</SheetDescription>
                    </SheetHeader>

                    <form onSubmit={createOpen ? handleCreate : handleUpdate} className='space-y-6'>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.name')}</Label>
                            <Input
                                value={formData.name}
                                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                className='bg-background/50'
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.icon')}</Label>
                            <Input
                                type='file'
                                accept='image/*'
                                onChange={handleFileSelect}
                                className='bg-background/50 file:text-foreground'
                            />
                            {iconPreview && (
                                <div className='mt-2'>
                                    <Label className='text-xs text-muted-foreground'>{t('common.preview')}</Label>
                                    <div className='relative h-16 w-16 rounded-lg overflow-hidden border border-border/10'>
                                        <Image
                                            src={iconPreview}
                                            alt={t('common.preview')}
                                            fill
                                            className='object-cover'
                                        />
                                    </div>
                                </div>
                            )}
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.color')}</Label>
                            <div className='flex gap-2'>
                                <Input
                                    type='color'
                                    value={formData.color}
                                    onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                                    className='w-12 h-10 p-1 bg-background/50'
                                />
                                <Input
                                    value={formData.color}
                                    onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                                    className='bg-background/50'
                                />
                            </div>
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.support_email')}</Label>
                            <Input
                                type='email'
                                value={formData.support_email}
                                onChange={(e) => setFormData({ ...formData, support_email: e.target.value })}
                                className='bg-background/50'
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.open_hours')}</Label>
                            <Input
                                value={formData.open_hours}
                                onChange={(e) => setFormData({ ...formData, open_hours: e.target.value })}
                                className='bg-background/50'
                                placeholder='Mon-Fri 9AM-5PM'
                            />
                        </div>

                        <SheetFooter className='gap-2 sm:gap-0'>
                            <Button
                                type='button'
                                variant='outline'
                                onClick={() => {
                                    setCreateOpen(false);
                                    setEditOpen(false);
                                }}
                                className='flex-1 rounded-xl h-12'
                            >
                                {t('common.cancel')}
                            </Button>
                            <Button type='submit' className='flex-1 rounded-xl h-12 shadow-xl shadow-primary/20'>
                                {createOpen ? t('common.create') : t('common.save')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            {/* Help Cards */}
            <div className='grid grid-cols-1 md:grid-cols-3 gap-6 pt-8'>
                <PageCard title={t('admin.tickets.categories.help.managing.title')} icon={Tags}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.managing.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.tickets.categories.help.emails.title')} icon={Info}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.emails.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.tickets.categories.help.icons.title')} icon={HelpCircle} variant='warning'>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.icons.description')}
                    </p>
                </PageCard>
            </div>
        </div>
    );
}

// frontend/src/pages/dashboard/knowledgebase/Categories.vue
<template>
    <DashboardLayout :breadcrumbs="[{ text: 'Knowledgebase', isCurrent: true, href: '/dashboard/knowledgebase' }]">
        <div class="min-h-screen bg-background">
            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading knowledgebase...</span>
                </div>
            </div>

            <!-- Categories Grid -->
            <div v-else class="p-6 max-w-7xl mx-auto">
                <div class="mb-8">
                    <h1
                        class="text-4xl font-bold mb-3 bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent"
                    >
                        Knowledgebase
                    </h1>
                    <p class="text-muted-foreground text-lg">Browse articles by category</p>
                </div>

                <div v-if="categories.length === 0" class="text-center py-16">
                    <div class="inline-flex items-center justify-center w-20 h-20 rounded-full bg-muted mb-4">
                        <BookOpen class="h-10 w-10 text-muted-foreground" />
                    </div>
                    <p class="text-muted-foreground text-lg">No categories available yet.</p>
                </div>

                <div v-else class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                    <Card
                        v-for="category in categories"
                        :key="category.id"
                        class="cursor-pointer hover:shadow-xl hover:scale-[1.02] transition-all duration-200 border-2 hover:border-primary/20 group"
                        @click="viewCategory(category)"
                    >
                        <CardHeader class="pb-4">
                            <div class="flex items-start gap-4">
                                <div
                                    v-if="category.icon"
                                    class="shrink-0 p-3 rounded-xl bg-muted/50 group-hover:bg-primary/10 transition-colors"
                                >
                                    <img
                                        :src="category.icon"
                                        :alt="category.name"
                                        class="h-14 w-14 rounded-lg object-cover"
                                        @error="handleImageError"
                                    />
                                </div>
                                <div class="flex-1 min-w-0 pt-1">
                                    <CardTitle class="text-xl mb-2 group-hover:text-primary transition-colors">
                                        {{ category.name }}
                                    </CardTitle>
                                    <CardDescription v-if="category.description" class="line-clamp-2 text-sm">
                                        {{ category.description }}
                                    </CardDescription>
                                </div>
                            </div>
                        </CardHeader>
                        <CardContent class="pt-0">
                            <Button
                                variant="ghost"
                                class="w-full justify-between group-hover:bg-primary/10 group-hover:text-primary transition-colors"
                                @click.stop="viewCategory(category)"
                            >
                                <span>View Articles</span>
                                <ChevronRight class="h-4 w-4 ml-2 group-hover:translate-x-1 transition-transform" />
                            </Button>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </DashboardLayout>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { BookOpen, ChevronRight } from 'lucide-vue-next';
import axios from 'axios';

type Category = {
    id: number;
    name: string;
    slug: string;
    icon: string;
    description?: string;
    position: number;
    created_at: string;
    updated_at: string;
};

const router = useRouter();
const categories = ref<Category[]>([]);
const loading = ref(true);

async function fetchCategories() {
    loading.value = true;
    try {
        const { data } = await axios.get('/api/user/knowledgebase/categories', {
            params: {
                page: 1,
                limit: 100,
            },
        });
        categories.value = (data.data.categories || []).sort((a: Category, b: Category) => {
            // Sort by position, then by name
            if (a.position !== b.position) {
                return a.position - b.position;
            }
            return a.name.localeCompare(b.name);
        });
    } catch (error) {
        console.error('Failed to fetch categories:', error);
    } finally {
        loading.value = false;
    }
}

function viewCategory(category: Category) {
    router.push(`/dashboard/knowledgebase/category/${category.id}`);
}

function handleImageError(event: Event) {
    const img = event.target as HTMLImageElement;
    img.style.display = 'none';
}

onMounted(() => {
    fetchCategories();
});
</script>
