// frontend/src/components/admin/QuickLinksWidget.vue
<template>
    <div class="p-6 space-y-4">
        <h2 class="text-xl font-semibold flex items-center gap-2">
            <Zap :size="20" class="text-primary" />
            Quick Links
        </h2>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
            <Card
                v-for="link in quickLinks"
                :key="link.name"
                class="p-4 hover:shadow-lg transition-all cursor-pointer group hover:scale-105 duration-200"
                @click="navigateTo(link.path)"
            >
                <div class="flex flex-col items-center text-center gap-3">
                    <div
                        class="h-12 w-12 rounded-full flex items-center justify-center transition-colors"
                        :class="`bg-${link.color}-500/10 group-hover:bg-${link.color}-500/20`"
                    >
                        <component :is="link.icon" :size="24" :class="`text-${link.color}-600`" />
                    </div>
                    <div class="font-medium text-sm">{{ link.name }}</div>
                </div>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { Server, Users, Settings, Sparkles, Zap } from 'lucide-vue-next';
import { Card } from '@/components/ui/card';
import { useRouter } from 'vue-router';
import type { Component } from 'vue';

const router = useRouter();

interface QuickLink {
    name: string;
    path: string;
    icon: Component;
    color: string;
}

const quickLinks: QuickLink[] = [
    { name: 'Servers', path: '/admin/servers', icon: Server, color: 'blue' },
    { name: 'Users', path: '/admin/users', icon: Users, color: 'green' },
    { name: 'Settings', path: '/admin/settings', icon: Settings, color: 'gray' },
    { name: 'Spells', path: '/admin/spells', icon: Sparkles, color: 'pink' },
];

const navigateTo = (path: string) => {
    router.push(path);
};
</script>

// frontendv2/src/components/admin/QuickLinksWidget.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React from 'react';
import Link from 'next/link';
import { ExternalLink, BookOpen, MessageSquare, Settings, Zap, Trash2 } from 'lucide-react';
import { useTranslation } from '@/contexts/TranslationContext';
import { PageCard } from '@/components/featherui/PageCard';
import { cn } from '@/lib/utils';

interface QuickLinksWidgetProps {
    onClearCache: () => void;
    isClearingCache: boolean;
}

export function QuickLinksWidget({ onClearCache, isClearingCache }: QuickLinksWidgetProps) {
    const { t } = useTranslation();

    const links = [
        {
            name: t('admin.quick_links.system_settings'),
            icon: Settings,
            href: '/admin/settings',
            color: 'text-primary',
            bg: 'bg-primary/10',
            border: 'border-primary/20',
            external: false,
        },
        {
            name: t('admin.quick_links.documentation'),
            icon: BookOpen,
            href: 'https://docs.featherpanel.com',
            color: 'text-blue-500',
            bg: 'bg-blue-500/10',
            border: 'border-blue-500/20',
            external: true,
        },
        {
            name: t('admin.quick_links.support_discord'),
            icon: MessageSquare,
            href: 'https://discord.mythical.systems',
            color: 'text-indigo-500',
            bg: 'bg-indigo-500/10',
            border: 'border-indigo-500/20',
            external: true,
        },
    ];

    return (
        <PageCard title={t('admin.quick_links.title')} description={t('admin.quick_links.description')} icon={Zap}>
            <div className='flex flex-wrap gap-3 md:gap-4'>
                {links.map((link) => (
                    <Link
                        key={link.name}
                        href={link.href}
                        target={link.external ? '_blank' : undefined}
                        rel={link.external ? 'noopener noreferrer' : undefined}
                        className='relative flex items-center gap-3 md:gap-4 p-3 md:p-4 rounded-xl md:rounded-2xl bg-muted/10 border border-border/50 hover:bg-muted/20 hover:scale-[1.02] active:scale-[0.98] transition-all group flex-1 min-w-[200px] sm:min-w-[240px] lg:flex-initial lg:flex-1 xl:flex-initial'
                    >
                        <div
                            className={cn(
                                'h-9 w-9 md:h-10 md:w-10 rounded-lg md:rounded-xl flex items-center justify-center border transition-all shrink-0',
                                link.bg,
                                link.color,
                                link.border,
                            )}
                        >
                            <link.icon className='h-4 w-4 md:h-5 md:w-5' />
                        </div>
                        <div className='min-w-0 flex-1'>
                            <p className='text-[10px] md:text-xs font-black uppercase tracking-widest break-words leading-tight whitespace-normal'>{link.name}</p>
                            {link.external && (
                                <ExternalLink className='h-3 w-3 text-muted-foreground opacity-50 absolute top-3 right-3 md:top-4 md:right-4 shrink-0' />
                            )}
                        </div>
                    </Link>
                ))}

                <button
                    onClick={onClearCache}
                    disabled={isClearingCache}
                    className='relative flex items-center gap-3 md:gap-4 p-3 md:p-4 rounded-xl md:rounded-2xl bg-red-500/5 border border-red-500/10 hover:bg-red-500/10 hover:scale-[1.02] active:scale-[0.98] transition-all group text-start flex-1 min-w-[200px] sm:min-w-[240px] lg:flex-initial lg:flex-1 xl:flex-initial disabled:opacity-50 disabled:cursor-not-allowed'
                >
                    <div
                        className={cn(
                            'h-9 w-9 md:h-10 md:w-10 rounded-lg md:rounded-xl flex items-center justify-center border border-red-500/20 bg-red-500/10 text-red-500 transition-all shrink-0',
                            isClearingCache && 'animate-pulse',
                        )}
                    >
                        <Trash2 className={cn('h-4 w-4 md:h-5 md:w-5', isClearingCache && 'animate-spin')} />
                    </div>
                    <div className='min-w-0 flex-1'>
                        <p className='text-[10px] md:text-xs font-black uppercase tracking-widest text-red-500 break-words leading-tight whitespace-normal'>
                            {t('admin.quick_links.clear_system_cache')}
                        </p>
                    </div>
                </button>
            </div>
        </PageCard>
    );
}
