// frontend/src/components/admin/VersionInfoWidget.vue
<template>
    <div v-if="versionInfo" class="p-6 space-y-4">
        <div class="flex items-center justify-between">
            <h2 class="text-xl font-semibold flex items-center gap-2">
                <Rocket :size="20" class="text-primary" />
                Version Information
            </h2>
            <div class="text-xs text-muted-foreground">Last checked {{ formatAgo(versionInfo.last_checked) }}</div>
        </div>

        <!-- Current Version Card -->
        <Card
            v-if="versionInfo.current"
            class="p-6 border-l-4 border-l-blue-500 bg-gradient-to-r from-blue-50/50 to-indigo-50/50 dark:from-blue-950/20 dark:to-indigo-950/20"
        >
            <div class="flex items-start gap-4">
                <div
                    class="h-12 w-12 rounded-full bg-gradient-to-br from-blue-500 to-indigo-600 flex items-center justify-center shadow-lg shrink-0"
                >
                    <Sparkles :size="24" class="text-white" />
                </div>
                <div class="flex-1 min-w-0">
                    <div class="flex flex-wrap items-center gap-3 mb-2">
                        <h3 class="text-lg font-semibold text-blue-900 dark:text-blue-100">
                            {{ versionInfo.current.release_name }}
                        </h3>
                        <span
                            class="text-sm px-3 py-1 rounded-full bg-blue-500/20 text-blue-700 dark:text-blue-300 font-medium border border-blue-200 dark:border-blue-700"
                        >
                            {{ versionInfo.current.version }}
                        </span>
                        <span
                            class="text-xs px-2 py-1 rounded-full bg-gray-500/10 text-gray-600 dark:text-gray-400 capitalize border"
                        >
                            {{ versionInfo.current.type }}
                        </span>
                    </div>
                    <p class="text-muted-foreground mb-3">{{ versionInfo.current.description }}</p>
                    <div class="flex flex-wrap items-center gap-4 text-sm text-muted-foreground">
                        <span class="flex items-center gap-1">
                            <span class="w-2 h-2 rounded-full bg-green-500"></span>
                            PHP {{ versionInfo.current.min_supported_php }}-{{ versionInfo.current.max_supported_php }}
                        </span>
                        <span>•</span>
                        <span>Released {{ formatDate(versionInfo.current.created_at) }}</span>
                    </div>
                </div>
            </div>
        </Card>

        <!-- Current Version Changelog -->
        <Card
            v-if="versionInfo.current && hasCurrentVersionChangelog(versionInfo.current)"
            class="p-6 border-l-4 border-l-indigo-500"
        >
            <div
                class="flex items-center justify-between cursor-pointer mb-4 hover:bg-muted/50 rounded-md p-2 -m-2 transition-colors"
                @click="toggleCurrentVersionChangelog"
            >
                <h4 class="text-lg font-semibold flex items-center gap-2">
                    <span class="w-2 h-2 rounded-full bg-indigo-500"></span>
                    What's in {{ versionInfo.current.release_name }}
                </h4>
                <div class="flex items-center gap-2 text-muted-foreground">
                    <span class="text-sm">{{ currentVersionChangelogOpen ? 'Hide' : 'Show' }}</span>
                    <component :is="currentVersionChangelogOpen ? ChevronUp : ChevronDown" :size="20" />
                </div>
            </div>
            <div v-show="currentVersionChangelogOpen" class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <ChangelogSection
                    v-if="versionInfo.current.changelog_added?.length"
                    title="Added"
                    :items="versionInfo.current.changelog_added"
                    color="emerald"
                    icon="+"
                />
                <ChangelogSection
                    v-if="versionInfo.current.changelog_fixed?.length"
                    title="Fixed"
                    :items="versionInfo.current.changelog_fixed"
                    color="blue"
                    icon="🔧"
                />
                <ChangelogSection
                    v-if="versionInfo.current.changelog_improved?.length"
                    title="Improved"
                    :items="versionInfo.current.changelog_improved"
                    color="purple"
                    icon="⚡"
                />
                <ChangelogSection
                    v-if="versionInfo.current.changelog_updated?.length"
                    title="Updated"
                    :items="versionInfo.current.changelog_updated"
                    color="amber"
                    icon="🔄"
                />
                <ChangelogSection
                    v-if="versionInfo.current.changelog_removed?.length"
                    title="Removed"
                    :items="versionInfo.current.changelog_removed"
                    color="red"
                    icon="-"
                />
            </div>
        </Card>

        <!-- Update Available Notification -->
        <div v-if="versionInfo.update_available && versionInfo.latest" class="space-y-4">
            <Card
                class="p-6 border-l-4 border-l-emerald-500 bg-gradient-to-r from-emerald-50/50 to-green-50/50 dark:from-emerald-950/20 dark:to-green-950/20 shadow-lg"
            >
                <div class="flex items-start gap-4">
                    <div
                        class="h-12 w-12 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center shadow-lg shrink-0"
                    >
                        <AlertTriangle :size="24" class="text-white" />
                    </div>
                    <div class="flex-1 min-w-0">
                        <div class="flex flex-wrap items-center gap-3 mb-2">
                            <h3 class="text-lg font-semibold text-emerald-800 dark:text-emerald-200">
                                🚀 Update Available!
                            </h3>
                            <span
                                class="text-sm px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-700 dark:text-emerald-300 font-medium border border-emerald-200 dark:border-emerald-700"
                            >
                                {{ versionInfo.latest.version }}
                            </span>
                        </div>
                        <p class="text-emerald-700 dark:text-emerald-300 mb-3">
                            <strong>{{ versionInfo.latest.release_name }}</strong> -
                            {{ versionInfo.latest.description }}
                        </p>
                        <div class="flex flex-wrap items-center gap-4 text-sm text-emerald-600 dark:text-emerald-400">
                            <span class="flex items-center gap-1">
                                <span class="w-2 h-2 rounded-full bg-green-500"></span>
                                PHP {{ versionInfo.latest.min_supported_php }}-{{
                                    versionInfo.latest.max_supported_php
                                }}
                            </span>
                            <span>•</span>
                            <span>Released {{ formatDate(versionInfo.latest.created_at) }}</span>
                        </div>
                    </div>
                </div>
            </Card>

            <!-- Changelog -->
            <Card class="p-6">
                <div
                    class="flex items-center justify-between cursor-pointer mb-4 hover:bg-muted/50 rounded-md p-2 -m-2 transition-colors"
                    @click="toggleLatestVersionChangelog"
                >
                    <h4 class="text-lg font-semibold">What's New in {{ versionInfo.latest.release_name }}</h4>
                    <div class="flex items-center gap-2 text-muted-foreground">
                        <span class="text-sm">{{ latestVersionChangelogOpen ? 'Hide' : 'Show' }}</span>
                        <component :is="latestVersionChangelogOpen ? ChevronUp : ChevronDown" :size="20" />
                    </div>
                </div>
                <div v-show="latestVersionChangelogOpen" class="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <ChangelogSection
                        v-if="versionInfo.latest.changelog_added?.length"
                        title="Added"
                        :items="versionInfo.latest.changelog_added"
                        color="emerald"
                        icon="+"
                    />
                    <ChangelogSection
                        v-if="versionInfo.latest.changelog_fixed?.length"
                        title="Fixed"
                        :items="versionInfo.latest.changelog_fixed"
                        color="blue"
                        icon="🔧"
                    />
                    <ChangelogSection
                        v-if="versionInfo.latest.changelog_improved?.length"
                        title="Improved"
                        :items="versionInfo.latest.changelog_improved"
                        color="purple"
                        icon="⚡"
                    />
                    <ChangelogSection
                        v-if="versionInfo.latest.changelog_updated?.length"
                        title="Updated"
                        :items="versionInfo.latest.changelog_updated"
                        color="amber"
                        icon="🔄"
                    />
                    <ChangelogSection
                        v-if="versionInfo.latest.changelog_removed?.length"
                        title="Removed"
                        :items="versionInfo.latest.changelog_removed"
                        color="red"
                        icon="-"
                    />
                </div>
            </Card>
        </div>

        <!-- No Update Available -->
        <div v-else-if="versionInfo.current" class="text-center pt-8">
            <Card
                class="p-8 bg-gradient-to-r from-emerald-50/50 to-green-50/50 dark:from-emerald-950/20 dark:to-green-950/20 border-l-4 border-l-emerald-500"
            >
                <div
                    class="h-16 w-16 rounded-full bg-gradient-to-br from-emerald-500 to-green-600 flex items-center justify-center mx-auto mb-4 shadow-lg"
                >
                    <CheckCircle2 :size="32" class="text-white" />
                </div>
                <h3 class="text-lg font-semibold text-emerald-800 dark:text-emerald-200 mb-2">🎉 You're up to date!</h3>
                <p class="text-muted-foreground">You're running the latest version of FeatherPanel.</p>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { computed, ref } from 'vue';
import { Card } from '@/components/ui/card';
import { Sparkles, AlertTriangle, CheckCircle2, ChevronDown, ChevronUp, Rocket } from 'lucide-vue-next';
import { useDashboardStore } from '@/stores/dashboard';
import ChangelogSection from './ChangelogSection.vue';

const dashboardStore = useDashboardStore();

const versionInfo = computed(() => dashboardStore.getVersionInfo);

const currentVersionChangelogOpen = ref(localStorage.getItem('currentVersionChangelogOpen') !== 'false');
const latestVersionChangelogOpen = ref(localStorage.getItem('latestVersionChangelogOpen') !== 'false');

const toggleCurrentVersionChangelog = () => {
    currentVersionChangelogOpen.value = !currentVersionChangelogOpen.value;
    localStorage.setItem('currentVersionChangelogOpen', currentVersionChangelogOpen.value.toString());
};

const toggleLatestVersionChangelog = () => {
    latestVersionChangelogOpen.value = !latestVersionChangelogOpen.value;
    localStorage.setItem('latestVersionChangelogOpen', latestVersionChangelogOpen.value.toString());
};

function formatAgo(dateStr: string | null): string {
    if (!dateStr) return 'never';
    const d = new Date(dateStr.replace(' ', 'T'));
    const diffMs = Date.now() - d.getTime();
    if (Number.isNaN(diffMs)) return dateStr;
    const minutes = Math.floor(diffMs / 60000);
    if (minutes < 1) return 'just now';
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
}

function formatDate(dateStr: string | null): string {
    if (!dateStr) return 'Unknown';
    try {
        const d = new Date(dateStr.replace(' ', 'T'));
        return d.toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
        });
    } catch {
        return dateStr;
    }
}

interface VersionData {
    changelog_added?: string[];
    changelog_fixed?: string[];
    changelog_improved?: string[];
    changelog_updated?: string[];
    changelog_removed?: string[];
}

function hasCurrentVersionChangelog(version: VersionData | null): boolean {
    if (!version) return false;
    return Boolean(
        (Array.isArray(version.changelog_added) && version.changelog_added.length > 0) ||
            (Array.isArray(version.changelog_fixed) && version.changelog_fixed.length > 0) ||
            (Array.isArray(version.changelog_improved) && version.changelog_improved.length > 0) ||
            (Array.isArray(version.changelog_updated) && version.changelog_updated.length > 0) ||
            (Array.isArray(version.changelog_removed) && version.changelog_removed.length > 0),
    );
}
</script>

// featherpanel-frontendv2/src/components/admin/VersionInfoWidget.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client'

import { toast } from 'sonner'

import React, { useState } from 'react'
import { Package, Download, ExternalLink, ShieldCheck, CheckCircle2, ChevronDown, ChevronUp, Cpu } from 'lucide-react'
import { PageCard } from '@/components/featherui/PageCard'
import ReactMarkdown from 'react-markdown'
import { ChangelogSection } from './ChangelogSection'

interface ChangelogData {
    changelog_added?: string[]
    changelog_fixed?: string[]
    changelog_improved?: string[]
    changelog_updated?: string[]
    changelog_removed?: string[]
    release_description?: string
}

interface VersionInfoWidgetProps {
    version?: {
        current: {
            version: string
            type: string
            release_name: string
            release_description?: string
            php_version?: string
            changelog_added?: string[]
            changelog_fixed?: string[]
            changelog_improved?: string[]
            changelog_updated?: string[]
            changelog_removed?: string[]
        } | null
        latest: {
            version: string
            type: string
            release_description?: string
            changelog_added?: string[]
            changelog_fixed?: string[]
            changelog_improved?: string[]
            changelog_updated?: string[]
            changelog_removed?: string[]
        } | null
        update_available: boolean
        last_checked: string | null
    }
    loading?: boolean
}

import { useTranslation } from '@/contexts/TranslationContext'

// ... imports

export function VersionInfoWidget({ version }: VersionInfoWidgetProps) {
    const { t } = useTranslation()
    const [showChangelog, setShowChangelog] = useState(version?.update_available ?? false)
    
    const isLatest = !version?.update_available
    const current = version?.current
    const latest = version?.latest

    const hasChangelog = (data: ChangelogData | null) => {
        if (!data) return false
        return (data.changelog_added?.length || 0) > 0 ||
               (data.changelog_fixed?.length || 0) > 0 ||
               (data.changelog_improved?.length || 0) > 0 ||
               (data.changelog_updated?.length || 0) > 0 ||
               (data.changelog_removed?.length || 0) > 0
    }

    const changelogData = version?.update_available ? latest : current

    return (
        <PageCard
            title={t('admin.version.title')}
            description={t('admin.version.description')}
            icon={Package}
        >
            <div className="space-y-6">
                <div className="flex items-center justify-between p-4 rounded-3xl bg-secondary/30 border border-border/50">
                    <div className="space-y-1">
                        <p className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">{t('admin.version.current_build')}</p>
                        <h4 className="text-xl font-black">{current?.version || 'unknown'}</h4>
                    </div>
                    <div className="text-right space-y-1">
                        <p className="text-[10px] font-black uppercase text-muted-foreground tracking-widest">{t('admin.version.release_type')}</p>
                        <span className="px-3 py-1 rounded-full bg-primary/20 text-primary text-[10px] font-black uppercase tracking-widest border border-primary/30">
                            {current?.type || 'Stable'}
                        </span>
                    </div>
                </div>

                <div className="flex flex-col gap-3">
                    {isLatest ? (
                        <div className="flex items-center gap-3 p-4 rounded-2xl bg-emerald-500/5 border border-emerald-500/10 text-emerald-500">
                            <CheckCircle2 className="h-5 w-5" />
                            <p className="text-sm font-bold">{t('admin.version.up_to_date')}</p>
                        </div>
                    ) : (
                        <div className="flex flex-col gap-4 p-5 rounded-3xl bg-amber-500/5 border border-amber-500/20 text-amber-500">
                            <div className="flex items-center gap-3">
                                <Download className="h-5 w-5 animate-bounce" />
                                <div className="space-y-0.5">
                                    <p className="text-sm font-black uppercase tracking-tight">{t('admin.version.update_available', { version: latest?.version || 'Unknown' })}</p>
                                    <p className="text-[10px] font-bold uppercase opacity-70">{t('admin.version.update_description')}</p>
                                </div>
                            </div>
                            <button className="w-full py-3 rounded-xl bg-amber-500 text-amber-950 text-[10px] font-black uppercase tracking-widest hover:bg-amber-400 transition-colors shadow-lg shadow-amber-500/20">
                                {t('admin.version.update_now')}
                            </button>
                        </div>
                    )}

                    {current?.php_version && (
                        <div className="flex items-center gap-3 p-4 rounded-2xl bg-primary/5 border border-primary/10">
                            <Cpu className="h-4 w-4 text-primary" />
                            <p className="text-xs font-bold text-muted-foreground">
                                {t('admin.version.recommended_php')} <span className="text-foreground">{current.php_version}</span>
                            </p>
                        </div>
                    )}

                    {(current?.release_description || latest?.release_description) && (
                        <div className="p-4 rounded-2xl bg-muted/20 border border-border/50">
                            <div className="prose prose-sm prose-invert max-w-none text-xs text-muted-foreground leading-relaxed">
                                <ReactMarkdown>
                                    {version?.update_available ? latest?.release_description : current?.release_description}
                                </ReactMarkdown>
                            </div>
                        </div>
                    )}

                    {hasChangelog(changelogData as ChangelogData) && (
                        <div className="space-y-3">
                            <button 
                                onClick={() => setShowChangelog(!showChangelog)}
                                className="flex items-center justify-between w-full p-4 rounded-2xl bg-muted/10 border border-border/40 hover:bg-muted/20 transition-all group"
                            >
                                <div className="flex items-center gap-2">
                                    <Package className="h-4 w-4 text-primary" />
                                    <span className="text-[10px] font-black uppercase tracking-widest">{t('admin.version.view_changelog')}</span>
                                </div>
                                {showChangelog ? <ChevronUp className="h-4 w-4 opacity-50" /> : <ChevronDown className="h-4 w-4 opacity-50" />}
                            </button>

                            {showChangelog && (
                                <div className="p-6 rounded-3xl bg-muted/5 border border-border/30 space-y-8 animate-in fade-in slide-in-from-top-2 duration-300">
                                    <ChangelogSection 
                                        title={t('admin.version.changelog.added')} 
                                        items={changelogData?.changelog_added || []} 
                                        color="emerald" 
                                        icon="+" 
                                    />
                                    <ChangelogSection 
                                        title={t('admin.version.changelog.fixed')} 
                                        items={changelogData?.changelog_fixed || []} 
                                        color="red" 
                                        icon="!" 
                                    />
                                    <ChangelogSection 
                                        title={t('admin.version.changelog.improved')} 
                                        items={changelogData?.changelog_improved || []} 
                                        color="blue" 
                                        icon="~" 
                                    />
                                    <ChangelogSection 
                                        title={t('admin.version.changelog.updated')} 
                                        items={changelogData?.changelog_updated || []} 
                                        color="amber" 
                                        icon="^" 
                                    />
                                    <ChangelogSection 
                                        title={t('admin.version.changelog.removed')} 
                                        items={changelogData?.changelog_removed || []} 
                                        color="purple" 
                                        icon="-" 
                                    />
                                </div>
                            )}
                        </div>
                    )}
                    <div className="grid grid-cols-2 gap-3 mt-2">
                        <button 
                            onClick={() => toast.info('Integrity Check', { description: t('admin.version.integrity_coming_soon') })}
                            className="flex items-center justify-center gap-2 p-3 rounded-xl bg-muted/20 border border-border/50 hover:bg-muted/30 transition-all text-[10px] font-black uppercase tracking-widest group"
                        >
                            <ShieldCheck className="h-4 w-4 text-primary group-hover:scale-110 transition-transform" />
                            {t('admin.version.verify_integrity')}
                        </button>
                        <a 
                            href="https://featherpanel.com" 
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center justify-center gap-2 p-3 rounded-xl bg-muted/20 border border-border/50 hover:bg-muted/30 transition-all text-[10px] font-black uppercase tracking-widest group"
                        >
                            <ExternalLink className="h-4 w-4 text-primary group-hover:scale-110 transition-transform" />
                            {t('admin.version.official_site')}
                        </a>
                    </div>

                    {version?.last_checked && (
                        <p className="text-[9px] font-bold text-center text-muted-foreground uppercase tracking-widest opacity-40">
                            {t('admin.version.last_checked', { date: new Date(version.last_checked).toLocaleString() })}
                        </p>
                    )}
                </div>
            </div>
        </PageCard>
    )
}
