// frontend/src/pages/admin/DatabaseManagement.vue
<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Database as DatabaseIcon, Activity, Wrench, AlertTriangle } from 'lucide-vue-next';

interface StatusResp {
    success: boolean;
    data: {
        engine: string;
        version: string;
        uptime_seconds: number;
        threads_connected: number;
        threads_running: number;
        connections_total: number;
        aborted_connects: number;
        queries_total: number;
        questions_total: number;
        qps: number;
        bytes_received: number;
        bytes_sent: number;
    };
}

const loading = ref(false);
const status = ref<StatusResp['data'] | null>(null);
const migRunning = ref(false);
const migOutput = ref('');

async function fetchStatus() {
    loading.value = true;
    try {
        const resp = await fetch('/api/admin/databases/management/status');
        const json: StatusResp = await resp.json();
        if (json.success) status.value = json.data;
    } finally {
        loading.value = false;
    }
}

async function runMigrations() {
    migRunning.value = true;
    migOutput.value = '';
    try {
        const resp = await fetch('/api/admin/databases/management/migrate', { method: 'POST' });
        const json = await resp.json();
        if (json.success) {
            migOutput.value = json.data.output ?? '';
        } else {
            migOutput.value = json.message ?? 'Failed to run migrations';
        }
    } catch (e: unknown) {
        migOutput.value = String(e);
    } finally {
        migRunning.value = false;
    }
}

fetchStatus();
</script>

<template>
    <DashboardLayout :breadcrumbs="[{ text: 'Database', isCurrent: true, href: '/admin/databases/management' }]">
        <div class="min-h-screen bg-background">
            <div class="p-4 sm:p-6 space-y-6">
                <!-- Header -->
                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                    <div>
                        <h1 class="text-2xl sm:text-3xl font-bold text-foreground mb-1">Database Management</h1>
                        <p class="text-sm sm:text-base text-muted-foreground">
                            Inspect database health and run migrations
                        </p>
                    </div>
                    <div class="flex flex-col sm:flex-row items-stretch sm:items-center gap-2">
                        <Button variant="outline" :disabled="loading" class="w-full sm:w-auto" @click="fetchStatus"
                            >Refresh</Button
                        >
                        <Button :disabled="migRunning" class="w-full sm:w-auto" @click="runMigrations">
                            <span
                                v-if="migRunning"
                                class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"
                            ></span>
                            Run Migrations
                        </Button>
                    </div>
                </div>

                <!-- Loading -->
                <div v-if="loading" class="flex items-center justify-center py-12">
                    <div class="flex items-center gap-3">
                        <div
                            class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"
                        ></div>
                        <span class="text-muted-foreground">Loading database status...</span>
                    </div>
                </div>

                <!-- Status Cards -->
                <div v-else-if="status" class="grid grid-cols-1 sm:grid-cols-2 gap-4 sm:gap-6">
                    <Card class="p-4">
                        <div class="font-semibold mb-3">Overview</div>
                        <div class="text-sm text-muted-foreground space-y-1">
                            <div><span class="font-medium text-foreground">Engine:</span> {{ status.engine }}</div>
                            <div><span class="font-medium text-foreground">Version:</span> {{ status.version }}</div>
                            <div>
                                <span class="font-medium text-foreground">Uptime (s):</span> {{ status.uptime_seconds }}
                            </div>
                            <div><span class="font-medium text-foreground">QPS:</span> {{ status.qps.toFixed(2) }}</div>
                        </div>
                    </Card>
                    <Card class="p-4">
                        <div class="font-semibold mb-3">Connections</div>
                        <div class="text-sm text-muted-foreground space-y-1">
                            <div>
                                <span class="font-medium text-foreground">Threads connected:</span>
                                {{ status.threads_connected }}
                            </div>
                            <div>
                                <span class="font-medium text-foreground">Threads running:</span>
                                {{ status.threads_running }}
                            </div>
                            <div>
                                <span class="font-medium text-foreground">Total connections:</span>
                                {{ status.connections_total }}
                            </div>
                            <div>
                                <span class="font-medium text-foreground">Aborted connects:</span>
                                {{ status.aborted_connects }}
                            </div>
                        </div>
                    </Card>
                    <Card class="p-4">
                        <div class="font-semibold mb-3">Queries</div>
                        <div class="text-sm text-muted-foreground space-y-1">
                            <div>
                                <span class="font-medium text-foreground">Queries total:</span>
                                {{ status.queries_total }}
                            </div>
                            <div>
                                <span class="font-medium text-foreground">Questions total:</span>
                                {{ status.questions_total }}
                            </div>
                        </div>
                    </Card>
                    <Card class="p-4">
                        <div class="font-semibold mb-3">Network</div>
                        <div class="text-sm text-muted-foreground space-y-1">
                            <div>
                                <span class="font-medium text-foreground">Bytes received:</span>
                                {{ status.bytes_received }}
                            </div>
                            <div>
                                <span class="font-medium text-foreground">Bytes sent:</span> {{ status.bytes_sent }}
                            </div>
                        </div>
                    </Card>
                </div>

                <!-- Migration Output -->
                <Card class="p-0 overflow-hidden">
                    <div class="p-4 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                        <div class="font-semibold">Migrations Output</div>
                        <Button variant="outline" size="sm" class="w-full sm:w-auto" @click="migOutput = ''"
                            >Clear</Button
                        >
                    </div>
                    <pre
                        class="text-xs whitespace-pre-wrap bg-black text-green-300 p-4 min-h-[150px] overflow-x-auto"
                        >{{ migOutput }}</pre
                    >
                </Card>

                <!-- Database Management help cards -->
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <DatabaseIcon class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">What is this page?</div>
                                    <p>
                                        View your database engine status and basic metrics. Useful for quick health
                                        checks and verifying connectivity.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <Activity class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Status & Metrics</div>
                                    <p>
                                        Inspect engine/version, uptime, connections, QPS, and network I/O. Re‑check
                                        using the Refresh button when diagnosing issues.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <Wrench class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Migrations</div>
                                    <p>
                                        Run database migrations when upgrading or installing plugins. Review output
                                        below and back up before major changes.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card class="md:col-span-2 lg:col-span-3">
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <AlertTriangle class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Safety & Backups</div>
                                    <p>
                                        Always maintain recent backups before applying migrations or installing plugins
                                        that alter schemas. FeatherPanel and its developers are not liable for changes
                                        you make.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>
    </DashboardLayout>
</template>

<style scoped>
.min-h\[150px\] {
    min-height: 150px;
}
</style>

// frontendv2/src/app/(docs)/icanhasfeatherpanel/events/database-management/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
'use client';

import Link from 'next/link';
import { ArrowLeft, Zap, Code } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

const categoryData = {
    name: 'DatabaseManagement',
    events: [
        {
            method: 'onDatabaseManagementError',
            name: 'featherpanel:admin:database_management:error',
            callback: 'string error message, array context.',
            category: 'DatabaseManagement',
            exampleCode:
                'use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\DatabaseManagementEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(DatabaseManagementEvent::onDatabaseManagementError(), function ($message, $context) {\n        // Handle featherpanel:admin:database_management:error\n        // Parameters: string error message, array context.\n    });\n}',
        },
        {
            method: 'onMigrationsExecuted',
            name: 'featherpanel:admin:database_management:migrations:executed',
            callback: 'array migration results.',
            category: 'DatabaseManagement',
            actualData: ['executed', 'executed_by', 'failed', 'skipped', 'total_time'],
            sourceFiles: ['backend/app/Controllers/Admin/DatabaseManagmentController.php'],
            exampleCode:
                'use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\DatabaseManagementEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(DatabaseManagementEvent::onMigrationsExecuted(), function ($executed, $executedBy, $failed, $skipped, $totalTime) {\n        // Handle featherpanel:admin:database_management:migrations:executed\n        // Data keys: executed, executed_by, failed, skipped, total_time\n    });\n}',
        },
        {
            method: 'onStatusRetrieved',
            name: 'featherpanel:admin:database_management:status:retrieved',
            callback: 'array status data.',
            category: 'DatabaseManagement',
            exampleCode:
                'use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\DatabaseManagementEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(DatabaseManagementEvent::onStatusRetrieved(), function ($data) {\n        // Handle featherpanel:admin:database_management:status:retrieved\n        // Parameters: array status data.\n    });\n}',
        },
    ],
};

export default function CategoryEventsPage() {
    // Helper to unescape JSON-escaped strings
    const unescapeCode = (str) => {
        // Replace double backslashes (escaped in JSON) with single backslash
        // Replace escaped newlines with actual newlines
        return str.replace(/\\\\/g, '\\').replace(/\\n/g, '\n');
    };

    return (
        <div className='min-h-screen bg-background'>
            <div className='container mx-auto px-4 py-16 max-w-6xl'>
                <Link href='/icanhasfeatherpanel/events'>
                    <Button variant='ghost' className='mb-8 -ml-4'>
                        <ArrowLeft className='w-4 h-4 mr-2' />
                        Back to Events
                    </Button>
                </Link>

                <div className='mb-12 space-y-4'>
                    <div className='flex items-center gap-3'>
                        <div className='p-3 rounded-xl bg-primary/10 border border-primary/20 backdrop-blur-sm'>
                            <Zap className='w-6 h-6 text-primary' />
                        </div>
                        <div>
                            <h1 className='text-4xl font-black tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent'>
                                {categoryData.name}
                            </h1>
                            <p className='text-muted-foreground mt-1'>
                                {categoryData.events.length} event{categoryData.events.length !== 1 ? 's' : ''} in this
                                category
                            </p>
                        </div>
                    </div>
                </div>

                <div className='space-y-4'>
                    {categoryData.events.map((event) => (
                        <Card
                            key={event.name}
                            className='border-border/50 bg-card/50 backdrop-blur-sm hover:bg-card/80 transition-colors'
                        >
                            <CardHeader>
                                <div className='flex items-start justify-between gap-4 flex-wrap'>
                                    <div className='flex-1 min-w-0'>
                                        <div className='flex items-center gap-2 mb-2 flex-wrap'>
                                            <Code className='w-4 h-4 text-primary flex-shrink-0' />
                                            <CardTitle className='text-lg font-mono text-foreground break-all'>
                                                {event.name}
                                            </CardTitle>
                                        </div>
                                        <CardDescription className='text-muted-foreground mb-3'>
                                            <span className='font-semibold'>Callback parameters:</span> {event.callback}
                                        </CardDescription>
                                    </div>
                                    <Badge
                                        variant='outline'
                                        className='text-xs font-mono bg-muted/30 border-border/50 text-foreground/80 flex-shrink-0'
                                    >
                                        {event.method}
                                    </Badge>
                                </div>
                            </CardHeader>
                            <CardContent className='space-y-4'>
                                {event.actualData && event.actualData.length > 0 && (
                                    <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                        <h4 className='text-sm font-semibold text-foreground mb-2'>
                                            Event Data Structure
                                        </h4>
                                        <p className='text-xs text-muted-foreground mb-3'>
                                            This event receives the following data when emitted:
                                        </p>
                                        <div className='flex flex-wrap gap-2'>
                                            {event.actualData.map((key) => (
                                                <Badge
                                                    key={key}
                                                    variant='outline'
                                                    className='text-xs font-mono bg-muted/50 border-border/50 text-foreground/80'
                                                >
                                                    {key}
                                                </Badge>
                                            ))}
                                        </div>
                                        {event.sourceFiles && event.sourceFiles.length > 0 && (
                                            <div className='mt-3 pt-3 border-t border-border/30'>
                                                <p className='text-xs text-muted-foreground mb-1'>Emitted from:</p>
                                                <div className='space-y-1'>
                                                    {event.sourceFiles.slice(0, 2).map((file) => (
                                                        <code
                                                            key={file}
                                                            className='text-xs text-muted-foreground block truncate'
                                                        >
                                                            {file}
                                                        </code>
                                                    ))}
                                                    {event.sourceFiles.length > 2 && (
                                                        <p className='text-xs text-muted-foreground italic'>
                                                            +{event.sourceFiles.length - 2} more location
                                                            {event.sourceFiles.length - 2 !== 1 ? 's' : ''}
                                                        </p>
                                                    )}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                )}
                                <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                    <h4 className='text-sm font-semibold text-foreground mb-2'>Usage Example</h4>
                                    <pre className='p-3 rounded-lg bg-muted/50 border border-border/50 overflow-x-auto'>
                                        <code className='text-xs font-mono text-foreground'>
                                            {unescapeCode(event.exampleCode)}
                                        </code>
                                    </pre>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </div>
    );
}
