// featherpanel-frontendv2/src/app/dashboard/tickets/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import axios from 'axios'
import {
    Ticket as TicketIcon,
    Plus,
    Search,
    ChevronLeft,
    ChevronRight,
    Trash2
} from 'lucide-react'
import { useTranslation } from '@/contexts/TranslationContext'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { HeadlessSelect } from '@/components/ui/headless-select'
import { HeadlessModal } from '@/components/ui/headless-modal'
import {

} from '@/components/ui/card'

// Types
interface Category {
    id: number
    name: string
}

interface Status {
    id: number
    name: string
}

interface ApiTicket {
    id: number
    uuid: string
    title: string
    created_at: string
    status?: {
        id: number
        name: string
        color?: string
    }
    priority?: {
        id: number
        name: string
        color?: string
    }
    category?: {
        id: number
        name: string
    }
    server?: {
        id: number
        name: string
    }
}

interface PaginationState {
    page: number
    pageSize: number
    total: number
    hasNext: boolean
    hasPrev: boolean
    from: number
    to: number
}

interface ApiPaginationResponse {
    success: boolean
    data: {
        tickets: ApiTicket[]
        pagination: {
            total_records: number
            has_next: boolean
            has_prev: boolean
            from: number
            to: number
            current_page: number
        }
    }
}

export default function TicketsPage() {
    const { t } = useTranslation()
    const router = useRouter()
    
    // State
    const [loading, setLoading] = useState(true)
    const [tickets, setTickets] = useState<ApiTicket[]>([])
    const [categories, setCategories] = useState<Category[]>([])
    const [statuses, setStatuses] = useState<Status[]>([])
    
    // Filters - Use specific types for Select values
    const [filterStatus, setFilterStatus] = useState<string | number>('all')
    const [filterCategory, setFilterCategory] = useState<string | number>('all')
    const [searchQuery, setSearchQuery] = useState('')
    
    // Pagination
    const [pagination, setPagination] = useState<PaginationState>({
        page: 1,
        pageSize: 10,
        total: 0,
        hasNext: false,
        hasPrev: false,
        from: 0,
        to: 0
    })

    // Delete Dialog
    const [showDeleteDialog, setShowDeleteDialog] = useState(false)
    const [ticketToDelete, setTicketToDelete] = useState<ApiTicket | null>(null)
    const [deleting, setDeleting] = useState(false)

    // Initial Fetch
    useEffect(() => {
        const fetchFilters = async () => {
            try {
                // Using unknown cast for safety then verifying shape if needed, but for simple lists we trust API mostly
                const [catsRes, statsRes] = await Promise.all([
                    axios.get('/api/user/tickets/categories').catch(() => ({ data: { data: { categories: [] } } })),
                    axios.get('/api/user/tickets/statuses').catch(() => ({ data: { data: { statuses: [] } } }))
                ])
                
                const cats = (catsRes.data as { data: { categories: Category[] } })?.data?.categories || []
                const stats = (statsRes.data as { data: { statuses: Status[] } })?.data?.statuses || []

                setCategories(cats)
                setStatuses(stats)
            } catch (error: unknown) {
                console.error('Failed to fetch filters', error)
            }
        }
        fetchFilters()
    }, [])

    // Fetch Tickets on changes
    useEffect(() => {
        fetchTickets()
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [pagination.page, filterStatus, filterCategory])

    const fetchTickets = async () => {
        setLoading(true)
        try {
            const params: Record<string, string | number> = {
                page: pagination.page,
                limit: pagination.pageSize,
            }
            if (searchQuery) params.search = searchQuery
            if (filterStatus !== 'all') params.status_id = filterStatus
            if (filterCategory !== 'all') params.category_id = filterCategory

            const response = await axios.get<ApiPaginationResponse>('/api/user/tickets', { params })
            
            if (response.data.success) {
                setTickets(response.data.data.tickets || [])
                const meta = response.data.data.pagination
                setPagination(prev => ({
                    ...prev,
                    total: meta.total_records,
                    hasNext: meta.has_next,
                    hasPrev: meta.has_prev,
                    from: meta.from,
                    to: meta.to,
                    page: meta.current_page
                }))
            }
        } catch (error: unknown) {
            console.error('Failed to fetch tickets', error)
            setTickets([])
        } finally {
            setLoading(false)
        }
    }

    const handleSearch = (e: React.FormEvent) => {
        e.preventDefault()
        setPagination(prev => ({ ...prev, page: 1 }))
        fetchTickets()
    }

    const confirmDeleteTicket = async () => {
        if (!ticketToDelete) return
        setDeleting(true)
        try {
            await axios.delete(`/api/user/tickets/${ticketToDelete.uuid}`)
            setShowDeleteDialog(false)
            setTicketToDelete(null)
            fetchTickets()
        } catch (error: unknown) {
            console.error('Failed to delete ticket', error)
        } finally {
            setDeleting(false)
        }
    }

    // Format options for HeadlessSelect
    const statusOptions = [
        { id: 'all', name: t('tickets.allStatuses') },
        ...statuses.map(s => ({ id: s.id, name: s.name }))
    ]
    
    const categoryOptions = [
        { id: 'all', name: t('tickets.allCategories') },
        ...categories.map(c => ({ id: c.id, name: c.name }))
    ]

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">{t('tickets.title')}</h1>
                    <p className="text-muted-foreground">{t('tickets.viewAndManage')}</p>
                </div>
                <Link href="/dashboard/tickets/create">
                    <Button>
                        <Plus className="mr-2 h-4 w-4" />
                        {t('tickets.createTicket')}
                    </Button>
                </Link>
            </div>

            {/* Filters */}
            <div className="bg-card/50 backdrop-blur-sm rounded-xl border border-border/50 p-1">
                <div className="flex flex-col md:flex-row gap-4 p-4">
                    <div className="flex-1 flex flex-col md:flex-row gap-4 w-full">
                         <div className="w-full md:w-56 z-20">
                            <HeadlessSelect 
                                value={filterStatus}
                                onChange={setFilterStatus}
                                options={statusOptions}
                                placeholder={t('tickets.allStatuses')}
                            />
                         </div>
                         <div className="w-full md:w-56 z-10">
                            <HeadlessSelect
                                value={filterCategory}
                                onChange={setFilterCategory}
                                options={categoryOptions}
                                placeholder={t('tickets.allCategories')}
                            />
                         </div>
                    </div>
                    <form onSubmit={handleSearch} className="flex gap-2 w-full md:w-auto relative">
                        <Input 
                            placeholder={t('tickets.searchTickets')} 
                            value={searchQuery}
                            onChange={(e) => setSearchQuery(e.target.value)}
                            className="w-full md:w-64 bg-background/50 border-border/50 focus:border-primary/50"
                        />
                        <Button type="submit" variant="ghost" size="icon" className="absolute right-1 top-1">
                            <Search className="h-4 w-4 text-muted-foreground" />
                        </Button>
                    </form>
                </div>
            </div>

            {/* List */}
            {loading ? (
                <div className="space-y-4">
                    {[1, 2, 3].map(i => (
                         <div key={i} className="h-24 bg-card/20 animate-pulse rounded-xl border border-white/5" />
                    ))}
                </div>
            ) : tickets.length === 0 ? (
                <div className="text-center py-24 rounded-xl border border-dashed border-border/50 bg-card/10">
                    <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-primary/10 mb-6">
                        <TicketIcon className="h-8 w-8 text-primary" />
                    </div>
                    <h3 className="text-xl font-medium mb-2">{t('tickets.noTicketsFound')}</h3>
                    <p className="text-muted-foreground mb-6 max-w-sm mx-auto">{t('tickets.createFirstTicket')}</p>
                    <Link href="/dashboard/tickets/create">
                        <Button variant="default" className="bg-primary hover:bg-primary/90 text-primary-foreground text-base px-6 py-6 h-auto shadow-lg shadow-primary/20">
                           <Plus className="w-5 h-5 mr-2" />
                           {t('tickets.createTicket')}
                        </Button>
                    </Link>
                </div>
            ) : (
                <div className="bg-card rounded-xl border border-border/50 shadow-sm overflow-hidden">
                    <div className="divide-y divide-border/50">
                        {tickets.map(ticket => (
                            <div 
                                key={ticket.uuid}
                                className="p-5 hover:bg-white/2 transition-all duration-200 flex flex-col sm:flex-row sm:items-center justify-between gap-4 group cursor-pointer border-l-2 border-l-transparent hover:border-l-primary"
                                onClick={() => router.push(`/dashboard/tickets/${ticket.uuid}`)}
                            >
                                <div className="flex-1">
                                    <div className="flex items-center gap-3 mb-2">
                                        <h3 className="font-semibold text-lg text-foreground group-hover:text-primary transition-colors">
                                            {ticket.title}
                                        </h3>
                                        <div className="flex gap-2">
                                            {ticket.status && (
                                                <Badge 
                                                    className="rounded-md px-2 py-0.5 font-medium border-0"
                                                    style={{ 
                                                        backgroundColor: ticket.status.color ? `${ticket.status.color}20` : 'hsl(var(--primary) / 0.1)',
                                                        color: ticket.status.color || 'hsl(var(--primary))',
                                                    }}
                                                >
                                                    {ticket.status.name}
                                                </Badge>
                                            )}
                                            {ticket.priority && (
                                                <Badge variant="secondary" className="bg-secondary/50 text-secondary-foreground/80 border-0 rounded-md">
                                                    {ticket.priority.name}
                                                </Badge>
                                            )}
                                        </div>
                                    </div>
                                    <div className="flex items-center gap-3 text-sm text-muted-foreground">
                                        <span className="font-mono text-xs opacity-50">#{ticket.id}</span>
                                        {ticket.category && (
                                            <>
                                                <span className="w-1 h-1 rounded-full bg-muted-foreground/30" />
                                                <span className="flex items-center gap-1.5">
                                                     {ticket.category.name}
                                                </span>
                                            </>
                                        )}
                                        <span className="w-1 h-1 rounded-full bg-muted-foreground/30" />
                                        <span>{new Date(ticket.created_at).toLocaleDateString()}</span>
                                    </div>
                                </div>
                                <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity transform translate-x-2 group-hover:translate-x-0">
                                     <Button
                                        variant="ghost"
                                        size="icon"
                                        className="text-muted-foreground hover:text-destructive hover:bg-destructive/10 rounded-full h-8 w-8"
                                        onClick={(e) => {
                                            e.stopPropagation()
                                            setTicketToDelete(ticket)
                                            setShowDeleteDialog(true)
                                        }}
                                     >
                                        <Trash2 className="h-4 w-4" />
                                     </Button>
                                     <div className="ml-2 pl-4 border-l border-border/50">
                                         <ChevronRight className="h-5 w-5 text-muted-foreground/50" />
                                     </div>
                                </div>
                            </div>
                        ))}
                    </div>
                    {/* Pagination */}
                    {pagination.total > 0 && (
                        <div className="p-4 border-t border-border flex items-center justify-between">
                            <p className="text-sm text-muted-foreground">
                                {t('tickets.showingTickets')
                                    .replace('{from}', String(pagination.from))
                                    .replace('{to}', String(pagination.to))
                                    .replace('{total}', String(pagination.total))
                                }
                            </p>
                            <div className="flex gap-2">
                                <Button
                                    variant="outline"
                                    size="sm"
                                    disabled={!pagination.hasPrev}
                                    onClick={() => setPagination(prev => ({ ...prev, page: prev.page - 1 }))}
                                >
                                    <ChevronLeft className="h-4 w-4 mr-1" />
                                    {t('tickets.previous')}
                                </Button>
                                <Button
                                    variant="outline"
                                    size="sm"
                                    disabled={!pagination.hasNext}
                                    onClick={() => setPagination(prev => ({ ...prev, page: prev.page + 1 }))}
                                >
                                    {t('tickets.next')}
                                    <ChevronRight className="h-4 w-4 ml-1" />
                                </Button>
                            </div>
                        </div>
                    )}
                </div>
            )}

            {/* Headless UI Modal for Delete */}
            <HeadlessModal
                isOpen={showDeleteDialog}
                onClose={() => setShowDeleteDialog(false)}
                title={t('tickets.deleteTicketTitle')}
                description={t('tickets.deleteTicketWarning')}
            >
                <div>
                     <p className="text-sm text-muted-foreground mb-6">
                        {t('tickets.deleteTicketConfirm')}
                     </p>
                     <div className="flex justify-end gap-2">
                        <Button variant="outline" onClick={() => setShowDeleteDialog(false)} disabled={deleting}>
                            {t('common.cancel')}
                        </Button>
                        <Button variant="destructive" onClick={confirmDeleteTicket} loading={deleting}>
                            {t('tickets.deleteTicket')}
                        </Button>
                     </div>
                </div>
            </HeadlessModal>
        </div>
    )
}

// frontend/src/pages/dashboard/tickets/Tickets.vue
<template>
    <DashboardLayout :breadcrumbs="[{ text: t('tickets.title'), isCurrent: true, href: '/dashboard/tickets' }]">
        <div class="min-h-screen bg-background">
            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">{{ t('tickets.loadingTickets') }}</span>
                </div>
            </div>

            <!-- Tickets List -->
            <div v-else class="p-6">
                <div class="mb-6 flex items-center justify-between">
                    <div>
                        <h1 class="text-3xl font-bold mb-2">{{ t('tickets.title') }}</h1>
                        <p class="text-muted-foreground">{{ t('tickets.viewAndManage') }}</p>
                    </div>
                    <Button @click="router.push('/dashboard/tickets/create')">
                        <Plus class="h-4 w-4 mr-2" />
                        {{ t('tickets.createTicket') }}
                    </Button>
                </div>

                <!-- Filters -->
                <div class="mb-4 flex gap-2">
                    <Select v-model="filterStatus" @update:model-value="applyFilters">
                        <SelectTrigger class="w-[180px]">
                            <SelectValue :placeholder="t('tickets.filterByStatus')" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">{{ t('tickets.allStatuses') }}</SelectItem>
                            <SelectItem v-for="status in statuses" :key="status.id" :value="String(status.id)">
                                {{ status.name }}
                            </SelectItem>
                        </SelectContent>
                    </Select>
                    <Select v-model="filterCategory" @update:model-value="applyFilters">
                        <SelectTrigger class="w-[180px]">
                            <SelectValue :placeholder="t('tickets.filterByCategory')" />
                        </SelectTrigger>
                        <SelectContent>
                            <SelectItem value="all">{{ t('tickets.allCategories') }}</SelectItem>
                            <SelectItem v-for="category in categories" :key="category.id" :value="String(category.id)">
                                {{ category.name }}
                            </SelectItem>
                        </SelectContent>
                    </Select>
                    <div class="flex gap-2 max-w-sm">
                        <Input
                            v-model="searchQuery"
                            :placeholder="t('tickets.searchTickets')"
                            class="flex-1"
                            @keyup.enter="handleSearch"
                        />
                        <Button type="button" variant="outline" @click="handleSearch">
                            <Search class="h-4 w-4" />
                        </Button>
                    </div>
                </div>

                <!-- Tickets Table -->
                <div v-if="tickets.length === 0" class="text-center py-16 border rounded-lg">
                    <div class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-muted mb-4">
                        <Ticket class="h-8 w-8 text-muted-foreground" />
                    </div>
                    <p class="text-muted-foreground mb-4">{{ t('tickets.noTicketsFound') }}</p>
                    <Button @click="router.push('/dashboard/tickets/create')">
                        <Plus class="h-4 w-4 mr-2" />
                        {{ t('tickets.createFirstTicket') }}
                    </Button>
                </div>

                <div v-else class="space-y-0 border rounded-lg">
                    <div
                        v-for="ticket in tickets"
                        :key="ticket.uuid"
                        class="flex items-center gap-4 p-4 border-b last:border-b-0 hover:bg-muted/50 transition-colors"
                    >
                        <div class="flex-1 min-w-0 cursor-pointer" @click="viewTicket(ticket.uuid)">
                            <div class="flex items-center gap-2 mb-2">
                                <h3 class="text-lg font-semibold">{{ ticket.title }}</h3>
                                <Badge
                                    v-if="ticket.status"
                                    :style="
                                        ticket.status.color
                                            ? { backgroundColor: ticket.status.color, color: '#fff' }
                                            : {}
                                    "
                                    variant="secondary"
                                    class="text-xs"
                                >
                                    {{ ticket.status.name }}
                                </Badge>
                                <Badge
                                    v-if="ticket.priority"
                                    :style="
                                        ticket.priority.color
                                            ? { backgroundColor: ticket.priority.color, color: '#fff' }
                                            : {}
                                    "
                                    variant="secondary"
                                    class="text-xs"
                                >
                                    {{ ticket.priority.name }}
                                </Badge>
                            </div>
                            <div class="flex items-center gap-4 text-sm text-muted-foreground">
                                <span v-if="ticket.category">
                                    <span class="font-medium">{{ t('tickets.category') }}:</span>
                                    {{ ticket.category.name }}
                                </span>
                                <span v-if="ticket.server">
                                    <span class="font-medium">{{ t('tickets.server') }}:</span> {{ ticket.server.name }}
                                </span>
                                <span>
                                    <span class="font-medium">{{ t('tickets.created') }}:</span>
                                    {{ formatDate(ticket.created_at) }}
                                </span>
                            </div>
                        </div>
                        <div class="flex items-center gap-2 shrink-0">
                            <Button
                                type="button"
                                variant="ghost"
                                size="icon"
                                class="h-8 w-8 text-red-600 dark:text-red-500 hover:text-red-700 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-950/20"
                                :title="t('tickets.deleteTicket')"
                                @click.stop.prevent="openDeleteDialog(ticket)"
                            >
                                <Trash2 class="h-4 w-4" />
                            </Button>
                            <ChevronRight
                                class="h-5 w-5 text-muted-foreground shrink-0 cursor-pointer"
                                @click="viewTicket(ticket.uuid)"
                            />
                        </div>
                    </div>
                </div>

                <!-- Pagination -->
                <div v-if="pagination.total > 0" class="mt-4 flex items-center justify-between">
                    <div class="text-sm text-muted-foreground">
                        {{
                            t('tickets.showingTickets', {
                                from: pagination.from,
                                to: pagination.to,
                                total: pagination.total,
                            })
                        }}
                    </div>
                    <div class="flex gap-2">
                        <Button
                            variant="outline"
                            size="sm"
                            :disabled="!pagination.hasPrev"
                            @click="changePage(pagination.page - 1)"
                        >
                            {{ t('tickets.previous') }}
                        </Button>
                        <Button
                            variant="outline"
                            size="sm"
                            :disabled="!pagination.hasNext"
                            @click="changePage(pagination.page + 1)"
                        >
                            {{ t('tickets.next') }}
                        </Button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Delete Ticket Confirmation Dialog -->
        <AlertDialog :open="showDeleteDialog" @update:open="(val: boolean) => !val && closeDeleteDialog()">
            <AlertDialogContent>
                <AlertDialogHeader>
                    <AlertDialogTitle class="flex items-center gap-2 text-destructive">
                        <Trash2 class="h-5 w-5" />
                        {{ t('tickets.deleteTicketTitle') }}
                    </AlertDialogTitle>
                    <AlertDialogDescription class="pt-2">
                        <p class="text-base font-medium text-foreground mb-2">
                            {{ t('tickets.deleteTicketConfirm') }}
                        </p>
                        <p class="text-sm text-muted-foreground">
                            {{ t('tickets.deleteTicketWarning') }}
                        </p>
                    </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                    <AlertDialogCancel @click="closeDeleteDialog">{{ t('common.cancel') }}</AlertDialogCancel>
                    <Button
                        class="bg-red-600 text-white hover:bg-red-700 focus:ring-red-500"
                        :disabled="deleting"
                        @click="confirmDeleteTicket"
                    >
                        <Trash2 class="h-4 w-4 mr-2" />
                        {{ deleting ? t('common.loading') : t('tickets.deleteTicket') }}
                    </Button>
                </AlertDialogFooter>
            </AlertDialogContent>
        </AlertDialog>
    </DashboardLayout>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, watch, onUnmounted } from 'vue';
import { useRouter } from 'vue-router';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Ticket, Plus, ChevronRight, Trash2, Search } from 'lucide-vue-next';
import axios, { type AxiosError } from 'axios';
import { useToast } from 'vue-toastification';
import { useI18n } from 'vue-i18n';
import {
    AlertDialog,
    AlertDialogCancel,
    AlertDialogContent,
    AlertDialogDescription,
    AlertDialogFooter,
    AlertDialogHeader,
    AlertDialogTitle,
} from '@/components/ui/alert-dialog';

const router = useRouter();
const toast = useToast();
const { t } = useI18n();

type ApiTicket = {
    id: number;
    uuid: string;
    title: string;
    description: string;
    created_at: string;
    status?: {
        id: number;
        name: string;
        color?: string;
    };
    priority?: {
        id: number;
        name: string;
        color?: string;
    };
    category?: {
        id: number;
        name: string;
    };
    server?: {
        id: number;
        name: string;
    };
};

type Category = {
    id: number;
    name: string;
};

type Status = {
    id: number;
    name: string;
};

const loading = ref(true);
const tickets = ref<ApiTicket[]>([]);
const categories = ref<Category[]>([]);
const statuses = ref<Status[]>([]);
const searchQuery = ref('');
const filterStatus = ref('all');
const filterCategory = ref('all');
const pagination = ref({
    page: 1,
    pageSize: 10,
    total: 0,
    hasNext: false,
    hasPrev: false,
    from: 0,
    to: 0,
});

// Delete confirmation dialog state
const showDeleteDialog = ref(false);
const ticketToDelete = ref<ApiTicket | null>(null);
const deleting = ref(false);

// Search debounce
let searchTimeout: ReturnType<typeof setTimeout> | null = null;
watch(searchQuery, () => {
    if (searchTimeout) {
        clearTimeout(searchTimeout);
    }
    searchTimeout = setTimeout(() => {
        handleSearch();
    }, 2000); // 2 second debounce
});

async function fetchTickets() {
    loading.value = true;
    try {
        const params: Record<string, string | number | undefined> = {
            page: pagination.value.page,
            limit: pagination.value.pageSize,
            search: searchQuery.value || undefined,
        };

        if (filterStatus.value && filterStatus.value !== 'all') {
            params.status_id = filterStatus.value;
        }
        if (filterCategory.value && filterCategory.value !== 'all') {
            params.category_id = filterCategory.value;
        }

        const { data } = await axios.get('/api/user/tickets', { params });
        tickets.value = data.data.tickets || [];

        const apiPagination = data.data.pagination;
        pagination.value = {
            page: apiPagination.current_page,
            pageSize: apiPagination.per_page,
            total: apiPagination.total_records,
            hasNext: apiPagination.has_next,
            hasPrev: apiPagination.has_prev,
            from: apiPagination.from,
            to: apiPagination.to,
        };
    } catch (error: unknown) {
        const errorMessage =
            ((error as AxiosError)?.response?.data as { message?: string })?.message || t('tickets.failedToFetch');
        toast.error(errorMessage);
        tickets.value = [];
    } finally {
        loading.value = false;
    }
}

async function fetchCategories() {
    try {
        const { data } = await axios.get('/api/user/tickets/categories');
        categories.value = data.data.categories || [];
    } catch (error: unknown) {
        console.error('Failed to fetch categories:', error);
    }
}

async function fetchStatuses() {
    try {
        const { data } = await axios.get('/api/user/tickets/statuses');
        statuses.value = data.data.statuses || [];
    } catch (error: unknown) {
        console.error('Failed to fetch statuses:', error);
    }
}

function viewTicket(uuid: string) {
    router.push(`/dashboard/tickets/${uuid}`);
}

function handleSearch() {
    pagination.value.page = 1;
    fetchTickets();
}

function applyFilters() {
    pagination.value.page = 1;
    fetchTickets();
}

function changePage(page: number) {
    pagination.value.page = page;
    fetchTickets();
}

function formatDate(dateString: string): string {
    if (!dateString) return '-';
    const date = new Date(dateString);
    return date.toLocaleString();
}

function openDeleteDialog(ticket: ApiTicket) {
    if (!ticket || !ticket.uuid) {
        return;
    }
    ticketToDelete.value = ticket;
    showDeleteDialog.value = true;
}

function closeDeleteDialog() {
    showDeleteDialog.value = false;
    ticketToDelete.value = null;
}

async function confirmDeleteTicket() {
    if (!ticketToDelete.value) {
        console.error('No ticket to delete');
        return;
    }

    const ticketUuid = ticketToDelete.value.uuid;
    console.log('Attempting to delete ticket:', ticketUuid);

    deleting.value = true;
    try {
        console.log('Sending DELETE request to:', `/api/user/tickets/${ticketUuid}`);
        const response = await axios.delete(`/api/user/tickets/${ticketUuid}`);
        console.log('Delete response:', response);

        const { data } = response;

        if (data && data.success) {
            console.log('Ticket deleted successfully');
            toast.success(t('tickets.ticketDeleted'));
            closeDeleteDialog();
            // Refresh tickets list
            await fetchTickets();
        } else {
            console.error('Delete failed - response:', data);
            throw new Error(data?.message || 'Failed to delete ticket');
        }
    } catch (err: unknown) {
        console.error('Error deleting ticket:', err);
        const errorMessage =
            ((err as AxiosError)?.response?.data as { message?: string })?.message ||
            (err as Error)?.message ||
            t('tickets.failedToDeleteTicket');
        toast.error(errorMessage);
        closeDeleteDialog();
    } finally {
        deleting.value = false;
    }
}

onMounted(async () => {
    await fetchCategories();
    await fetchStatuses();
    await fetchTickets();
});

onUnmounted(() => {
    if (searchTimeout) {
        clearTimeout(searchTimeout);
    }
});
</script>
