// frontend/src/pages/admin/Images.vue
<template>
    <DashboardLayout :breadcrumbs="[{ text: 'Images', isCurrent: true, href: '/admin/images' }]">
        <div class="min-h-screen bg-background">
            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading images...</span>
                </div>
            </div>

            <!-- Error State -->
            <div
                v-else-if="message?.type === 'error'"
                class="flex flex-col items-center justify-center py-12 text-center"
            >
                <div class="text-red-500 mb-4">
                    <svg class="h-12 w-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"
                        />
                    </svg>
                </div>
                <h3 class="text-lg font-medium text-muted-foreground mb-2">Failed to load images</h3>
                <p class="text-sm text-muted-foreground max-w-sm">
                    {{ message.text }}
                </p>
                <Button class="mt-4" @click="fetchImages">Try Again</Button>
            </div>

            <!-- Images Table -->
            <div v-else class="p-6">
                <TableComponent
                    title="Images"
                    description="Manage uploaded images for your system."
                    :columns="tableColumns"
                    :data="images"
                    :search-placeholder="'Search by name or URL...'"
                    :server-side-pagination="true"
                    :total-records="pagination.total"
                    :total-pages="Math.ceil(pagination.total / pagination.pageSize)"
                    :current-page="pagination.page"
                    :has-next="pagination.hasNext"
                    :has-prev="pagination.hasPrev"
                    :from="pagination.from"
                    :to="pagination.to"
                    local-storage-key="featherpanel-images-table-columns"
                    @search="handleSearch"
                    @page-change="changePage"
                >
                    <template #header-actions>
                        <div class="flex gap-2">
                            <Button variant="outline" size="sm" @click="openCreateDrawer">
                                <Plus class="h-4 w-4 mr-2" />
                                Upload Image
                            </Button>
                        </div>
                    </template>

                    <!-- Custom cell templates -->
                    <template #cell-name="{ item }">
                        <div class="flex items-center gap-2">
                            <ImageIcon class="h-4 w-4 text-muted-foreground" />
                            <span class="font-medium">{{ (item as unknown as Image).name }}</span>
                        </div>
                    </template>

                    <template #cell-url="{ item }">
                        <div class="max-w-xs">
                            <a
                                :href="(item as unknown as Image).url"
                                target="_blank"
                                class="text-sm text-blue-600 hover:text-blue-800 truncate block"
                            >
                                {{ (item as unknown as Image).url }}
                            </a>
                        </div>
                    </template>

                    <template #cell-preview="{ item }">
                        <div class="w-16 h-16 rounded-lg overflow-hidden border">
                            <img
                                :src="(item as unknown as Image).url"
                                :alt="(item as unknown as Image).name"
                                class="w-full h-full object-cover"
                                @error="handleImageError"
                            />
                        </div>
                    </template>

                    <template #cell-created_at="{ item }">
                        <span class="text-sm text-muted-foreground">
                            {{ formatDate((item as unknown as Image).created_at) }}
                        </span>
                    </template>

                    <template #cell-updated_at="{ item }">
                        <span class="text-sm text-muted-foreground">
                            {{ formatDate((item as unknown as Image).updated_at) }}
                        </span>
                    </template>

                    <template #cell-actions="{ item }">
                        <div class="flex gap-2">
                            <Button size="sm" variant="outline" @click="onView(item as unknown as Image)">
                                <Eye :size="16" />
                            </Button>
                            <Button size="sm" variant="secondary" @click="onEdit(item as unknown as Image)">
                                <Pencil :size="16" />
                            </Button>
                            <Button size="sm" variant="outline" @click="onCopyUrl(item as unknown as Image)">
                                <Copy :size="16" />
                            </Button>
                            <template v-if="confirmDeleteRow === (item as unknown as Image).id">
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    :loading="deleting"
                                    @click="confirmDelete(item as unknown as Image)"
                                >
                                    Confirm Delete
                                </Button>
                                <Button size="sm" variant="outline" :disabled="deleting" @click="onCancelDelete">
                                    Cancel
                                </Button>
                            </template>
                            <template v-else>
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    :disabled="deleting"
                                    @click="onDelete(item as unknown as Image)"
                                >
                                    <Trash2 :size="16" />
                                </Button>
                            </template>
                        </div>
                    </template>
                </TableComponent>
                <!-- Images help cards under the table -->
                <div class="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <Upload class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Upload & Reuse</div>
                                    <p>
                                        Upload images to use across the dashboard – e.g., for spells/eggs, banners,
                                        logos, or other UI assets you want to reference.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <ImageIcon class="h-5 w-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Library & Audit</div>
                                    <p>
                                        This page is a central place to see what was uploaded to your host by users –
                                        like banners and other media – and manage them when needed.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>
            </div>
        </div>

        <!-- View Drawer -->
        <Drawer
            :open="viewDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeViewDrawer();
                }
            "
        >
            <DrawerContent v-if="selectedImage">
                <DrawerHeader>
                    <DrawerTitle>Image Details</DrawerTitle>
                    <DrawerDescription>Viewing details for image: {{ selectedImage.name }}</DrawerDescription>
                </DrawerHeader>

                <div class="px-6 pb-6 space-y-6">
                    <div class="flex justify-center">
                        <div class="w-64 h-64 rounded-lg overflow-hidden border">
                            <img
                                :src="selectedImage.url"
                                :alt="selectedImage.name"
                                class="w-full h-full object-cover"
                                @error="handleImageError"
                            />
                        </div>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label class="text-sm font-medium">Name</Label>
                            <p class="text-sm text-muted-foreground mt-1">{{ selectedImage.name }}</p>
                        </div>
                        <div>
                            <Label class="text-sm font-medium">URL</Label>
                            <a
                                :href="selectedImage.url"
                                target="_blank"
                                class="text-sm text-blue-600 hover:text-blue-800 block mt-1 break-all"
                            >
                                {{ selectedImage.url }}
                            </a>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label class="text-sm font-medium">Created At</Label>
                            <p class="text-sm text-muted-foreground mt-1">
                                {{ formatDate(selectedImage.created_at) }}
                            </p>
                        </div>
                        <div>
                            <Label class="text-sm font-medium">Updated At</Label>
                            <p class="text-sm text-muted-foreground mt-1">
                                {{ formatDate(selectedImage.updated_at) }}
                            </p>
                        </div>
                    </div>
                </div>

                <DrawerFooter>
                    <DrawerClose as-child>
                        <Button variant="outline">Close</Button>
                    </DrawerClose>
                </DrawerFooter>
            </DrawerContent>
        </Drawer>

        <!-- Edit Drawer -->
        <Drawer
            :open="editDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeEditDrawer();
                }
            "
        >
            <DrawerContent v-if="editingImage">
                <DrawerHeader>
                    <DrawerTitle>Edit Image</DrawerTitle>
                    <DrawerDescription>Edit details for image: {{ editingImage.name }}</DrawerDescription>
                </DrawerHeader>

                <form class="px-6 pb-6 space-y-6" @submit.prevent="updateImage">
                    <div class="space-y-2">
                        <Label for="edit-name">Name</Label>
                        <Input id="edit-name" v-model="editingImage.name" placeholder="Image name" required />
                    </div>

                    <div class="space-y-2">
                        <Label for="edit-url">URL</Label>
                        <Input id="edit-url" v-model="editingImage.url" placeholder="Image URL" required />
                    </div>

                    <div class="flex gap-2">
                        <Button type="submit" variant="default" :loading="updating">
                            {{ updating ? 'Updating...' : 'Update Image' }}
                        </Button>
                        <Button type="button" variant="outline" @click="closeEditDrawer">Cancel</Button>
                    </div>
                </form>
            </DrawerContent>
        </Drawer>

        <!-- Create Drawer -->
        <Drawer
            :open="createDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeCreateDrawer();
                }
            "
        >
            <DrawerContent>
                <DrawerHeader>
                    <DrawerTitle>Upload Image</DrawerTitle>
                    <DrawerDescription>Upload a new image to your system.</DrawerDescription>
                </DrawerHeader>

                <form class="px-6 pb-6 space-y-6" @submit.prevent="uploadImage">
                    <div class="space-y-2">
                        <Label for="create-name">Name</Label>
                        <Input id="create-name" v-model="newImage.name" placeholder="Image name" required />
                    </div>

                    <div class="space-y-2">
                        <Label for="create-file">Image File</Label>
                        <Input id="create-file" type="file" accept="image/*" required @change="handleFileSelect" />
                        <p class="text-xs text-muted-foreground">Supported formats: JPG, PNG, GIF, WebP</p>
                    </div>

                    <div v-if="selectedFile" class="space-y-2">
                        <Label>Preview</Label>
                        <div class="w-32 h-32 rounded-lg overflow-hidden border">
                            <img :src="filePreview" :alt="newImage.name" class="w-full h-full object-cover" />
                        </div>
                    </div>

                    <div class="flex gap-2">
                        <Button type="submit" variant="default" :loading="uploading">
                            {{ uploading ? 'Uploading...' : 'Upload Image' }}
                        </Button>
                        <Button type="button" variant="outline" @click="closeCreateDrawer">Cancel</Button>
                    </div>
                </form>
            </DrawerContent>
        </Drawer>
    </DashboardLayout>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, watch } from 'vue';
import { useToast } from 'vue-toastification';
import axios from 'axios';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import TableComponent from '@/kit/TableComponent.vue';
import type { TableColumn } from '@/kit/types';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerFooter,
    DrawerClose,
} from '@/components/ui/drawer';
import { Plus, Eye, Pencil, Trash2, Copy, ImageIcon, Upload } from 'lucide-vue-next';
import { Card, CardContent } from '@/components/ui/card';

// Types
interface Image {
    id: number;
    name: string;
    url: string;
    created_at: string;
    updated_at: string;
}

interface Message {
    type: 'success' | 'error' | 'info' | 'warning';
    text: string;
}

// Reactive state
const loading = ref(true);
const images = ref<Image[]>([]);
const pagination = ref({
    page: 1,
    pageSize: 10,
    total: 0,
    hasNext: false,
    hasPrev: false,
    from: 0,
    to: 0,
});
const message = ref<Message | null>(null);
const searchQuery = ref('');

// Drawer states
const viewDrawerOpen = ref(false);
const editDrawerOpen = ref(false);
const createDrawerOpen = ref(false);

// Selected items
const selectedImage = ref<Image | null>(null);
const editingImage = ref<Image | null>(null);

// Form states
const uploading = ref(false);
const updating = ref(false);
const deleting = ref(false);
const confirmDeleteRow = ref<number | null>(null);

// New image form
const newImage = ref({
    name: '',
});
const selectedFile = ref<File | null>(null);
const filePreview = ref<string>('');

// Table columns configuration
const tableColumns: TableColumn[] = [
    { key: 'name', label: 'Name', searchable: true },
    { key: 'url', label: 'URL', searchable: true },
    { key: 'preview', label: 'Preview', searchable: false },
    { key: 'created_at', label: 'Created' },
    { key: 'updated_at', label: 'Updated' },
    { key: 'actions', label: 'Actions', headerClass: 'w-[120px] font-semibold' },
];

const toast = useToast();

// Methods
async function fetchImages() {
    loading.value = true;
    try {
        const { data } = await axios.get('/api/admin/images', {
            params: {
                page: pagination.value.page,
                limit: pagination.value.pageSize,
                search: searchQuery.value || undefined,
            },
        });
        images.value = data.data.images || [];

        // Map the API response pagination to our expected format
        const apiPagination = data.data.pagination;
        pagination.value = {
            page: apiPagination.current_page,
            pageSize: apiPagination.per_page,
            total: apiPagination.total_records,
            hasNext: apiPagination.has_next,
            hasPrev: apiPagination.has_prev,
            from: apiPagination.from,
            to: apiPagination.to,
        };
    } catch (error) {
        console.error('Error fetching images:', error);
        message.value = {
            type: 'error',
            text: error instanceof Error ? error.message : 'Failed to fetch images',
        };
    } finally {
        loading.value = false;
    }
}

const handleSearch = (query: string) => {
    searchQuery.value = query;
    pagination.value.page = 1;
    fetchImages();
};

const changePage = (page: number) => {
    pagination.value.page = page;
    fetchImages();
};

// Drawer methods
const openViewDrawer = (image: Image) => {
    selectedImage.value = image;
    viewDrawerOpen.value = true;
};

const closeViewDrawer = () => {
    viewDrawerOpen.value = false;
    selectedImage.value = null;
};

const openEditDrawer = (image: Image) => {
    editingImage.value = { ...image };
    editDrawerOpen.value = true;
};

const closeEditDrawer = () => {
    editDrawerOpen.value = false;
    editingImage.value = null;
};

const openCreateDrawer = () => {
    newImage.value = { name: '' };
    selectedFile.value = null;
    filePreview.value = '';
    createDrawerOpen.value = true;
};

const closeCreateDrawer = () => {
    createDrawerOpen.value = false;
    newImage.value = { name: '' };
    selectedFile.value = null;
    filePreview.value = '';
};

// File handling
const handleFileSelect = (event: Event) => {
    const target = event.target as HTMLInputElement;
    if (target.files && target.files[0]) {
        selectedFile.value = target.files[0];

        // Create preview
        const reader = new FileReader();
        reader.onload = (e) => {
            filePreview.value = e.target?.result as string;
        };
        reader.readAsDataURL(selectedFile.value);
    }
};

const handleImageError = (event: Event) => {
    const img = event.target as HTMLImageElement;
    img.src =
        'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNjQiIGhlaWdodD0iNjQiIHZpZXdCb3g9IjAgMCA2NCA2NCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0IiBmaWxsPSIjRjNGNEY2Ii8+CjxwYXRoIGQ9Ik0yNCAyNEg0MFY0MEgyNFYyNFoiIGZpbGw9IiNEMUQ1REIiLz4KPC9zdmc+';
};

// CRUD operations
async function uploadImage() {
    if (!newImage.value.name || !selectedFile.value) {
        toast.error('Please fill in all required fields');
        return;
    }

    try {
        uploading.value = true;

        const formData = new FormData();
        formData.append('name', newImage.value.name);
        formData.append('image', selectedFile.value);

        const { data } = await axios.post('/api/admin/images/upload', formData, {
            headers: {
                'Content-Type': 'multipart/form-data',
            },
        });

        if (data && data.success) {
            toast.success('Image uploaded successfully');
            closeCreateDrawer();
            await fetchImages();
        } else {
            toast.error(data?.message || 'Failed to upload image');
        }
    } catch (error) {
        console.error('Error uploading image:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to upload image');
    } finally {
        uploading.value = false;
    }
}

async function updateImage() {
    if (!editingImage.value) return;

    try {
        updating.value = true;
        const { data } = await axios.patch(`/api/admin/images/${editingImage.value.id}`, editingImage.value);

        if (data && data.success) {
            toast.success('Image updated successfully');
            closeEditDrawer();
            await fetchImages();
        } else {
            toast.error(data?.message || 'Failed to update image');
        }
    } catch (error) {
        console.error('Error updating image:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to update image');
    } finally {
        updating.value = false;
    }
}

const onDelete = (image: Image) => {
    confirmDeleteRow.value = image.id;
};

const onCancelDelete = () => {
    confirmDeleteRow.value = null;
};

async function confirmDelete(image: Image) {
    deleting.value = true;
    let success = false;
    try {
        const response = await axios.delete(`/api/admin/images/${image.id}`);
        if (response.data && response.data.success) {
            toast.success('Image deleted successfully');
            await fetchImages();
            success = true;
        } else {
            toast.error(response.data?.message || 'Failed to delete image');
        }
    } catch (error) {
        console.error('Error deleting image:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to delete image');
    } finally {
        deleting.value = false;
        if (success) confirmDeleteRow.value = null;
    }
}

// Action handlers
const onView = (image: Image) => {
    openViewDrawer(image);
};

const onEdit = (image: Image) => {
    openEditDrawer(image);
};

const onCopyUrl = async (image: Image) => {
    try {
        await navigator.clipboard.writeText(image.url);
        toast.success('URL copied to clipboard');
    } catch {
        toast.error('Failed to copy URL');
    }
};

// Utility functions
const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
};

onMounted(fetchImages);
watch([() => pagination.value.page, () => pagination.value.pageSize, searchQuery], fetchImages);
</script>

// featherpanel-frontendv2/src/app/admin/images/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import {
    Search,
    Image as ImageIcon,
    Copy,
    Eye,
    Pencil,
    Trash2,
    Upload,
    ChevronLeft,
    ChevronRight,
    Calendar,
    Link as LinkIcon,
} from 'lucide-react';
import axios, { isAxiosError } from 'axios';
import { toast } from 'sonner';
import { copyToClipboard } from '@/lib/utils';
import { PageHeader } from '@/components/featherui/PageHeader';
import { Input } from '@/components/featherui/Input';
import { Button } from '@/components/featherui/Button';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { PageCard } from '@/components/featherui/PageCard';
import { EmptyState } from '@/components/featherui/EmptyState';
import { Sheet, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Label } from '@/components/ui/label';

interface Image {
    id: number;
    name: string;
    url: string;
    created_at: string;
    updated_at: string;
}

interface Pagination {
    page: number;
    pageSize: number;
    total: number;
    hasNext: boolean;
    hasPrev: boolean;
    from: number;
    to: number;
}

export default function ImagesPage() {
    const { t } = useTranslation();
    const [loading, setLoading] = useState(true);
    const [images, setImages] = useState<Image[]>([]);
    const [pagination, setPagination] = useState<Pagination>({
        page: 1,
        pageSize: 10,
        total: 0,
        hasNext: false,
        hasPrev: false,
        from: 0,
        to: 0,
    });
    const [searchQuery, setSearchQuery] = useState('');
    const [debouncedSearchQuery, setDebouncedSearchQuery] = useState('');

    // Sheet states
    const [createOpen, setCreateOpen] = useState(false);
    const [editOpen, setEditOpen] = useState(false);
    const [viewOpen, setViewOpen] = useState(false);

    // Selected content
    const [selectedImage, setSelectedImage] = useState<Image | null>(null);
    const [formData, setFormData] = useState({ name: '', url: '' });
    const [uploadData, setUploadData] = useState({ name: '' });
    const [selectedFile, setSelectedFile] = useState<File | null>(null);
    const [filePreview, setFilePreview] = useState<string>('');

    // Action states
    const [processing, setProcessing] = useState(false);
    const [refreshKey, setRefreshKey] = useState(0);

    // Debounce search
    useEffect(() => {
        const timer = setTimeout(() => {
            setDebouncedSearchQuery(searchQuery);
            if (searchQuery !== debouncedSearchQuery) {
                setPagination((p) => ({ ...p, page: 1 }));
            }
        }, 500);
        return () => clearTimeout(timer);
    }, [searchQuery, debouncedSearchQuery]);

    const fetchImages = useCallback(async () => {
        setLoading(true);
        try {
            const { data } = await axios.get('/api/admin/images', {
                params: {
                    page: pagination.page,
                    limit: pagination.pageSize,
                    search: debouncedSearchQuery || undefined,
                },
            });
            if (data.success) {
                setImages(data.data.images || []);
                const apiPag = data.data.pagination;
                setPagination({
                    page: apiPag.current_page,
                    pageSize: apiPag.per_page,
                    total: apiPag.total_records,
                    hasNext: apiPag.has_next,
                    hasPrev: apiPag.has_prev,
                    from: apiPag.from,
                    to: apiPag.to,
                });
            } else {
                toast.error(data.message || t('admin.images.messages.fetch_failed'));
            }
        } catch (error) {
            console.error('Error fetching images:', error);
            toast.error(t('admin.images.messages.fetch_failed'));
        } finally {
            setLoading(false);
        }
    }, [pagination.page, pagination.pageSize, debouncedSearchQuery, t]);

    useEffect(() => {
        fetchImages();
    }, [fetchImages, refreshKey]);

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setSelectedFile(file);
            const reader = new FileReader();
            reader.onload = (event) => {
                setFilePreview(event.target?.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const openCreate = () => {
        setUploadData({ name: '' });
        setSelectedFile(null);
        setFilePreview('');
        setCreateOpen(true);
    };

    const handleUpload = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedFile || !uploadData.name) {
            toast.error(t('admin.images.messages.fill_all'));
            return;
        }

        setProcessing(true);
        try {
            const fd = new FormData();
            fd.append('name', uploadData.name);
            fd.append('image', selectedFile);

            const { data } = await axios.post('/api/admin/images/upload', fd, {
                headers: { 'Content-Type': 'multipart/form-data' },
            });

            if (data.success) {
                toast.success(t('admin.images.messages.upload_success'));
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.images.messages.upload_failed'));
            }
        } catch (error: unknown) {
            let message = t('admin.images.messages.upload_failed');
            if (isAxiosError(error) && error.response?.data?.message) {
                message = error.response.data.message;
            }
            toast.error(message);
        } finally {
            setProcessing(false);
        }
    };

    const openEdit = (image: Image) => {
        setSelectedImage(image);
        setFormData({ name: image.name, url: image.url });
        setEditOpen(true);
    };

    const handleUpdate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedImage) return;
        setProcessing(true);
        try {
            const { data } = await axios.patch(`/api/admin/images/${selectedImage.id}`, formData);
            if (data.success) {
                toast.success(t('admin.images.messages.update_success'));
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.images.messages.update_failed'));
            }
        } catch (error: unknown) {
            let message = t('admin.images.messages.update_failed');
            if (isAxiosError(error) && error.response?.data?.message) {
                message = error.response.data.message;
            }
            toast.error(message);
        } finally {
            setProcessing(false);
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm(t('admin.images.messages.delete_confirm'))) return;
        try {
            const { data } = await axios.delete(`/api/admin/images/${id}`);
            if (data.success) {
                toast.success(t('admin.images.messages.delete_success'));
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.images.messages.delete_failed'));
            }
        } catch {
            toast.error(t('admin.images.messages.delete_failed'));
        }
    };

    const openView = (image: Image) => {
        setSelectedImage(image);
        setFormData({ name: image.name, url: image.url });
        setViewOpen(true);
    };


    const formatDate = (dateString: string) => {
        return new Date(dateString).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'short',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    return (
        <div className='space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500'>
            <PageHeader
                title={t('admin.images.title')}
                description={t('admin.images.subtitle')}
                icon={ImageIcon}
                actions={
                    <Button onClick={openCreate}>
                        <Upload className='w-4 h-4 mr-2' />
                        {t('admin.images.create')}
                    </Button>
                }
            />

            <div className='flex flex-col sm:flex-row gap-4 items-center bg-card/40 backdrop-blur-md p-4 rounded-2xl shadow-sm'>
                <div className='relative flex-1 group w-full'>
                    <Search className='absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors' />
                    <Input
                        className='pl-10 h-11 w-full'
                        placeholder={t('admin.images.search_placeholder')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                    />
                </div>
            </div>

            <div className='grid grid-cols-1 md:grid-cols-1 gap-4'>
                {loading ? (
                    Array.from({ length: 3 }).map((_, i) => (
                        <div key={i} className='h-24 rounded-2xl bg-card/40 animate-pulse' />
                    ))
                ) : images.length > 0 ? (
                    images.map((image) => (
                        <ResourceCard
                            key={image.id}
                            icon={ImageIcon}
                            image={image.url}
                            title={image.name}
                            subtitle={
                                <div className='flex items-center gap-1.5'>
                                    <Calendar className='w-3 h-3' />
                                    {formatDate(image.created_at)}
                                </div>
                            }
                            description={
                                <div className='flex items-center gap-1.5 mt-1'>
                                    <LinkIcon className='w-3 h-3 shrink-0' />
                                    <span className='truncate opacity-70'>{image.url}</span>
                                </div>
                            }
                            actions={
                                <div className='flex gap-2'>
                                    <Button
                                        variant='ghost'
                                        size='sm'
                                        className='h-9 w-9 p-0'
                                        onClick={() => openView(image)}
                                    >
                                        <Eye className='w-4 h-4' />
                                    </Button>
                                    <Button
                                        variant='ghost'
                                        size='sm'
                                        className='h-9 w-9 p-0'
                                        onClick={() => openEdit(image)}
                                    >
                                        <Pencil className='w-4 h-4' />
                                    </Button>
                                    <Button
                                        variant='ghost'
                                        size='sm'
                                        className='h-9 w-9 p-0'
                                        onClick={() => copyToClipboard(image.url)}
                                    >
                                        <Copy className='w-4 h-4' />
                                    </Button>
                                    <Button
                                        variant='ghost'
                                        size='sm'
                                        className='h-9 w-9 p-0 text-destructive hover:bg-destructive/10 hover:text-destructive'
                                        onClick={() => handleDelete(image.id)}
                                    >
                                        <Trash2 className='w-4 h-4' />
                                    </Button>
                                </div>
                            }
                        />
                    ))
                ) : (
                    <EmptyState
                        icon={ImageIcon}
                        title={t('admin.images.no_results')}
                        description={t('admin.images.search_placeholder')}
                        action={
                            <Button onClick={openCreate}>
                                <Upload className='w-4 h-4 mr-2' />
                                {t('admin.images.create')}
                            </Button>
                        }
                    />
                )}
            </div>

            {pagination.total > pagination.pageSize && (
                <div className='flex items-center justify-center gap-2 mt-8'>
                    <Button
                        variant='outline'
                        size='icon'
                        disabled={!pagination.hasPrev}
                        onClick={() => setPagination((p) => ({ ...p, page: p.page - 1 }))}
                    >
                        <ChevronLeft className='h-4 w-4' />
                    </Button>
                    <span className='text-sm font-medium'>
                        {pagination.page} / {Math.ceil(pagination.total / pagination.pageSize)}
                    </span>
                    <Button
                        variant='outline'
                        size='icon'
                        disabled={!pagination.hasNext}
                        onClick={() => setPagination((p) => ({ ...p, page: p.page + 1 }))}
                    >
                        <ChevronRight className='h-4 w-4' />
                    </Button>
                </div>
            )}

            <div className='grid grid-cols-1 md:grid-cols-2 gap-4'>
                <PageCard icon={Upload} title={t('admin.images.help.upload.title')}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.images.help.upload.description')}
                    </p>
                </PageCard>
                <PageCard icon={ImageIcon} title={t('admin.images.help.audit.title')}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.images.help.audit.description')}
                    </p>
                </PageCard>
            </div>

            {/* Create Sheet */}
            <Sheet open={createOpen} onOpenChange={setCreateOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>{t('admin.images.form.create_title')}</SheetTitle>
                        <SheetDescription>{t('admin.images.form.create_description')}</SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleUpload} className='space-y-6'>
                        <div className='space-y-4'>
                            <div className='space-y-2'>
                                <Label>{t('admin.images.form.name')}</Label>
                                <Input
                                    required
                                    value={uploadData.name}
                                    onChange={(e) => setUploadData({ name: e.target.value })}
                                />
                            </div>
                            <div className='space-y-2'>
                                <Label>{t('admin.images.form.file')}</Label>
                                <Input type='file' accept='image/*' required onChange={handleFileSelect} />
                                <p className='text-xs text-muted-foreground'>{t('admin.images.form.file_help')}</p>
                            </div>
                            {filePreview && (
                                <div className='space-y-2'>
                                    <Label>{t('admin.images.form.preview')}</Label>
                                    <div className='w-full h-48 rounded-xl overflow-hidden border bg-card/50'>
                                        {/* eslint-disable-next-line @next/next/no-img-element */}
                                        <img src={filePreview} alt='Preview' className='w-full h-full object-contain' />
                                    </div>
                                </div>
                            )}
                        </div>
                        <SheetFooter>
                            <Button type='submit' loading={processing} className='w-full sm:w-auto'>
                                {t('admin.images.form.submit_create')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            {/* Edit Sheet */}
            <Sheet open={editOpen} onOpenChange={setEditOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>{t('admin.images.form.edit_title')}</SheetTitle>
                        <SheetDescription>
                            {t('admin.images.form.edit_description', { name: selectedImage?.name || '' })}
                        </SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleUpdate} className='space-y-6'>
                        <div className='space-y-4'>
                            <div className='space-y-2'>
                                <Label>{t('admin.images.form.name')}</Label>
                                <Input
                                    required
                                    value={formData.name}
                                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                />
                            </div>
                            <div className='space-y-2'>
                                <Label>{t('admin.images.form.url')}</Label>
                                <Input
                                    required
                                    value={formData.url}
                                    onChange={(e) => setFormData({ ...formData, url: e.target.value })}
                                />
                            </div>
                        </div>
                        <SheetFooter>
                            <Button type='submit' loading={processing} className='w-full sm:w-auto'>
                                {t('admin.images.form.submit_update')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            {/* View Sheet */}
            <Sheet open={viewOpen} onOpenChange={setViewOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>{t('admin.images.form.view_title')}</SheetTitle>
                        <SheetDescription>
                            {t('admin.images.form.view_description', { name: selectedImage?.name || '' })}
                        </SheetDescription>
                    </SheetHeader>
                    <div className='space-y-8'>
                        <div className='w-full h-80 rounded-2xl overflow-hidden border bg-black/20 flex items-center justify-center p-4'>
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                                src={selectedImage?.url}
                                alt={selectedImage?.name}
                                className='max-w-full max-h-full object-contain shadow-2xl'
                            />
                        </div>

                        <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
                            <div className='space-y-1.5'>
                                <Label className='text-xs opacity-50 uppercase tracking-wider font-semibold'>
                                    {t('admin.images.form.name')}
                                </Label>
                                <p className='font-medium'>{selectedImage?.name}</p>
                            </div>
                            <div className='space-y-1.5'>
                                <Label className='text-xs opacity-50 uppercase tracking-wider font-semibold'>
                                    {t('admin.images.form.createdAt')}
                                </Label>
                                <p className='font-medium'>
                                    {selectedImage ? formatDate(selectedImage.created_at) : ''}
                                </p>
                            </div>
                            <div className='col-span-full space-y-1.5'>
                                <Label className='text-xs opacity-50 uppercase tracking-wider font-semibold'>
                                    {t('admin.images.form.url')}
                                </Label>
                                <div className='flex items-center gap-2'>
                                    <div className='flex-1 p-3 bg-card/40 rounded-xl text-sm truncate font-mono border border-white/5'>
                                        {selectedImage?.url}
                                    </div>
                                    <Button
                                        size='sm'
                                        variant='outline'
                                        className='h-11 w-11 p-0 shrink-0'
                                        onClick={() => selectedImage && copyToClipboard(selectedImage.url)}
                                    >
                                        <Copy className='w-4 h-4' />
                                    </Button>
                                </div>
                            </div>
                        </div>
                        <SheetFooter>
                            <Button variant='outline' onClick={() => setViewOpen(false)} className='w-full'>
                                {t('common.close')}
                            </Button>
                        </SheetFooter>
                    </div>
                </div>
            </Sheet>
        </div>
    );
}
