// frontendv2/src/app/(app)/admin/analytics/system/page.tsx
/*
This file is part of FeatherPanel.

Copyright (C) 2025 MythicalSystems Studios
Copyright (C) 2025 FeatherPanel Contributors
Copyright (C) 2025 Cassian Gherman (aka NaysKutzu)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the LICENSE file or <https://www.gnu.org/licenses/>.
*/

'use client';

import React, { useEffect, useState } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import api from '@/lib/api';
import { SimplePieChart } from '@/components/admin/analytics/SharedCharts';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { PageHeader } from '@/components/featherui/PageHeader';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Mail, CheckCircle, XCircle, Activity } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';

interface MailQueueStats {
    total_queued: number;
    total_sent: number;
    total_failed: number;
    success_rate: number;
    recent_queued: {
        id: number;
        subject: string;
        recipient: string;
        status: string;
        attempts: number;
        created_at: string;
    }[];
}

export default function SystemAnalyticsPage() {
    const { t } = useTranslation();
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const [stats, setStats] = useState<MailQueueStats | null>(null);

    const fetchData = React.useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const res = await api.get('/admin/analytics/mail-queue/stats'); // Removed double /api and fixed path
            setStats(res.data.data);
        } catch (err) {
            console.error('Failed to fetch system analytics:', err);
            setError(t('admin.analytics.system.error'));
        } finally {
            setLoading(false);
        }
    }, [t]);

    useEffect(() => {
        fetchData();
    }, [fetchData]);

    if (loading) {
        return (
            <div className='flex items-center justify-center min-h-[400px]'>
                <div className='animate-spin rounded-full h-8 w-8 border-b-2 border-primary'></div>
            </div>
        );
    }

    if (error) {
        return (
            <div className='flex flex-col items-center justify-center min-h-[400px] text-center'>
                <p className='text-red-500 mb-4'>{error}</p>
                <button
                    onClick={fetchData}
                    className='px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity'
                >
                    {t('admin.analytics.activity.retry')}
                </button>
            </div>
        );
    }

    return (
        <div className='space-y-6'>
            <PageHeader
                title={t('admin.analytics.system.title')}
                description={t('admin.analytics.system.subtitle')}
                icon={Activity}
            />

            {stats && (
                <>
                    {/* Overview Stats */}
                    <div className='grid gap-6 md:grid-cols-2 lg:grid-cols-4'>
                        <ResourceCard
                            title={stats.total_queued.toString()}
                            subtitle={t('admin.analytics.system.queued')}
                            description={t('admin.analytics.system.pending_emails')}
                            icon={Mail}
                            className='shadow-none! bg-card/50 backdrop-blur-sm'
                        />
                        <ResourceCard
                            title={stats.total_sent.toString()}
                            subtitle={t('admin.analytics.system.sent')}
                            description={t('admin.analytics.system.delivered')}
                            icon={CheckCircle}
                            className='shadow-none! bg-card/50 backdrop-blur-sm'
                        />
                        <ResourceCard
                            title={stats.total_failed.toString()}
                            subtitle={t('admin.analytics.system.failed')}
                            description={t('admin.analytics.system.errors')}
                            icon={XCircle}
                            className='shadow-none! bg-card/50 backdrop-blur-sm'
                        />
                        <ResourceCard
                            title={`${stats.success_rate}%`}
                            subtitle={t('admin.analytics.system.success_rate')}
                            description={t('admin.analytics.system.delivery_rate')}
                            icon={Activity}
                            className='shadow-none! bg-card/50 backdrop-blur-sm'
                        />
                    </div>

                    <div className='grid gap-4 grid-cols-1 md:grid-cols-3'>
                        <div className='md:col-span-1'>
                            <SimplePieChart
                                title={t('admin.analytics.system.queue_status')}
                                description={t('admin.analytics.system.queue_status_desc')}
                                data={[
                                    { name: t('admin.analytics.system.queued'), value: stats.total_queued },
                                    { name: t('admin.analytics.system.sent'), value: stats.total_sent },
                                    { name: t('admin.analytics.system.failed'), value: stats.total_failed },
                                ]}
                            />
                        </div>

                        <Card className='md:col-span-2 border-border/50 shadow-sm bg-card/50 backdrop-blur-sm'>
                            <CardHeader>
                                <CardTitle>{t('admin.analytics.system.recent_activity')}</CardTitle>
                                <CardDescription>{t('admin.analytics.system.recent_activity_desc')}</CardDescription>
                            </CardHeader>
                            <CardContent>
                                {stats.recent_queued.length > 0 ? (
                                    <div className='space-y-6'>
                                        {stats.recent_queued.map((item) => (
                                            <div
                                                key={item.id}
                                                className='flex items-center justify-between pb-4 border-b last:border-0 last:pb-0'
                                            >
                                                <div className='space-y-1'>
                                                    <p className='text-sm font-medium'>{item.subject}</p>
                                                    <p className='text-xs text-muted-foreground'>{item.recipient}</p>
                                                </div>
                                                <div className='text-right'>
                                                    <span
                                                        className={`text-xs px-2 py-1 rounded-full ${
                                                            item.status === 'sent'
                                                                ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-400'
                                                                : item.status === 'failed'
                                                                  ? 'bg-red-100 text-red-800 dark:bg-red-900/30 dark:text-red-400'
                                                                  : 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/30 dark:text-yellow-400'
                                                        }`}
                                                    >
                                                        {t(`admin.analytics.system.status.${item.status}`) ||
                                                            item.status}
                                                    </span>
                                                    <p className='text-xs text-muted-foreground mt-1'>
                                                        {formatDistanceToNow(new Date(item.created_at), {
                                                            addSuffix: true,
                                                        })}
                                                    </p>
                                                </div>
                                            </div>
                                        ))}
                                    </div>
                                ) : (
                                    <div className='flex justify-center py-8 text-muted-foreground'>
                                        {t('admin.analytics.system.no_activity')}
                                    </div>
                                )}
                            </CardContent>
                        </Card>
                    </div>
                </>
            )}
        </div>
    );
}

// frontend/src/pages/admin/kpi/System.vue
<template>
    <DashboardLayout
        :breadcrumbs="[
            { text: 'Analytics', href: '/admin/kpi/analytics' },
            { text: 'System', isCurrent: true },
        ]"
    >
        <div class="min-h-screen bg-background">
            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading system analytics...</span>
                </div>
            </div>

            <!-- Error State -->
            <div v-else-if="error" class="text-center py-12">
                <p class="text-red-500">{{ error }}</p>
                <Button class="mt-4" data-umami-event="Retry system analytics" @click="fetchAnalytics"
                    >Try Again</Button
                >
            </div>

            <!-- Content -->
            <div v-else class="p-6 space-y-6">
                <!-- Header -->
                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                    <div>
                        <h1 class="text-3xl font-bold text-foreground mb-1">System Analytics</h1>
                        <p class="text-muted-foreground">Mail queue monitoring and statistics</p>
                    </div>
                    <div class="flex gap-2">
                        <Button variant="outline" data-umami-event="Refresh system analytics" @click="fetchAnalytics">
                            <RefreshCw :size="16" class="mr-2" />
                            Refresh
                        </Button>
                    </div>
                </div>

                <!-- Overview Stats Cards -->
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                    <Card>
                        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle class="text-sm font-medium">Queued</CardTitle>
                            <Mail class="h-4 w-4 text-orange-500" />
                        </CardHeader>
                        <CardContent>
                            <div class="text-2xl font-bold">{{ mailQueue.total_queued }}</div>
                            <p class="text-xs text-muted-foreground mt-1">Pending emails</p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle class="text-sm font-medium">Sent</CardTitle>
                            <Mail class="h-4 w-4 text-green-500" />
                        </CardHeader>
                        <CardContent>
                            <div class="text-2xl font-bold">{{ mailQueue.total_sent }}</div>
                            <p class="text-xs text-muted-foreground mt-1">Successfully delivered</p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle class="text-sm font-medium">Failed</CardTitle>
                            <Mail class="h-4 w-4 text-red-500" />
                        </CardHeader>
                        <CardContent>
                            <div class="text-2xl font-bold">{{ mailQueue.total_failed }}</div>
                            <p class="text-xs text-muted-foreground mt-1">Delivery errors</p>
                        </CardContent>
                    </Card>

                    <Card>
                        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
                            <CardTitle class="text-sm font-medium">Success Rate</CardTitle>
                            <Mail class="h-4 w-4 text-blue-500" />
                        </CardHeader>
                        <CardContent>
                            <div class="text-2xl font-bold">{{ mailQueue.success_rate }}%</div>
                            <p class="text-xs text-muted-foreground mt-1">Delivery rate</p>
                        </CardContent>
                    </Card>
                </div>

                <!-- Mail Queue Chart -->
                <Card>
                    <CardHeader>
                        <CardTitle>Mail Queue Status</CardTitle>
                        <CardDescription>Email queue distribution</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div class="h-[300px] flex items-center justify-center">
                            <Doughnut
                                v-if="mailQueueChartData"
                                :data="mailQueueChartData"
                                :options="doughnutChartOptions"
                            />
                        </div>
                    </CardContent>
                </Card>

                <!-- Mail Queue Details -->
                <Card>
                    <CardHeader>
                        <CardTitle>Recent Mail Queue Activity</CardTitle>
                        <CardDescription>Latest email processing status</CardDescription>
                    </CardHeader>
                    <CardContent>
                        <div
                            v-if="!mailQueue.recent_queued || mailQueue.recent_queued.length === 0"
                            class="text-center py-8 text-muted-foreground"
                        >
                            No recent mail queue activity
                        </div>
                        <div v-else class="space-y-3">
                            <div
                                v-for="mail in mailQueue.recent_queued.slice(0, 10)"
                                :key="mail.id"
                                class="flex items-center justify-between p-3 rounded-lg border border-border hover:bg-muted/50 transition-colors"
                            >
                                <div class="flex-1">
                                    <p class="font-medium">{{ mail.subject }}</p>
                                    <p class="text-sm text-muted-foreground">To: {{ mail.email }}</p>
                                </div>
                                <Badge v-if="mail.status === 'sent'" variant="default">Sent</Badge>
                                <Badge v-else-if="mail.status === 'failed'" variant="destructive">Failed</Badge>
                                <Badge v-else variant="secondary">Queued</Badge>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </div>
    </DashboardLayout>
</template>

<script setup lang="ts">
/*
MIT License

Copyright (c) 2025 MythicalSystems
Copyright (c) 2025 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

import { ref, onMounted, computed } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Mail, RefreshCw } from 'lucide-vue-next';
import axios from 'axios';
import { Doughnut } from 'vue-chartjs';
import { Chart as ChartJS, ArcElement, Title, Tooltip, Legend } from 'chart.js';

// Register Chart.js components
ChartJS.register(ArcElement, Title, Tooltip, Legend);

interface MailQueueItem {
    id: number;
    email: string;
    subject: string;
    status: string;
    created_at: string;
}

// State
const loading = ref(true);
const error = ref<string | null>(null);
const mailQueue = ref({
    total_queued: 0,
    total_sent: 0,
    total_failed: 0,
    success_rate: 0,
    recent_queued: [] as MailQueueItem[],
});

// Chart Data
const mailQueueChartData = computed(() => {
    const total = mailQueue.value.total_queued + mailQueue.value.total_sent + mailQueue.value.total_failed;
    if (total === 0) return null;

    return {
        labels: ['Queued', 'Sent', 'Failed'],
        datasets: [
            {
                data: [mailQueue.value.total_queued, mailQueue.value.total_sent, mailQueue.value.total_failed],
                backgroundColor: ['rgb(251, 146, 60)', 'rgb(34, 197, 94)', 'rgb(239, 68, 68)'],
            },
        ],
    };
});

// Chart Options
const doughnutChartOptions = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
        legend: {
            position: 'bottom' as const,
        },
    },
};

// Fetch analytics data
const fetchAnalytics = async () => {
    loading.value = true;
    error.value = null;

    try {
        const mailRes = await axios.get('/api/admin/analytics/mail-queue/stats');

        if (mailRes.data?.success) {
            mailQueue.value = mailRes.data.data;
        }
    } catch (err) {
        console.error('Failed to fetch system analytics:', err);
        error.value = 'Failed to load system analytics data';
    } finally {
        loading.value = false;
    }
};

onMounted(() => {
    fetchAnalytics();
});
</script>
