// frontendv2/src/app/(app)/admin/nodes/[id]/components/DockerTab.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
This file is part of FeatherPanel.

Copyright (C) 2025 MythicalSystems Studios
Copyright (C) 2025 FeatherPanel Contributors
Copyright (C) 2025 Cassian Gherman (aka NaysKutzu)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the LICENSE file or <https://www.gnu.org/licenses/>.
*/

import React, { useState } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import { PageCard } from '@/components/featherui/PageCard';
import { Button } from '@/components/featherui/Button';
import { LayoutGrid, Trash2, RefreshCw, AlertTriangle, Info } from 'lucide-react';
import { formatBytes } from '@/lib/format';
import axios from 'axios';
import { DockerResponse } from '../types';
import { toast } from 'sonner';

interface DockerTabProps {
    nodeId: number;
    loading: boolean;
    data: DockerResponse | null;
    error: string | null;
    onRefresh: () => void;
}

export function DockerTab({ nodeId, loading, data, error, onRefresh }: DockerTabProps) {
    const { t } = useTranslation();
    const [cleaning, setCleaning] = useState(false);

    const handlePrune = async () => {
        if (!confirm(t('admin.node.view.docker.prune_confirm'))) return;

        setCleaning(true);
        try {
            await axios.delete(`/api/wings/admin/node/${nodeId}/docker/prune`);
            toast.success(t('admin.node.view.docker.prune_success'));
            onRefresh();
        } catch (e: unknown) {
            let msg = t('admin.node.view.docker.prune_failed');
            if (axios.isAxiosError(e)) {
                msg = e.response?.data?.message || e.message;
            }
            toast.error(msg);
        } finally {
            setCleaning(false);
        }
    };

    if (loading) {
        return (
            <div className='flex items-center justify-center py-12'>
                <RefreshCw className='h-8 w-8 animate-spin text-primary' />
            </div>
        );
    }

    if (error) {
        return (
            <PageCard title={t('admin.node.view.docker.error_title')} icon={AlertTriangle}>
                <div className='p-6 bg-destructive/10 border border-destructive/20 rounded-2xl text-center space-y-4'>
                    <p className='text-destructive'>{error}</p>
                    <Button variant='outline' onClick={onRefresh}>
                        {t('common.retry')}
                    </Button>
                </div>
            </PageCard>
        );
    }

    if (!data) return null;

    const { dockerDiskUsage } = data;

    const stats = [
        {
            label: t('admin.node.view.docker.containers_size'),
            value: formatBytes(dockerDiskUsage.containers_size),
            description: t('admin.node.view.docker.containers_size_help'),
        },
        {
            label: t('admin.node.view.docker.images_total'),
            value: dockerDiskUsage.images_total,
            description: t('admin.node.view.docker.images_total_help'),
        },
        {
            label: t('admin.node.view.docker.images_active'),
            value: dockerDiskUsage.images_active,
            description: t('admin.node.view.docker.images_active_help'),
        },
        {
            label: t('admin.node.view.docker.images_size'),
            value: formatBytes(dockerDiskUsage.images_size),
            description: t('admin.node.view.docker.images_size_help'),
        },
        {
            label: t('admin.node.view.docker.cache_size'),
            value: formatBytes(dockerDiskUsage.build_cache_size),
            description: t('admin.node.view.docker.cache_size_help'),
        },
    ];

    return (
        <div className='space-y-6'>
            <PageCard
                title={t('admin.node.view.docker.title')}
                icon={LayoutGrid}
                action={
                    <Button
                        variant='destructive'
                        size='sm'
                        onClick={handlePrune}
                        loading={cleaning}
                        title={t('admin.node.view.docker.prune')}
                    >
                        <Trash2 className='h-4 w-4 mr-2' />
                        {t('admin.node.view.docker.prune')}
                    </Button>
                }
            >
                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6'>
                    {stats.map((stat, index) => (
                        <div key={index} className='p-6 rounded-2xl bg-muted/30 border border-border/50'>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2'>
                                {stat.label}
                            </p>
                            <h3 className='text-2xl font-bold mb-1'>{stat.value}</h3>
                            <p className='text-xs text-muted-foreground italic leading-relaxed'>{stat.description}</p>
                        </div>
                    ))}
                </div>
            </PageCard>

            <PageCard title={t('admin.node.view.docker.info_title')} icon={Info}>
                <p className='text-sm text-muted-foreground leading-relaxed'>
                    {t('admin.node.view.docker.info_description')}
                </p>
            </PageCard>
        </div>
    );
}

// frontend/src/pages/admin/nodes/view/components/DockerTab.vue
<template>
    <div class="space-y-4">
        <div v-if="loading" class="flex items-center justify-center py-8">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>

        <div v-else-if="error" class="space-y-4">
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg flex items-center gap-2">
                        <div class="h-3 w-3 bg-red-500 rounded-full animate-pulse"></div>
                        Docker Data Unavailable
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <Alert variant="destructive">
                        <div class="space-y-3">
                            <div class="font-medium">Failed to fetch Docker information</div>
                            <div class="text-sm">{{ error }}</div>
                        </div>
                    </Alert>
                </CardContent>
            </Card>
        </div>

        <div v-else-if="data" class="space-y-4">
            <!-- Docker Images -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">Docker Images</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
                        <div class="text-center">
                            <div class="text-2xl font-bold">{{ data.dockerDiskUsage.images_total }}</div>
                            <div class="text-sm text-muted-foreground">Total Images</div>
                        </div>
                        <div class="text-center">
                            <div class="text-2xl font-bold text-green-600">
                                {{ data.dockerDiskUsage.images_active }}
                            </div>
                            <div class="text-sm text-muted-foreground">Active Images</div>
                        </div>
                        <div class="text-center">
                            <div class="text-2xl font-bold text-orange-600">
                                {{ data.dockerDiskUsage.images_total - data.dockerDiskUsage.images_active }}
                            </div>
                            <div class="text-sm text-muted-foreground">Inactive Images</div>
                        </div>
                        <div class="text-center">
                            <div class="text-2xl font-bold">
                                {{ formatBytes(data.dockerDiskUsage.images_size, true) }}
                            </div>
                            <div class="text-sm text-muted-foreground">Images Size</div>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Docker Disk Usage -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">Docker Disk Usage</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="space-y-4">
                        <div class="flex justify-between items-center p-3 bg-muted rounded-lg">
                            <span class="text-sm font-medium">Containers</span>
                            <span class="text-sm">{{ formatBytes(data.dockerDiskUsage.containers_size, true) }}</span>
                        </div>
                        <div class="flex justify-between items-center p-3 bg-muted rounded-lg">
                            <span class="text-sm font-medium">Images</span>
                            <span class="text-sm">{{ formatBytes(data.dockerDiskUsage.images_size, true) }}</span>
                        </div>
                        <div class="flex justify-between items-center p-3 bg-muted rounded-lg">
                            <span class="text-sm font-medium">Build Cache</span>
                            <span class="text-sm">{{ formatBytes(data.dockerDiskUsage.build_cache_size) }}</span>
                        </div>
                        <div
                            class="flex justify-between items-center p-3 bg-primary/10 rounded-lg border border-primary/20"
                        >
                            <span class="text-sm font-bold">Total Docker Usage</span>
                            <span class="text-sm font-bold">
                                {{
                                    formatBytes(
                                        data.dockerDiskUsage.containers_size +
                                            data.dockerDiskUsage.images_size +
                                            data.dockerDiskUsage.build_cache_size,
                                        true,
                                    )
                                }}
                            </span>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Docker Management -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">Docker Management</CardTitle>
                </CardHeader>
                <CardContent>
                    <div class="space-y-4">
                        <div
                            v-if="
                                data.dockerDiskUsage.images_total - data.dockerDiskUsage.images_active > 0 ||
                                data.dockerDiskUsage.build_cache_size > 0
                            "
                            class="p-4 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-lg"
                        >
                            <div class="flex items-start gap-3">
                                <div class="flex-1">
                                    <div class="font-medium text-yellow-800 dark:text-yellow-200">
                                        Cleanup Recommendation
                                    </div>
                                    <div class="text-sm text-yellow-700 dark:text-yellow-300 mt-1">
                                        You have
                                        {{ data.dockerDiskUsage.images_total - data.dockerDiskUsage.images_active }}
                                        inactive Docker images. Pruning them could free up space.
                                    </div>
                                    <div class="text-xs text-yellow-600 dark:text-yellow-400 mt-2">
                                        Build cache:
                                        {{ formatBytes(data.dockerDiskUsage.build_cache_size, true) }} could also be
                                        reclaimed.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <Button
                            variant="outline"
                            class="w-full"
                            :loading="pruning"
                            :disabled="data.dockerDiskUsage.images_total - data.dockerDiskUsage.images_active === 0"
                            @click="$emit('prune')"
                        >
                            <Trash2 :size="16" class="mr-2" />
                            Prune Unused Images
                        </Button>
                    </div>
                </CardContent>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems and Contributors
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert } from '@/components/ui/alert';
import { Trash2 } from 'lucide-vue-next';
import { formatBytes } from '@/lib/format';
import type { DockerResponse } from '../types';

defineProps<{
    loading: boolean;
    data: DockerResponse | null;
    error: string | null;
    pruning: boolean;
}>();

defineEmits<{
    prune: [];
}>();
</script>
