// frontendv2/src/app/(app)/admin/nodes/[id]/components/NodeHeader.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
This file is part of FeatherPanel.

Copyright (C) 2025 MythicalSystems Studios
Copyright (C) 2025 FeatherPanel Contributors
Copyright (C) 2025 Cassian Gherman (aka NaysKutzu)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the LICENSE file or <https://www.gnu.org/licenses/>.
*/

import React from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import { Button } from '@/components/featherui/Button';
import { PageHeader } from '@/components/featherui/PageHeader';
import { Database, Network, ArrowLeft, Activity } from 'lucide-react';
import { NodeData, SystemInfoResponse } from '../types';

interface NodeHeaderProps {
    node: NodeData;
    locationName: string;
    systemInfoData: SystemInfoResponse | null;
    systemInfoError: string | null;
    onDatabases: () => void;
    onAllocations: () => void;
    onBack: () => void;
}

export function NodeHeader({
    node,
    locationName,
    systemInfoData,
    systemInfoError,
    onDatabases,
    onAllocations,
    onBack,
}: NodeHeaderProps) {
    const { t } = useTranslation();

    const isOnline = !!systemInfoData && !systemInfoError;

    return (
        <PageHeader
            title={node.name}
            description={
                <div className='flex items-center gap-2 mt-1'>
                    <span className='text-sm text-muted-foreground'>{node.fqdn}</span>
                    <span className='text-muted-foreground/30'>•</span>
                    <span className='text-sm text-muted-foreground'>{locationName}</span>
                </div>
            }
            icon={Activity}
            actions={
                <div className='flex items-center gap-3'>
                    <div className='flex items-center gap-2 mr-2 px-3 py-1.5 rounded-full bg-background/50 border border-border/50'>
                        {isOnline ? (
                            <>
                                <div className='h-2 w-2 rounded-full bg-green-500 animate-pulse' />
                                <span className='text-xs font-medium text-green-500'>
                                    {t('admin.node.health.online')}
                                </span>
                            </>
                        ) : (
                            <>
                                <div className='h-2 w-2 rounded-full bg-red-500' />
                                <span className='text-xs font-medium text-red-500'>
                                    {t('admin.node.health.offline')}
                                </span>
                            </>
                        )}
                    </div>
                    <Button variant='outline' size='sm' onClick={onBack}>
                        <ArrowLeft className='h-4 w-4 mr-2' />
                        {t('common.back')}
                    </Button>
                    <Button variant='outline' size='sm' onClick={onDatabases}>
                        <Database className='h-4 w-4 mr-2' />
                        {t('admin.node.view.databases')}
                    </Button>
                    <Button variant='outline' size='sm' onClick={onAllocations}>
                        <Network className='h-4 w-4 mr-2' />
                        {t('admin.node.view.allocations')}
                    </Button>
                </div>
            }
        />
    );
}

// frontend/src/pages/admin/nodes/view/components/NodeHeader.vue
<!--
MIT License

Copyright (c) 2025 MythicalSystems and Contributors
Copyright (c) 2025 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
-->

<template>
    <div class="mb-6">
        <div class="flex items-start justify-between mb-4">
            <div>
                <div class="flex items-center gap-3 mb-2">
                    <h1 class="text-3xl font-bold">{{ node.name }}</h1>
                    <div
                        :class="[
                            'h-3 w-3 rounded-full',
                            systemInfoError
                                ? 'bg-red-500 animate-pulse'
                                : systemInfoData
                                  ? 'bg-green-500'
                                  : 'bg-gray-400',
                        ]"
                        :title="systemInfoError ? 'Unhealthy' : systemInfoData ? 'Healthy' : 'Unknown'"
                    ></div>
                </div>
                <p class="text-muted-foreground text-lg">{{ node.fqdn }}</p>
                <p class="text-sm text-muted-foreground mt-1">Location: {{ locationName }}</p>
            </div>
            <div class="flex gap-2 flex-wrap">
                <Button variant="outline" size="sm" @click="$emit('databases')">
                    <Database :size="16" class="mr-2" />
                    Databases
                </Button>
                <Button variant="outline" size="sm" @click="$emit('allocations')">
                    <Network :size="16" class="mr-2" />
                    Allocations
                </Button>
                <Button variant="outline" size="sm" @click="$emit('back')">
                    <ArrowLeft :size="16" class="mr-2" />
                    Back
                </Button>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems and Contributors
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { Button } from '@/components/ui/button';
import { Database, Network, ArrowLeft } from 'lucide-vue-next';
import type { Node, SystemInfoResponse } from '../types';

defineProps<{
    node: Node;
    locationName: string;
    systemInfoData: SystemInfoResponse | null;
    systemInfoError: string | null;
}>();

defineEmits<{
    databases: [];
    allocations: [];
    back: [];
}>();
</script>
