// frontendv2/src/app/(app)/admin/nodes/[id]/components/SystemInfoTab.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/*
This file is part of FeatherPanel.

Copyright (C) 2025 MythicalSystems Studios
Copyright (C) 2025 FeatherPanel Contributors
Copyright (C) 2025 Cassian Gherman (aka NaysKutzu)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the LICENSE file or <https://www.gnu.org/licenses/>.
*/

import React, { useState, useEffect } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import { PageCard } from '@/components/featherui/PageCard';
import { Button } from '@/components/featherui/Button';
import { Badge } from '@/components/ui/badge';
import { AlertTriangle, Check, RefreshCw, Cpu, LayoutGrid, Shield } from 'lucide-react';
import { formatBytes } from '@/lib/format';
import axios from 'axios';
import { SystemInfoResponse, VersionStatus } from '../types';

interface SystemInfoTabProps {
    nodeId: number;
    loading: boolean;
    data: SystemInfoResponse | null;
    error: string | null;
    onRefresh: () => void;
}

export function SystemInfoTab({ nodeId, loading, data, error, onRefresh }: SystemInfoTabProps) {
    const { t } = useTranslation();
    const [versionStatus, setVersionStatus] = useState<VersionStatus | null>(null);
    const [versionLoading, setVersionLoading] = useState(false);

    const fetchVersionStatus = async () => {
        if (!nodeId || !data) return;
        setVersionLoading(true);
        try {
            const res = await axios.get(`/api/admin/nodes/${nodeId}/version-status`);
            if (res.data.success) {
                setVersionStatus(res.data.data);
            }
        } catch (e) {
            console.error('Failed to fetch version status', e);
        } finally {
            setVersionLoading(false);
        }
    };

    useEffect(() => {
        if (data && nodeId) {
            fetchVersionStatus();
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [data, nodeId]);

    if (loading) {
        return (
            <div className='flex items-center justify-center py-12'>
                <RefreshCw className='h-8 w-8 animate-spin text-primary' />
            </div>
        );
    }

    if (error) {
        return (
            <PageCard title={t('admin.node.view.system.error_title')} icon={AlertTriangle}>
                <div className='p-4 bg-destructive/10 border border-destructive/20 rounded-xl text-center'>
                    <p className='text-destructive mb-4'>{error}</p>
                    <Button variant='outline' onClick={onRefresh}>
                        {t('common.retry')}
                    </Button>
                </div>
            </PageCard>
        );
    }

    if (!data) return null;

    return (
        <div className='space-y-6'>
            {/* Wings Information */}
            <PageCard title={t('admin.node.view.system.wings_info')} icon={Shield}>
                <div className='space-y-6'>
                    <div>
                        <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                            {t('admin.node.view.system.wings_version')}
                        </p>
                        <p className='text-sm font-mono'>{data.wings.version}</p>
                    </div>

                    {versionLoading ? (
                        <div className='flex items-center gap-2 p-4 rounded-2xl bg-muted/30'>
                            <RefreshCw className='h-4 w-4 animate-spin text-primary' />
                            <span className='text-sm text-muted-foreground'>
                                {t('admin.node.view.system.checking_updates')}
                            </span>
                        </div>
                    ) : versionStatus?.update_available ? (
                        <div className='flex items-start gap-4 p-4 rounded-2xl bg-orange-500/10 border border-orange-500/20'>
                            <div className='p-2 rounded-xl bg-orange-500/20 h-fit'>
                                <AlertTriangle className='h-5 w-5 text-orange-500' />
                            </div>
                            <div className='flex-1'>
                                <p className='text-sm font-bold text-orange-500 mb-1'>
                                    {t('admin.node.view.system.update_available')}
                                </p>
                                <p className='text-sm text-orange-500/80 mb-2'>
                                    {t('admin.node.view.system.current')}:{' '}
                                    <span className='font-mono'>{versionStatus.current_version}</span> →{' '}
                                    {t('admin.node.view.system.latest')}:{' '}
                                    <span className='font-mono'>v{versionStatus.latest_version}</span>
                                </p>
                                <p className='text-xs text-orange-500/60 leading-relaxed italic'>
                                    {t('admin.node.view.system.update_help')}
                                </p>
                            </div>
                        </div>
                    ) : versionStatus?.is_up_to_date ? (
                        <div className='flex items-center gap-4 p-4 rounded-2xl bg-green-500/10 border border-green-500/20'>
                            <div className='p-2 rounded-xl bg-green-500/20 h-fit'>
                                <Check className='h-5 w-5 text-green-500' />
                            </div>
                            <div>
                                <p className='text-sm font-bold text-green-500 mb-1'>
                                    {t('admin.node.view.system.up_to_date')}
                                </p>
                                <p className='text-sm text-green-500/80 font-mono'>{versionStatus.current_version}</p>
                            </div>
                        </div>
                    ) : versionStatus?.github_error ? (
                        <div className='flex items-center gap-3 p-4 rounded-2xl bg-muted/30 text-muted-foreground'>
                            <AlertTriangle className='h-4 w-4' />
                            <span className='text-sm italic'>{versionStatus.github_error}</span>
                        </div>
                    ) : null}
                </div>
            </PageCard>

            <div className='grid grid-cols-1 lg:grid-cols-2 gap-6'>
                {/* Docker Information */}
                <PageCard title={t('admin.node.view.system.docker_info')} icon={LayoutGrid}>
                    <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.docker_version')}
                            </p>
                            <p className='text-sm font-mono'>{data.wings.docker.version}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.cgroups_driver')}
                            </p>
                            <p className='text-sm'>
                                {data.wings.docker.cgroups.driver} (v{data.wings.docker.cgroups.version})
                            </p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.storage_driver')}
                            </p>
                            <p className='text-sm'>
                                {data.wings.docker.storage.driver} ({data.wings.docker.storage.filesystem})
                            </p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.runc_version')}
                            </p>
                            <p className='text-sm font-mono'>{data.wings.docker.runc.version}</p>
                        </div>
                        <div className='md:col-span-2 pt-4 border-t border-border/50'>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-3'>
                                {t('admin.node.view.system.containers')}
                            </p>
                            <div className='flex flex-wrap gap-3'>
                                <Badge
                                    variant='secondary'
                                    className='px-3 py-1 bg-primary/5 text-primary border-primary/10'
                                >
                                    {t('admin.node.view.system.total')}: {data.wings.docker.containers.total}
                                </Badge>
                                <Badge
                                    variant='secondary'
                                    className='px-3 py-1 bg-green-500/5 text-green-500 border-green-500/10'
                                >
                                    {t('admin.node.view.system.running')}: {data.wings.docker.containers.running}
                                </Badge>
                                <Badge
                                    variant='secondary'
                                    className='px-3 py-1 bg-yellow-500/5 text-yellow-500 border-yellow-500/10'
                                >
                                    {t('admin.node.view.system.paused')}: {data.wings.docker.containers.paused}
                                </Badge>
                                <Badge
                                    variant='secondary'
                                    className='px-3 py-1 bg-red-500/5 text-red-500 border-red-500/10'
                                >
                                    {t('admin.node.view.system.stopped')}: {data.wings.docker.containers.stopped}
                                </Badge>
                            </div>
                        </div>
                    </div>
                </PageCard>

                {/* Host System Information */}
                <PageCard title={t('admin.node.view.system.host_info')} icon={Cpu}>
                    <div className='grid grid-cols-1 md:grid-cols-2 gap-6'>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.architecture')}
                            </p>
                            <p className='text-sm font-mono uppercase'>{data.wings.system.architecture}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.cpu_threads')}
                            </p>
                            <p className='text-sm'>{data.wings.system.cpu_threads}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.total_memory')}
                            </p>
                            <p className='text-sm'>{formatBytes(data.wings.system.memory_bytes)}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.kernel_version')}
                            </p>
                            <p className='text-sm font-mono'>{data.wings.system.kernel_version}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.operating_system')}
                            </p>
                            <p className='text-sm'>{data.wings.system.os}</p>
                        </div>
                        <div>
                            <p className='text-xs font-bold uppercase tracking-wider text-muted-foreground mb-1'>
                                {t('admin.node.view.system.os_type')}
                            </p>
                            <p className='text-sm capitalize'>{data.wings.system.os_type}</p>
                        </div>
                    </div>
                </PageCard>
            </div>
        </div>
    );
}

// frontend/src/pages/admin/nodes/view/components/SystemInfoTab.vue
<template>
    <div class="space-y-4">
        <div v-if="loading" class="flex items-center justify-center py-8">
            <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
        </div>

        <div v-else-if="error" class="space-y-4">
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg flex items-center gap-2">
                        <div class="h-3 w-3 bg-red-500 rounded-full animate-pulse"></div>
                        System Information Unavailable
                    </CardTitle>
                </CardHeader>
                <CardContent>
                    <Alert variant="destructive">
                        <div class="space-y-3">
                            <div class="font-medium">Failed to fetch system information</div>
                            <div class="text-sm">{{ error }}</div>
                            <Button size="sm" variant="outline" @click="$emit('retry')">Retry</Button>
                        </div>
                    </Alert>
                </CardContent>
            </Card>
        </div>

        <div v-else-if="data" class="space-y-4">
            <!-- Wings Information -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">Wings Information</CardTitle>
                </CardHeader>
                <CardContent class="space-y-4">
                    <div>
                        <div class="text-sm font-medium text-muted-foreground mb-1">Version</div>
                        <div class="text-sm font-mono">{{ data.wings.version }}</div>
                    </div>

                    <!-- Version Status Check -->
                    <div v-if="versionStatusLoading" class="flex items-center gap-2 p-3 rounded-lg bg-muted/50">
                        <div class="animate-spin rounded-full h-4 w-4 border-2 border-primary border-t-transparent"></div>
                        <span class="text-sm text-muted-foreground">Checking for updates...</span>
                    </div>

                    <!-- Update Available -->
                    <div
                        v-else-if="versionStatus && versionStatus.update_available"
                        class="flex items-start gap-3 p-4 rounded-lg border bg-orange-50/50 dark:bg-orange-950/20 border-orange-200 dark:border-orange-800"
                    >
                        <div class="h-8 w-8 rounded-lg bg-orange-500/10 dark:bg-orange-500/20 flex items-center justify-center shrink-0">
                            <AlertTriangle class="h-4 w-4 text-orange-600 dark:text-orange-400" />
                        </div>
                        <div class="flex-1 min-w-0">
                            <div class="font-semibold text-sm text-orange-900 dark:text-orange-100 mb-1">
                                Update Available
                            </div>
                            <div class="text-sm text-orange-800 dark:text-orange-200">
                                <p>
                                    Current: <span class="font-mono font-medium">{{ versionStatus.current_version }}</span> →
                                    Latest: <span class="font-mono font-medium">v{{ versionStatus.latest_version }}</span>
                                </p>
                                <p class="mt-1.5 text-orange-700 dark:text-orange-300">
                                    A new FeatherWings version is available. Please update for the latest features and security improvements.
                                </p>
                            </div>
                        </div>
                    </div>

                    <!-- Up to Date -->
                    <div
                        v-else-if="versionStatus && versionStatus.is_up_to_date"
                        class="flex items-start gap-3 p-4 rounded-lg border bg-green-50/50 dark:bg-green-950/20 border-green-200 dark:border-green-800"
                    >
                        <div class="h-8 w-8 rounded-lg bg-green-500/10 dark:bg-green-500/20 flex items-center justify-center shrink-0">
                            <Check class="h-4 w-4 text-green-600 dark:text-green-400" />
                        </div>
                        <div class="flex-1 min-w-0">
                            <div class="font-semibold text-sm text-green-900 dark:text-green-100 mb-1">
                                Up to Date
                            </div>
                            <div class="text-sm text-green-800 dark:text-green-200">
                                Running the latest version <span class="font-mono font-medium">{{ versionStatus.current_version }}</span>
                            </div>
                        </div>
                    </div>

                    <!-- GitHub Error -->
                    <div
                        v-else-if="versionStatus && versionStatus.github_error"
                        class="flex items-start gap-3 p-4 rounded-lg border bg-muted/50 border-border"
                    >
                        <div class="h-8 w-8 rounded-lg bg-muted flex items-center justify-center shrink-0">
                            <AlertTriangle class="h-4 w-4 text-muted-foreground" />
                        </div>
                        <div class="flex-1 min-w-0">
                            <div class="text-sm text-muted-foreground">
                                Unable to check for updates. {{ versionStatus.github_error }}
                            </div>
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- Docker Information -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">Docker Information</CardTitle>
                </CardHeader>
                <CardContent class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Version</div>
                        <div class="text-sm">{{ data.wings.docker.version }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">CGroups Driver</div>
                        <div class="text-sm">{{ data.wings.docker.cgroups.driver }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">CGroups Version</div>
                        <div class="text-sm">{{ data.wings.docker.cgroups.version }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Storage Driver</div>
                        <div class="text-sm">{{ data.wings.docker.storage.driver }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Storage Filesystem</div>
                        <div class="text-sm">{{ data.wings.docker.storage.filesystem }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">RunC Version</div>
                        <div class="text-sm">{{ data.wings.docker.runc.version }}</div>
                    </div>
                    <div class="md:col-span-2">
                        <div class="text-sm font-medium text-muted-foreground">Containers</div>
                        <div class="text-sm">
                            Total: {{ data.wings.docker.containers.total }}, Running:
                            {{ data.wings.docker.containers.running }}, Paused:
                            {{ data.wings.docker.containers.paused }}, Stopped:
                            {{ data.wings.docker.containers.stopped }}
                        </div>
                    </div>
                </CardContent>
            </Card>

            <!-- System Information -->
            <Card>
                <CardHeader>
                    <CardTitle class="text-lg">System Information</CardTitle>
                </CardHeader>
                <CardContent class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Architecture</div>
                        <div class="text-sm">{{ data.wings.system.architecture }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">CPU Threads</div>
                        <div class="text-sm">{{ data.wings.system.cpu_threads }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Memory</div>
                        <div class="text-sm">{{ formatBytes(data.wings.system.memory_bytes, true) }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">Kernel Version</div>
                        <div class="text-sm">{{ data.wings.system.kernel_version }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">OS</div>
                        <div class="text-sm">{{ data.wings.system.os }}</div>
                    </div>
                    <div>
                        <div class="text-sm font-medium text-muted-foreground">OS Type</div>
                        <div class="text-sm">{{ data.wings.system.os_type }}</div>
                    </div>
                </CardContent>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems and Contributors
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, watch } from 'vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert } from '@/components/ui/alert';
import { AlertTriangle, Check } from 'lucide-vue-next';
import { formatBytes } from '@/lib/format';
import axios from 'axios';
import type { SystemInfoResponse } from '../types';

const props = defineProps<{
    loading: boolean;
    data: SystemInfoResponse | null;
    error: string | null;
    nodeId?: number;
}>();

defineEmits<{
    retry: [];
}>();

const versionStatus = ref<{
    current_version: string;
    latest_version: string | null;
    is_up_to_date: boolean;
    update_available: boolean;
    github_error: string | null;
} | null>(null);
const versionStatusLoading = ref(false);

async function fetchVersionStatus() {
    if (!props.nodeId || !props.data) return;

    versionStatusLoading.value = true;
    try {
        const { data } = await axios.get(`/api/admin/nodes/${props.nodeId}/version-status`);
        if (data.success) {
            versionStatus.value = data.data;
        }
    } catch {
        // Silently fail - version check is not critical
        versionStatus.value = null;
    } finally {
        versionStatusLoading.value = false;
    }
}

// Fetch version status when data is loaded
watch(
    () => [props.data, props.nodeId],
    ([newData, newNodeId]) => {
        if (newData && newNodeId) {
            fetchVersionStatus();
        }
    },
    { immediate: true }
);

onMounted(() => {
    if (props.data && props.nodeId) {
        fetchVersionStatus();
    }
});
</script>
