// featherpanel-frontendv2/src/app/admin/nodes/[id]/components/WingsConfigTab.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { Editor } from '@monaco-editor/react';
import { useTranslation } from '@/contexts/TranslationContext';
import { useTheme } from '@/contexts/ThemeContext';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/featherui/Button';
import { Checkbox } from '@/components/ui/checkbox';
import { Settings2, Save, RotateCw, AlertTriangle, Loader2 } from 'lucide-react';
import { NodeData } from '../types';
import axios from 'axios';
import { toast } from 'sonner';

interface WingsConfigTabProps {
    node: NodeData;
}

export function WingsConfigTab({ node }: WingsConfigTabProps) {
    const { t } = useTranslation();
    const { theme } = useTheme();
    const [content, setContent] = useState<string>('');
    const [originalContent, setOriginalContent] = useState<string>('');
    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [restart, setRestart] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const fetchConfig = useCallback(async () => {
        setLoading(true);
        setError(null);
        try {
            const { data } = await axios.get(`/api/admin/nodes/${node.id}/wings/config`);
            if (data.success) {
                const config = data.data.config || '';
                setContent(config);
                setOriginalContent(config);
            } else {
                setError(data.message || 'Failed to load Wings configuration');
            }
        } catch (err: unknown) {
            let msg = 'Failed to load Wings configuration';
            if (axios.isAxiosError(err)) {
                msg = err.response?.data?.message || err.message;
            }
            setError(msg);
        } finally {
            setLoading(false);
        }
    }, [node.id]);

    useEffect(() => {
        fetchConfig();
    }, [fetchConfig]);

    const handleSave = async () => {
        setSaving(true);
        try {
            const { data } = await axios.put(`/api/admin/nodes/${node.id}/wings/config`, {
                config: content,
                restart: restart,
            });

            if (data.success) {
                setOriginalContent(content);
                toast.success(t('admin.node.view.config.save_success'));
                if (restart) {
                    toast.info(t('admin.node.view.config.restart_notice'));
                }
            } else {
                toast.error(data.message || 'Failed to save configuration');
            }
        } catch (err: unknown) {
            let msg = 'Failed to save configuration';
            if (axios.isAxiosError(err)) {
                msg = err.response?.data?.message || err.message;
            }
            toast.error(msg);
        } finally {
            setSaving(false);
        }
    };

    const isDirty = content !== originalContent;

    return (
        <Card className='border-none shadow-none bg-transparent'>
            <CardHeader className='px-0 pt-0'>
                <div className='flex items-center justify-between'>
                    <div className='space-y-1'>
                        <CardTitle className='text-lg flex items-center gap-2'>
                            <Settings2 className='h-5 w-5 text-primary' />
                            {t('admin.node.view.config.title')}
                        </CardTitle>
                        <CardDescription>{t('admin.node.view.config.description')}</CardDescription>
                    </div>
                    <div className='flex items-center gap-3'>
                        <Button
                            variant='outline'
                            size='sm'
                            onClick={fetchConfig}
                            disabled={loading || saving}
                            className='h-10 rounded-xl'
                        >
                            <RotateCw className={`h-4 w-4 mr-2 ${loading ? 'animate-spin' : ''}`} />
                            {t('common.reload')}
                        </Button>
                        <Button
                            size='sm'
                            onClick={handleSave}
                            disabled={loading || saving || !isDirty}
                            className='h-10 rounded-xl'
                        >
                            {saving ? (
                                <Loader2 className='h-4 w-4 mr-2 animate-spin' />
                            ) : (
                                <Save className='h-4 w-4 mr-2' />
                            )}
                            {t('common.save')}
                        </Button>
                    </div>
                </div>
            </CardHeader>
            <CardContent className='px-0 space-y-6'>
                {error ? (
                    <div className='rounded-2xl border border-destructive/20 bg-destructive/5 p-6 text-center'>
                        <AlertTriangle className='h-8 w-8 text-destructive mx-auto mb-3' />
                        <h3 className='text-sm font-bold text-destructive mb-1'>Failed to Load Configuration</h3>
                        <p className='text-xs text-destructive/80 mb-4'>{error}</p>
                        <Button variant='outline' size='sm' onClick={fetchConfig} className='rounded-xl'>
                            Try Again
                        </Button>
                    </div>
                ) : (
                    <>
                        <div className='rounded-2xl border border-border/50 bg-card overflow-hidden h-[500px] shadow-xl relative'>
                            {loading && (
                                <div className='absolute inset-0 bg-background/50 backdrop-blur-sm z-10 flex items-center justify-center'>
                                    <Loader2 className='h-8 w-8 text-primary animate-spin' />
                                </div>
                            )}
                            <Editor
                                height='100%'
                                defaultLanguage='yaml'
                                value={content}
                                theme={theme === 'dark' ? 'vs-dark' : 'light'}
                                onChange={(value) => setContent(value || '')}
                                options={{
                                    minimap: { enabled: true },
                                    fontSize: 14,
                                    lineNumbers: 'on',
                                    scrollBeyondLastLine: false,
                                    automaticLayout: true,
                                    padding: { top: 20 },
                                    fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
                                    fontLigatures: true,
                                }}
                            />
                        </div>

                        <div className='rounded-2xl border border-border/50 bg-muted/30 p-4'>
                            <div className='flex items-center space-x-3'>
                                <Checkbox
                                    id='restart-wings'
                                    checked={restart}
                                    onCheckedChange={(checked) => setRestart(!!checked)}
                                    className='h-5 w-5 rounded-lg border-2'
                                />
                                <div className='grid gap-1.5 leading-none'>
                                    <label
                                        htmlFor='restart-wings'
                                        className='text-sm font-bold cursor-pointer select-none leading-none'
                                    >
                                        {t('admin.node.view.config.restart_checkbox')}
                                    </label>
                                    <p className='text-xs text-muted-foreground'>
                                        {t('admin.node.view.config.restart_help')}
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div className='rounded-2xl border border-blue-500/20 bg-blue-500/5 p-4'>
                            <div className='flex items-start gap-4'>
                                <div className='p-2 rounded-xl bg-blue-500/10'>
                                    <Settings2 className='h-5 w-5 text-blue-500' />
                                </div>
                                <div className='flex-1'>
                                    <div className='text-sm font-bold text-blue-600 dark:text-blue-500 mb-1'>
                                        {t('admin.node.view.config.info_title')}
                                    </div>
                                    <p className='text-xs text-blue-600/80 dark:text-blue-400/70 leading-relaxed'>
                                        {t('admin.node.view.config.info_description')}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </>
                )}
            </CardContent>
        </Card>
    );
}

// frontend/src/pages/admin/nodes/view/components/WingsConfigTab.vue
<template>
    <Card>
        <CardHeader>
            <CardTitle class="text-lg flex items-center gap-2">
                <svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"
                    />
                </svg>
                Wings Configuration
            </CardTitle>
            <CardDescription>View and edit the Wings daemon configuration file directly</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
            <div v-if="loading" class="flex items-center justify-center py-8">
                <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
            </div>

            <div v-else-if="error" class="space-y-4">
                <Alert variant="destructive">
                    <div class="space-y-3">
                        <div class="font-medium">Failed to load Wings configuration</div>
                        <div class="text-sm">{{ error }}</div>
                    </div>
                </Alert>
                <Button size="sm" variant="outline" :loading="loading" @click="$emit('reload')">Retry</Button>
            </div>

            <div v-else-if="content !== null" class="space-y-4">
                <div class="flex items-center justify-between">
                    <div class="text-sm text-muted-foreground">Configuration file from Wings daemon</div>
                    <div class="flex gap-2">
                        <Button size="sm" variant="outline" :disabled="saving" @click="$emit('reload')">
                            <RefreshCw :size="16" class="mr-2" />
                            Reload
                        </Button>
                        <Button size="sm" variant="outline" :disabled="saving || !dirty" @click="$emit('reset')">
                            Reset
                        </Button>
                    </div>
                </div>

                <div class="space-y-2">
                    <Label class="text-sm font-medium">Configuration (YAML)</Label>
                    <textarea
                        :value="content"
                        class="w-full h-96 p-3 text-xs font-mono bg-muted border rounded-md resize-none"
                        :disabled="saving"
                        @input="$emit('update:content', ($event.target as HTMLTextAreaElement).value)"
                    ></textarea>
                    <p class="text-xs text-muted-foreground">
                        Edit the YAML configuration directly. Changes will be saved to Wings.
                    </p>
                </div>

                <div
                    class="flex items-center gap-2 p-3 bg-yellow-50 dark:bg-yellow-950 border border-yellow-200 dark:border-yellow-800 rounded-lg"
                >
                    <svg
                        class="h-5 w-5 text-yellow-600 dark:text-yellow-400 shrink-0"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                    >
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"
                        />
                    </svg>
                    <div class="flex-1">
                        <div class="text-sm font-semibold text-yellow-800 dark:text-yellow-200">
                            Configuration Warning
                        </div>
                        <p class="mt-1 text-xs text-yellow-700 dark:text-yellow-300">
                            Invalid configuration may cause Wings to fail to start. Always review changes carefully.
                            Consider backing up the configuration before making changes.
                        </p>
                    </div>
                </div>

                <div class="flex items-center justify-between p-3 bg-muted rounded-lg">
                    <div class="flex items-center gap-4">
                        <div class="flex items-center gap-2">
                            <input
                                id="wings-config-restart"
                                :checked="restart"
                                type="checkbox"
                                :disabled="saving"
                                class="h-4 w-4 rounded border-gray-300 text-primary focus:ring-2 focus:ring-primary focus:ring-offset-0 disabled:opacity-50 disabled:cursor-not-allowed dark:border-gray-600 dark:bg-gray-700"
                                @change="$emit('update:restart', ($event.target as HTMLInputElement).checked)"
                            />
                            <Label class="text-sm font-medium" for="wings-config-restart"
                                >Restart Wings after save</Label
                            >
                        </div>
                    </div>
                    <Button size="sm" :loading="saving" :disabled="!dirty || saving" @click="$emit('save')">
                        <svg v-if="!saving" class="h-4 w-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7" />
                        </svg>
                        Save Configuration
                    </Button>
                </div>
            </div>
        </CardContent>
    </Card>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems and Contributors
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Alert } from '@/components/ui/alert';
import { RefreshCw } from 'lucide-vue-next';

defineProps<{
    loading: boolean;
    error: string | null;
    content: string | null;
    dirty: boolean;
    saving: boolean;
    restart: boolean;
}>();

defineEmits<{
    'update:content': [value: string];
    'update:restart': [value: boolean];
    reload: [];
    reset: [];
    save: [];
}>();
</script>
