// frontendv2/src/app/(app)/admin/dev/console/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import { useState, useEffect, useRef, useCallback } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import { useRouter } from 'next/navigation';
import axios from 'axios';
import { PageHeader } from '@/components/featherui/PageHeader';
import { PageCard } from '@/components/featherui/PageCard';
import { Button } from '@/components/featherui/Button';
import { Input } from '@/components/featherui/Input';
import { EmptyState } from '@/components/featherui/EmptyState';
import { useDeveloperMode } from '@/hooks/useDeveloperMode';
import { toast } from 'sonner';
import { Terminal, Lock, Loader2, RefreshCw, Trash2, Eye, EyeOff } from 'lucide-react';

interface CommandResult {
    stdout: string;
    stderr: string;
    return_code: number;
    execution_time: number;
    command: string;
    working_directory: string;
    timestamp: string;
}

interface SystemInfo {
    os: string;
    php_version: string;
    server_software: string;
    server_name: string;
    user: string;
    home: string;
    working_directory: string;
    disk_usage: {
        free: number;
        total: number;
        used: number;
        percentage: number;
    };
    memory_usage: Record<string, number>;
    uptime: string;
}

interface TerminalLine {
    id: string;
    type: 'command' | 'output' | 'error' | 'info';
    content: string;
    timestamp: string;
    command?: string;
    returnCode?: number;
    executionTime?: number;
}

function formatBytes(bytes: number): string {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return Math.round((bytes / Math.pow(k, i)) * 100) / 100 + ' ' + sizes[i];
}

export default function ConsolePage() {
    const { t } = useTranslation();
    const router = useRouter();
    const { isDeveloperModeEnabled, loading: developerModeLoading } = useDeveloperMode();
    const [commandInput, setCommandInput] = useState('');
    const [currentDirectory, setCurrentDirectory] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [terminalLines, setTerminalLines] = useState<TerminalLine[]>([]);
    const [systemInfo, setSystemInfo] = useState<SystemInfo | null>(null);
    const [showSystemInfo, setShowSystemInfo] = useState(false);
    const [commandHistory, setCommandHistory] = useState<string[]>([]);
    const [, setHistoryIndex] = useState(-1);
    const terminalRef = useRef<HTMLDivElement>(null);
    const inputRef = useRef<HTMLInputElement>(null);

    const getPrompt = useCallback((): string => {
        const user = systemInfo?.user || 'www-data';
        const dir = currentDirectory.replace(/^.*\//, '~');
        return `${user}@featherpanel:${dir}$`;
    }, [systemInfo, currentDirectory]);

    const addTerminalLine = useCallback(
        (
            type: TerminalLine['type'],
            content: string,
            command?: string,
            returnCode?: number,
            executionTime?: number,
        ) => {
            const line: TerminalLine = {
                id: Date.now() + '-' + Math.random(),
                type,
                content,
                timestamp: new Date().toLocaleTimeString(),
                command,
                returnCode,
                executionTime,
            };
            setTerminalLines((prev) => [...prev, line]);
        },
        [],
    );

    const scrollToBottom = useCallback(() => {
        setTimeout(() => {
            if (terminalRef.current) {
                terminalRef.current.scrollTop = terminalRef.current.scrollHeight;
            }
        }, 0);
    }, []);

    const fetchSystemInfo = useCallback(async () => {
        if (isDeveloperModeEnabled !== true) return;

        try {
            const response = await axios.get<{ success: boolean; data: SystemInfo; message?: string }>(
                '/api/admin/console/system-info',
            );
            if (response.data.success) {
                setSystemInfo(response.data.data);
                setCurrentDirectory(response.data.data.working_directory);
                addTerminalLine('info', `Connected to ${response.data.data.server_name} (${response.data.data.os})`);
                addTerminalLine('info', `PHP ${response.data.data.php_version} | User: ${response.data.data.user}`);
            } else {
                toast.error(response.data.message || t('admin.dev.console.messages.fetch_failed'));
            }
        } catch (error) {
            console.error('Failed to fetch system info:', error);
            toast.error(t('admin.dev.console.messages.fetch_failed'));
        }
    }, [isDeveloperModeEnabled, addTerminalLine, t]);

    const executeCommand = useCallback(async () => {
        if (!commandInput.trim() || isDeveloperModeEnabled !== true) return;

        const command = commandInput.trim();
        setCommandHistory((prev) => {
            const newHistory = [command, ...prev].slice(0, 100);
            return newHistory;
        });
        setHistoryIndex(-1);

        addTerminalLine('command', `${getPrompt()} ${command}`);
        setCommandInput('');
        setIsLoading(true);

        try {
            const response = await axios.post<{ success: boolean; data: CommandResult; message?: string }>(
                '/api/admin/console/execute',
                new URLSearchParams({
                    command: command,
                    cwd: currentDirectory,
                }),
            );

            if (response.data.success) {
                const result = response.data.data;

                // Update current directory if cd command was used
                if (command.startsWith('cd ')) {
                    const newDir = command.substring(3).trim();
                    if (newDir === '~' || newDir === '') {
                        setCurrentDirectory(systemInfo?.home || '/var/www');
                    } else if (newDir.startsWith('/')) {
                        setCurrentDirectory(newDir);
                    } else {
                        setCurrentDirectory((prev) => prev + '/' + newDir);
                    }
                }

                // Display output
                if (result.stdout) {
                    addTerminalLine('output', result.stdout);
                }
                if (result.stderr) {
                    addTerminalLine('error', result.stderr);
                }

                // Show command result info
                addTerminalLine('info', `[${result.return_code}] ${result.execution_time}ms`);

                if (result.return_code !== 0 && !result.stderr) {
                    toast.warning(
                        t('admin.dev.console.messages.command_failed', {
                            code: result.return_code.toString() || 'Unknown',
                        }),
                    );
                }
            } else {
                addTerminalLine('error', `Error: ${response.data.message || 'Unknown error'}`);
                toast.error(response.data.message || t('admin.dev.console.messages.execute_failed'));
            }
        } catch (error) {
            console.error('Failed to execute command:', error);
            addTerminalLine('error', `Network error: ${String(error)}`);
            toast.error(t('admin.dev.console.messages.execute_failed'));
        } finally {
            setIsLoading(false);
            scrollToBottom();
        }
    }, [
        commandInput,
        isDeveloperModeEnabled,
        getPrompt,
        currentDirectory,
        systemInfo,
        addTerminalLine,
        scrollToBottom,
        t,
    ]);

    const clearTerminal = useCallback(() => {
        setTerminalLines([]);
        addTerminalLine('info', 'Terminal cleared');
    }, [addTerminalLine]);

    const handleKeyDown = useCallback(
        (e: React.KeyboardEvent<HTMLInputElement>) => {
            if (e.key === 'Enter') {
                e.preventDefault();
                executeCommand();
            } else if (e.key === 'ArrowUp') {
                e.preventDefault();
                setHistoryIndex((prev) => {
                    if (prev < commandHistory.length - 1) {
                        const newIndex = prev + 1;
                        setCommandInput(commandHistory[newIndex] || '');
                        return newIndex;
                    }
                    return prev;
                });
            } else if (e.key === 'ArrowDown') {
                e.preventDefault();
                setHistoryIndex((prev) => {
                    if (prev > 0) {
                        const newIndex = prev - 1;
                        setCommandInput(commandHistory[newIndex] || '');
                        return newIndex;
                    } else if (prev === 0) {
                        setCommandInput('');
                        return -1;
                    }
                    return prev;
                });
            } else if (e.key === 'l' && e.ctrlKey) {
                e.preventDefault();
                clearTerminal();
            }
        },
        [executeCommand, commandHistory, clearTerminal],
    );

    useEffect(() => {
        if (isDeveloperModeEnabled === true) {
            fetchSystemInfo();
            addTerminalLine('info', 'FeatherPanel Console - Type "help" for available commands');
        }
    }, [isDeveloperModeEnabled, fetchSystemInfo, addTerminalLine]);

    // Developer Mode Check
    if (developerModeLoading) {
        return (
            <div className='flex items-center justify-center p-12'>
                <Loader2 className='w-8 h-8 animate-spin text-primary' />
            </div>
        );
    }

    if (isDeveloperModeEnabled === false) {
        return (
            <div className='space-y-6'>
                <EmptyState
                    title={t('admin.dev.developerModeRequired') || 'Developer Mode Required'}
                    description={
                        t('admin.dev.developerModeDescription') ||
                        'Developer mode must be enabled in settings to access developer tools.'
                    }
                    icon={Lock}
                    action={
                        <Button variant='outline' onClick={() => router.push('/admin/settings')}>
                            {t('admin.dev.goToSettings') || 'Go to Settings'}
                        </Button>
                    }
                />
            </div>
        );
    }

    const quickCommands = [
        'ls -la',
        'pwd',
        'whoami',
        'date',
        'df -h',
        'free -h',
        'ps aux',
        'top',
        'git status',
        'composer --version',
        'npm --version',
        'php --version',
    ];

    return (
        <div className='space-y-6'>
            <PageHeader
                title={t('admin.dev.console.title') || 'Console'}
                description={t('admin.dev.console.description') || 'Execute commands on the server'}
                icon={Terminal}
                actions={
                    <div className='flex gap-2'>
                        <Button variant='outline' onClick={() => setShowSystemInfo(!showSystemInfo)}>
                            {showSystemInfo ? (
                                <>
                                    <EyeOff className='w-4 h-4 mr-2' />
                                    {t('admin.dev.console.hide_system_info') || 'Hide System Info'}
                                </>
                            ) : (
                                <>
                                    <Eye className='w-4 h-4 mr-2' />
                                    {t('admin.dev.console.show_system_info') || 'Show System Info'}
                                </>
                            )}
                        </Button>
                        <Button variant='outline' onClick={clearTerminal}>
                            <Trash2 className='w-4 h-4 mr-2' />
                            {t('admin.dev.console.clear_terminal') || 'Clear Terminal'}
                        </Button>
                        <Button variant='outline' onClick={fetchSystemInfo} disabled={isLoading}>
                            <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                            {t('admin.dev.console.refresh') || 'Refresh'}
                        </Button>
                    </div>
                }
            />

            {/* System Info Panel */}
            {showSystemInfo && systemInfo && (
                <PageCard title={t('admin.dev.console.system_info') || 'System Information'}>
                    <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4'>
                        <div>
                            <h3 className='font-semibold mb-2'>{t('admin.dev.console.system') || 'System'}</h3>
                            <div className='text-sm space-y-1'>
                                <div>
                                    <span className='text-muted-foreground'>OS:</span> {systemInfo.os}
                                </div>
                                <div>
                                    <span className='text-muted-foreground'>Server:</span> {systemInfo.server_software}
                                </div>
                                <div>
                                    <span className='text-muted-foreground'>User:</span> {systemInfo.user}
                                </div>
                            </div>
                        </div>
                        <div>
                            <h3 className='font-semibold mb-2'>{t('admin.dev.console.runtime') || 'Runtime'}</h3>
                            <div className='text-sm space-y-1'>
                                <div>
                                    <span className='text-muted-foreground'>PHP:</span> {systemInfo.php_version}
                                </div>
                                <div>
                                    <span className='text-muted-foreground'>Uptime:</span> {systemInfo.uptime}
                                </div>
                            </div>
                        </div>
                        <div>
                            <h3 className='font-semibold mb-2'>{t('admin.dev.console.disk_usage') || 'Disk Usage'}</h3>
                            <div className='text-sm space-y-1'>
                                <div>
                                    <span className='text-muted-foreground'>Used:</span>{' '}
                                    {formatBytes(systemInfo.disk_usage.used)}
                                </div>
                                <div>
                                    <span className='text-muted-foreground'>Free:</span>{' '}
                                    {formatBytes(systemInfo.disk_usage.free)}
                                </div>
                                <div>
                                    <span className='text-muted-foreground'>Usage:</span>{' '}
                                    {systemInfo.disk_usage.percentage}%
                                </div>
                            </div>
                        </div>
                    </div>
                </PageCard>
            )}

            {/* Terminal */}
            <PageCard title={t('admin.dev.console.terminal') || 'Terminal'}>
                <div className='space-y-4'>
                    <p className='text-xs text-muted-foreground'>
                        {t('admin.dev.console.terminal_help') ||
                            'Use Arrow Up/Down for command history, Ctrl+L to clear'}
                    </p>

                    {/* Terminal Output */}
                    <div
                        ref={terminalRef}
                        className='h-96 bg-black text-green-400 p-4 overflow-auto font-mono text-sm rounded-xl border border-border/50'
                        style={{ fontFamily: "'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace" }}
                    >
                        {terminalLines.map((line) => (
                            <div key={line.id} className='mb-1'>
                                {line.type === 'command' && (
                                    <span className='text-green-400 font-medium'>{line.content}</span>
                                )}
                                {line.type === 'error' && <span className='text-red-400'>{line.content}</span>}
                                {line.type === 'info' && (
                                    <span className='text-blue-400'>
                                        [{line.timestamp}] {line.content}
                                    </span>
                                )}
                                {line.type === 'output' && <span className='text-gray-300'>{line.content}</span>}
                            </div>
                        ))}

                        {/* Loading indicator */}
                        {isLoading && (
                            <div className='flex items-center gap-2 text-yellow-400'>
                                <div className='animate-pulse'>●</div>
                                <span>{t('admin.dev.console.executing') || 'Executing command...'}</span>
                            </div>
                        )}
                    </div>

                    {/* Command Input */}
                    <div className='p-4 border border-border/50 bg-muted/30 rounded-xl'>
                        <div className='flex items-center gap-2'>
                            <span className='text-green-400 font-mono text-sm shrink-0'>{getPrompt()}</span>
                            <Input
                                ref={inputRef}
                                value={commandInput}
                                onChange={(e) => setCommandInput(e.target.value)}
                                className='bg-transparent border-none text-green-400 font-mono text-sm focus:ring-0 focus:border-none flex-1'
                                placeholder={t('admin.dev.console.enter_command') || 'Enter command...'}
                                disabled={isLoading}
                                autoComplete='off'
                                spellCheck={false}
                                onKeyDown={handleKeyDown}
                            />
                        </div>
                    </div>
                </div>
            </PageCard>

            {/* Quick Commands */}
            <PageCard title={t('admin.dev.console.quick_commands') || 'Quick Commands'}>
                <div className='grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2'>
                    {quickCommands.map((cmd) => (
                        <Button
                            key={cmd}
                            variant='outline'
                            size='sm'
                            className='text-xs'
                            disabled={isLoading}
                            onClick={() => {
                                setCommandInput(cmd);
                                executeCommand();
                            }}
                        >
                            {cmd}
                        </Button>
                    ))}
                </div>
            </PageCard>
        </div>
    );
}

// frontend/src/pages/admin/dev/Console.vue
<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, onUnmounted, nextTick } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useToast } from 'vue-toastification';

interface CommandResult {
    stdout: string;
    stderr: string;
    return_code: number;
    execution_time: number;
    command: string;
    working_directory: string;
    timestamp: string;
}

interface CommandResponse {
    success: boolean;
    data: CommandResult;
    message?: string;
}

interface SystemInfoResponse {
    success: boolean;
    data: {
        os: string;
        php_version: string;
        server_software: string;
        server_name: string;
        user: string;
        home: string;
        working_directory: string;
        disk_usage: {
            free: number;
            total: number;
            used: number;
            percentage: number;
        };
        memory_usage: Record<string, number>;
        uptime: string;
    };
    message?: string;
}

interface TerminalLine {
    id: string;
    type: 'command' | 'output' | 'error' | 'info';
    content: string;
    timestamp: string;
    command?: string;
    returnCode?: number;
    executionTime?: number;
}

const commandInput = ref('');
const currentDirectory = ref('');
const isLoading = ref(false);
const terminalLines = ref<TerminalLine[]>([]);
const systemInfo = ref<SystemInfoResponse['data'] | null>(null);
const showSystemInfo = ref(false);
const commandHistory = ref<string[]>([]);
const historyIndex = ref(-1);

const toast = useToast();

// Terminal colors and styling (removed unused function)

const getPrompt = (): string => {
    const user = systemInfo.value?.user || 'www-data';
    const dir = currentDirectory.value.replace(/^.*\//, '~');
    return `${user}@featherpanel:${dir}$`;
};

async function fetchSystemInfo() {
    try {
        const resp = await fetch('/api/admin/console/system-info');
        const text = await resp.text();

        // Check if response contains HTML error messages
        if (text.includes('<br />') || text.includes('<b>')) {
            console.error('Response contains HTML error messages:', text);
            toast.error('Server returned error messages. Check console for details.');
            return;
        }

        let json: SystemInfoResponse;
        try {
            json = JSON.parse(text);
        } catch {
            console.error('Failed to parse JSON response:', text);
            toast.error('Failed to parse server response. Check console for details.');
            return;
        }

        if (json.success) {
            systemInfo.value = json.data;
            currentDirectory.value = json.data.working_directory;
            addTerminalLine('info', `Connected to ${json.data.server_name} (${json.data.os})`);
            addTerminalLine('info', `PHP ${json.data.php_version} | User: ${json.data.user}`);
        } else {
            toast.error('Failed to fetch system info: ' + (json.message || 'Unknown error'));
        }
    } catch (e) {
        console.error('Failed to fetch system info:', e);
        toast.error('Failed to fetch system info: Network error');
    }
}

async function executeCommand() {
    if (!commandInput.value.trim()) return;

    const command = commandInput.value.trim();
    commandHistory.value.unshift(command);
    if (commandHistory.value.length > 100) {
        commandHistory.value = commandHistory.value.slice(0, 100);
    }
    historyIndex.value = -1;

    addTerminalLine('command', `${getPrompt()} ${command}`);
    commandInput.value = '';
    isLoading.value = true;

    try {
        const resp = await fetch('/api/admin/console/execute', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: new URLSearchParams({
                command: command,
                cwd: currentDirectory.value,
            }),
        });

        const text = await resp.text();

        // Check if response contains HTML error messages
        if (text.includes('<br />') || text.includes('<b>')) {
            console.error('Response contains HTML error messages:', text);
            addTerminalLine('error', 'Server returned error messages. Check browser console for details.');
            return;
        }

        let json: CommandResponse;
        try {
            json = JSON.parse(text);
        } catch {
            console.error('Failed to parse JSON response:', text);
            addTerminalLine('error', 'Failed to parse server response. Check browser console for details.');
            return;
        }

        if (json.success) {
            const result = json.data;

            // Update current directory if cd command was used
            if (command.startsWith('cd ')) {
                // Extract directory from cd command
                const newDir = command.substring(3).trim();
                if (newDir === '~' || newDir === '') {
                    currentDirectory.value = systemInfo.value?.home || '/var/www';
                } else if (newDir.startsWith('/')) {
                    currentDirectory.value = newDir;
                } else {
                    currentDirectory.value = currentDirectory.value + '/' + newDir;
                }
                currentDirectory.value = currentDirectory.value.replace(/\/+/g, '/');
            }

            // Display output
            if (result.stdout) {
                addTerminalLine('output', result.stdout);
            }
            if (result.stderr) {
                addTerminalLine('error', result.stderr);
            }

            // Show command result info
            addTerminalLine('info', `[${result.return_code}] ${result.execution_time}ms`);

            if (result.return_code !== 0 && !result.stderr) {
                toast.warning(`Command failed with exit code ${result.return_code}`);
            }
        } else {
            addTerminalLine('error', `Error: ${json.message || 'Unknown error'}`);
            toast.error('Command execution failed: ' + (json.message || 'Unknown error'));
        }
    } catch (e) {
        console.error('Failed to execute command:', e);
        addTerminalLine('error', `Network error: ${String(e)}`);
        toast.error('Failed to execute command: Network error');
    } finally {
        isLoading.value = false;
        scrollToBottom();
    }
}

function addTerminalLine(
    type: TerminalLine['type'],
    content: string,
    command?: string,
    returnCode?: number,
    executionTime?: number,
) {
    const line: TerminalLine = {
        id: Date.now() + '-' + Math.random(),
        type,
        content,
        timestamp: new Date().toLocaleTimeString(),
        command,
        returnCode,
        executionTime,
    };
    terminalLines.value.push(line);
}

function clearTerminal() {
    terminalLines.value = [];
    addTerminalLine('info', 'Terminal cleared');
}

function scrollToBottom() {
    nextTick(() => {
        const terminal = document.getElementById('terminal-output');
        if (terminal) {
            terminal.scrollTop = terminal.scrollHeight;
        }
    });
}

function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
        event.preventDefault();
        executeCommand();
    } else if (event.key === 'ArrowUp') {
        event.preventDefault();
        if (historyIndex.value < commandHistory.value.length - 1) {
            historyIndex.value++;
            commandInput.value = commandHistory.value[historyIndex.value] ?? '';
        }
    } else if (event.key === 'ArrowDown') {
        event.preventDefault();
        if (historyIndex.value > 0) {
            historyIndex.value--;
            commandInput.value = commandHistory.value[historyIndex.value] ?? '';
        } else if (historyIndex.value === 0) {
            historyIndex.value = -1;
            commandInput.value = '';
        }
    } else if (event.key === 'l' && event.ctrlKey) {
        event.preventDefault();
        clearTerminal();
    }
}

function formatBytes(bytes: number): string {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

function toggleSystemInfo() {
    showSystemInfo.value = !showSystemInfo.value;
}

onMounted(() => {
    fetchSystemInfo();
    addTerminalLine('info', 'FeatherPanel Console - Type "help" for available commands');
});

onUnmounted(() => {
    // Cleanup if needed
});
</script>

<template>
    <DashboardLayout
        :breadcrumbs="[
            { text: 'Dev', href: '/admin/dev' },
            { text: 'Console', isCurrent: true, href: '/admin/dev/console' },
        ]"
    >
        <div class="min-h-screen bg-background">
            <div class="p-6 space-y-6">
                <!-- Header -->
                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                    <div>
                        <h1 class="text-3xl font-bold text-foreground mb-1">Console</h1>
                        <p class="text-muted-foreground">Execute commands on the server</p>
                    </div>
                    <div class="flex items-center gap-2">
                        <Button variant="outline" @click="toggleSystemInfo">
                            {{ showSystemInfo ? 'Hide' : 'Show' }} System Info
                        </Button>
                        <Button variant="outline" @click="clearTerminal">Clear Terminal</Button>
                        <Button variant="outline" :disabled="isLoading" @click="fetchSystemInfo">Refresh</Button>
                    </div>
                </div>

                <!-- System Info Panel -->
                <Card v-if="showSystemInfo && systemInfo" class="p-4">
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div>
                            <h3 class="font-semibold mb-2">System</h3>
                            <div class="text-sm space-y-1">
                                <div><span class="text-muted-foreground">OS:</span> {{ systemInfo.os }}</div>
                                <div>
                                    <span class="text-muted-foreground">Server:</span> {{ systemInfo.server_software }}
                                </div>
                                <div><span class="text-muted-foreground">User:</span> {{ systemInfo.user }}</div>
                            </div>
                        </div>
                        <div>
                            <h3 class="font-semibold mb-2">Runtime</h3>
                            <div class="text-sm space-y-1">
                                <div><span class="text-muted-foreground">PHP:</span> {{ systemInfo.php_version }}</div>
                                <div><span class="text-muted-foreground">Uptime:</span> {{ systemInfo.uptime }}</div>
                            </div>
                        </div>
                        <div>
                            <h3 class="font-semibold mb-2">Disk Usage</h3>
                            <div class="text-sm space-y-1">
                                <div>
                                    <span class="text-muted-foreground">Used:</span>
                                    {{ formatBytes(systemInfo.disk_usage.used) }}
                                </div>
                                <div>
                                    <span class="text-muted-foreground">Free:</span>
                                    {{ formatBytes(systemInfo.disk_usage.free) }}
                                </div>
                                <div>
                                    <span class="text-muted-foreground">Usage:</span>
                                    {{ systemInfo.disk_usage.percentage }}%
                                </div>
                            </div>
                        </div>
                    </div>
                </Card>

                <!-- Terminal -->
                <Card class="p-0 overflow-hidden">
                    <div class="p-4 border-b">
                        <div class="font-semibold">Terminal</div>
                        <div class="text-xs text-muted-foreground mt-1">
                            Use Ctrl+Up/Down for command history, Ctrl+L to clear
                        </div>
                    </div>

                    <!-- Terminal Output -->
                    <div
                        id="terminal-output"
                        class="h-96 bg-black text-green-400 p-4 overflow-auto font-mono text-sm"
                        style="font-family: 'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace"
                    >
                        <div v-for="line in terminalLines" :key="line.id" class="mb-1">
                            <span v-if="line.type === 'command'" class="text-green-400 font-medium">
                                {{ line.content }}
                            </span>
                            <span v-else-if="line.type === 'error'" class="text-red-400">
                                {{ line.content }}
                            </span>
                            <span v-else-if="line.type === 'info'" class="text-blue-400">
                                [{{ line.timestamp }}] {{ line.content }}
                            </span>
                            <span v-else class="text-gray-300">
                                {{ line.content }}
                            </span>
                        </div>

                        <!-- Loading indicator -->
                        <div v-if="isLoading" class="flex items-center gap-2 text-yellow-400">
                            <div class="animate-pulse">●</div>
                            <span>Executing command...</span>
                        </div>
                    </div>

                    <!-- Command Input -->
                    <div class="p-4 border-t bg-gray-900">
                        <div class="flex items-center gap-2">
                            <span class="text-green-400 font-mono text-sm flex-shrink-0">{{ getPrompt() }}</span>
                            <Input
                                v-model="commandInput"
                                class="bg-transparent border-none text-green-400 font-mono text-sm focus:ring-0 focus:border-none flex-1"
                                placeholder="Enter command..."
                                :disabled="isLoading"
                                autocomplete="off"
                                spellcheck="false"
                                @keydown="handleKeydown"
                            />
                        </div>
                    </div>
                </Card>

                <!-- Quick Commands -->
                <Card class="p-4">
                    <div class="font-semibold mb-3">Quick Commands</div>
                    <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2">
                        <Button
                            v-for="cmd in [
                                'ls -la',
                                'pwd',
                                'whoami',
                                'date',
                                'df -h',
                                'free -h',
                                'ps aux',
                                'top',
                                'git status',
                                'composer --version',
                                'npm --version',
                                'php --version',
                            ]"
                            :key="cmd"
                            variant="outline"
                            size="sm"
                            class="text-xs"
                            :disabled="isLoading"
                            @click="
                                commandInput = cmd;
                                executeCommand();
                            "
                        >
                            {{ cmd }}
                        </Button>
                    </div>
                </Card>
            </div>
        </div>
    </DashboardLayout>
</template>

<style scoped>
/* Terminal styling */
#terminal-output {
    scrollbar-width: thin;
    scrollbar-color: #4a5568 #1a202c;
}

#terminal-output::-webkit-scrollbar {
    width: 8px;
}

#terminal-output::-webkit-scrollbar-track {
    background: #1a202c;
}

#terminal-output::-webkit-scrollbar-thumb {
    background: #4a5568;
    border-radius: 4px;
}

#terminal-output::-webkit-scrollbar-thumb:hover {
    background: #718096;
}

/* Command input styling */
:deep(input) {
    font-family: 'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace !important;
}

/* Blinking cursor effect */
:deep(input:focus) {
    box-shadow: none !important;
    border-color: transparent !important;
}
</style>
