// frontendv2/src/app/(docs)/docs/events/console/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
'use client';

import Link from 'next/link';
import { ArrowLeft, Zap, Code } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

const categoryData = {
    name: "Console",
    events: [
  {
    "method": "onCommandExecuted",
    "name": "featherpanel:admin:console:command:executed",
    "callback": "string command, array execution data.",
    "category": "Console",
    "actualData": [
      "command",
      "executed_by",
      "execution_time",
      "return_code",
      "working_directory"
    ],
    "sourceFiles": [
      "backend/app/Controllers/Admin/ConsoleController.php"
    ],
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\ConsoleEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(ConsoleEvent::onCommandExecuted(), function ($command, $executedBy, $executionTime, $returnCode, $workingDirectory) {\n        // Handle featherpanel:admin:console:command:executed\n        // Data keys: command, executed_by, execution_time, return_code, working_directory\n    });\n}"
  },
  {
    "method": "onConsoleError",
    "name": "featherpanel:admin:console:error",
    "callback": "string error message, array context.",
    "category": "Console",
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\ConsoleEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(ConsoleEvent::onConsoleError(), function ($message, $context) {\n        // Handle featherpanel:admin:console:error\n        // Parameters: string error message, array context.\n    });\n}"
  },
  {
    "method": "onSystemInfoRetrieved",
    "name": "featherpanel:admin:console:system_info:retrieved",
    "callback": "array system info.",
    "category": "Console",
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\ConsoleEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(ConsoleEvent::onSystemInfoRetrieved(), function ($info) {\n        // Handle featherpanel:admin:console:system_info:retrieved\n        // Parameters: array system info.\n    });\n}"
  }
]
};

export default function CategoryEventsPage() {
    // Helper to unescape JSON-escaped strings
    const unescapeCode = (str) => {
        // Replace double backslashes (escaped in JSON) with single backslash
        // Replace escaped newlines with actual newlines
        return str.replace(/\\\\/g, '\\').replace(/\\n/g, '\n');
    };
    
    return (
        <div className='min-h-screen bg-background'>
            <div className='container mx-auto px-4 py-16 max-w-6xl'>
                <Link href='/docs/events'>
                    <Button variant='ghost' className='mb-8 -ml-4'>
                        <ArrowLeft className='w-4 h-4 mr-2' />
                        Back to Events
                    </Button>
                </Link>

                <div className='mb-12 space-y-4'>
                    <div className='flex items-center gap-3'>
                        <div className='p-3 rounded-xl bg-primary/10 border border-primary/20 backdrop-blur-sm'>
                            <Zap className='w-6 h-6 text-primary' />
                        </div>
                        <div>
                            <h1 className='text-4xl font-black tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent'>
                                {categoryData.name}
                            </h1>
                            <p className='text-muted-foreground mt-1'>
                                {categoryData.events.length} event{categoryData.events.length !== 1 ? 's' : ''} in this category
                            </p>
                        </div>
                    </div>
                </div>

                <div className='space-y-4'>
                    {categoryData.events.map((event) => (
                        <Card key={event.name} className='border-border/50 bg-card/50 backdrop-blur-sm hover:bg-card/80 transition-colors'>
                            <CardHeader>
                                <div className='flex items-start justify-between gap-4 flex-wrap'>
                                    <div className='flex-1 min-w-0'>
                                        <div className='flex items-center gap-2 mb-2 flex-wrap'>
                                            <Code className='w-4 h-4 text-primary flex-shrink-0' />
                                            <CardTitle className='text-lg font-mono text-foreground break-all'>
                                                {event.name}
                                            </CardTitle>
                                        </div>
                                        <CardDescription className='text-muted-foreground mb-3'>
                                            <span className='font-semibold'>Callback parameters:</span> {event.callback}
                                        </CardDescription>
                                    </div>
                                    <Badge variant='outline' className='text-xs font-mono bg-muted/30 border-border/50 text-foreground/80 flex-shrink-0'>
                                        {event.method}
                                    </Badge>
                                </div>
                            </CardHeader>
                            <CardContent className='space-y-4'>
                                {event.actualData && event.actualData.length > 0 && (
                                    <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                        <h4 className='text-sm font-semibold text-foreground mb-2'>Event Data Structure</h4>
                                        <p className='text-xs text-muted-foreground mb-3'>
                                            This event receives the following data when emitted:
                                        </p>
                                        <div className='flex flex-wrap gap-2'>
                                            {event.actualData.map((key) => (
                                                <Badge 
                                                    key={key} 
                                                    variant='outline' 
                                                    className='text-xs font-mono bg-muted/50 border-border/50 text-foreground/80'
                                                >
                                                    {key}
                                                </Badge>
                                            ))}
                                        </div>
                                        {event.sourceFiles && event.sourceFiles.length > 0 && (
                                            <div className='mt-3 pt-3 border-t border-border/30'>
                                                <p className='text-xs text-muted-foreground mb-1'>Emitted from:</p>
                                                <div className='space-y-1'>
                                                    {event.sourceFiles.slice(0, 2).map((file) => (
                                                        <code key={file} className='text-xs text-muted-foreground block truncate'>
                                                            {file}
                                                        </code>
                                                    ))}
                                                    {event.sourceFiles.length > 2 && (
                                                        <p className='text-xs text-muted-foreground italic'>
                                                            +{event.sourceFiles.length - 2} more location{event.sourceFiles.length - 2 !== 1 ? 's' : ''}
                                                        </p>
                                                    )}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                )}
                                <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                    <h4 className='text-sm font-semibold text-foreground mb-2'>Usage Example</h4>
                                    <pre className='p-3 rounded-lg bg-muted/50 border border-border/50 overflow-x-auto'>
                                        <code className='text-xs font-mono text-foreground'>
{unescapeCode(event.exampleCode)}
                                        </code>
                                    </pre>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </div>
    );
}

// frontend/src/pages/admin/dev/Console.vue
<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, onUnmounted, nextTick } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useToast } from 'vue-toastification';
import { formatBytes } from '@/lib/format';

interface CommandResult {
    stdout: string;
    stderr: string;
    return_code: number;
    execution_time: number;
    command: string;
    working_directory: string;
    timestamp: string;
}

interface CommandResponse {
    success: boolean;
    data: CommandResult;
    message?: string;
}

interface SystemInfoResponse {
    success: boolean;
    data: {
        os: string;
        php_version: string;
        server_software: string;
        server_name: string;
        user: string;
        home: string;
        working_directory: string;
        disk_usage: {
            free: number;
            total: number;
            used: number;
            percentage: number;
        };
        memory_usage: Record<string, number>;
        uptime: string;
    };
    message?: string;
}

interface TerminalLine {
    id: string;
    type: 'command' | 'output' | 'error' | 'info';
    content: string;
    timestamp: string;
    command?: string;
    returnCode?: number;
    executionTime?: number;
}

const commandInput = ref('');
const currentDirectory = ref('');
const isLoading = ref(false);
const terminalLines = ref<TerminalLine[]>([]);
const systemInfo = ref<SystemInfoResponse['data'] | null>(null);
const showSystemInfo = ref(false);
const commandHistory = ref<string[]>([]);
const historyIndex = ref(-1);

const toast = useToast();

// Terminal colors and styling (removed unused function)

const getPrompt = (): string => {
    const user = systemInfo.value?.user || 'www-data';
    const dir = currentDirectory.value.replace(/^.*\//, '~');
    return `${user}@featherpanel:${dir}$`;
};

async function fetchSystemInfo() {
    try {
        const resp = await fetch('/api/admin/console/system-info');
        const text = await resp.text();

        // Check if response contains HTML error messages
        if (text.includes('<br />') || text.includes('<b>')) {
            console.error('Response contains HTML error messages:', text);
            toast.error('Server returned error messages. Check console for details.');
            return;
        }

        let json: SystemInfoResponse;
        try {
            json = JSON.parse(text);
        } catch {
            console.error('Failed to parse JSON response:', text);
            toast.error('Failed to parse server response. Check console for details.');
            return;
        }

        if (json.success) {
            systemInfo.value = json.data;
            currentDirectory.value = json.data.working_directory;
            addTerminalLine('info', `Connected to ${json.data.server_name} (${json.data.os})`);
            addTerminalLine('info', `PHP ${json.data.php_version} | User: ${json.data.user}`);
        } else {
            toast.error('Failed to fetch system info: ' + (json.message || 'Unknown error'));
        }
    } catch (e) {
        console.error('Failed to fetch system info:', e);
        toast.error('Failed to fetch system info: Network error');
    }
}

async function executeCommand() {
    if (!commandInput.value.trim()) return;

    const command = commandInput.value.trim();
    commandHistory.value.unshift(command);
    if (commandHistory.value.length > 100) {
        commandHistory.value = commandHistory.value.slice(0, 100);
    }
    historyIndex.value = -1;

    addTerminalLine('command', `${getPrompt()} ${command}`);
    commandInput.value = '';
    isLoading.value = true;

    try {
        const resp = await fetch('/api/admin/console/execute', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
            },
            body: new URLSearchParams({
                command: command,
                cwd: currentDirectory.value,
            }),
        });

        const text = await resp.text();

        // Check if response contains HTML error messages
        if (text.includes('<br />') || text.includes('<b>')) {
            console.error('Response contains HTML error messages:', text);
            addTerminalLine('error', 'Server returned error messages. Check browser console for details.');
            return;
        }

        let json: CommandResponse;
        try {
            json = JSON.parse(text);
        } catch {
            console.error('Failed to parse JSON response:', text);
            addTerminalLine('error', 'Failed to parse server response. Check browser console for details.');
            return;
        }

        if (json.success) {
            const result = json.data;

            // Update current directory if cd command was used
            if (command.startsWith('cd ')) {
                // Extract directory from cd command
                const newDir = command.substring(3).trim();
                if (newDir === '~' || newDir === '') {
                    currentDirectory.value = systemInfo.value?.home || '/var/www';
                } else if (newDir.startsWith('/')) {
                    currentDirectory.value = newDir;
                } else {
                    currentDirectory.value = currentDirectory.value + '/' + newDir;
                }
                currentDirectory.value = currentDirectory.value.replace(/\/+/g, '/');
            }

            // Display output
            if (result.stdout) {
                addTerminalLine('output', result.stdout);
            }
            if (result.stderr) {
                addTerminalLine('error', result.stderr);
            }

            // Show command result info
            addTerminalLine('info', `[${result.return_code}] ${result.execution_time}ms`);

            if (result.return_code !== 0 && !result.stderr) {
                toast.warning(`Command failed with exit code ${result.return_code}`);
            }
        } else {
            addTerminalLine('error', `Error: ${json.message || 'Unknown error'}`);
            toast.error('Command execution failed: ' + (json.message || 'Unknown error'));
        }
    } catch (e) {
        console.error('Failed to execute command:', e);
        addTerminalLine('error', `Network error: ${String(e)}`);
        toast.error('Failed to execute command: Network error');
    } finally {
        isLoading.value = false;
        scrollToBottom();
    }
}

function addTerminalLine(
    type: TerminalLine['type'],
    content: string,
    command?: string,
    returnCode?: number,
    executionTime?: number,
) {
    const line: TerminalLine = {
        id: Date.now() + '-' + Math.random(),
        type,
        content,
        timestamp: new Date().toLocaleTimeString(),
        command,
        returnCode,
        executionTime,
    };
    terminalLines.value.push(line);
}

function clearTerminal() {
    terminalLines.value = [];
    addTerminalLine('info', 'Terminal cleared');
}

function scrollToBottom() {
    nextTick(() => {
        const terminal = document.getElementById('terminal-output');
        if (terminal) {
            terminal.scrollTop = terminal.scrollHeight;
        }
    });
}

function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
        event.preventDefault();
        executeCommand();
    } else if (event.key === 'ArrowUp') {
        event.preventDefault();
        if (historyIndex.value < commandHistory.value.length - 1) {
            historyIndex.value++;
            commandInput.value = commandHistory.value[historyIndex.value] ?? '';
        }
    } else if (event.key === 'ArrowDown') {
        event.preventDefault();
        if (historyIndex.value > 0) {
            historyIndex.value--;
            commandInput.value = commandHistory.value[historyIndex.value] ?? '';
        } else if (historyIndex.value === 0) {
            historyIndex.value = -1;
            commandInput.value = '';
        }
    } else if (event.key === 'l' && event.ctrlKey) {
        event.preventDefault();
        clearTerminal();
    }
}


function toggleSystemInfo() {
    showSystemInfo.value = !showSystemInfo.value;
}

onMounted(() => {
    fetchSystemInfo();
    addTerminalLine('info', 'FeatherPanel Console - Type "help" for available commands');
});

onUnmounted(() => {
    // Cleanup if needed
});
</script>

<template>
    <DashboardLayout
        :breadcrumbs="[
            { text: 'Dev', href: '/admin/dev' },
            { text: 'Console', isCurrent: true, href: '/admin/dev/console' },
        ]"
    >
        <div class="min-h-screen bg-background">
            <div class="p-6 space-y-6">
                <!-- Header -->
                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                    <div>
                        <h1 class="text-3xl font-bold text-foreground mb-1">Console</h1>
                        <p class="text-muted-foreground">Execute commands on the server</p>
                    </div>
                    <div class="flex items-center gap-2">
                        <Button variant="outline" data-umami-event="Toggle system info" @click="toggleSystemInfo">
                            {{ showSystemInfo ? 'Hide' : 'Show' }} System Info
                        </Button>
                        <Button variant="outline" data-umami-event="Clear terminal" @click="clearTerminal"
                            >Clear Terminal</Button
                        >
                        <Button
                            variant="outline"
                            :disabled="isLoading"
                            data-umami-event="Refresh system info"
                            @click="fetchSystemInfo"
                            >Refresh</Button
                        >
                    </div>
                </div>

                <!-- System Info Panel -->
                <Card v-if="showSystemInfo && systemInfo" class="p-4">
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                        <div>
                            <h3 class="font-semibold mb-2">System</h3>
                            <div class="text-sm space-y-1">
                                <div><span class="text-muted-foreground">OS:</span> {{ systemInfo.os }}</div>
                                <div>
                                    <span class="text-muted-foreground">Server:</span> {{ systemInfo.server_software }}
                                </div>
                                <div><span class="text-muted-foreground">User:</span> {{ systemInfo.user }}</div>
                            </div>
                        </div>
                        <div>
                            <h3 class="font-semibold mb-2">Runtime</h3>
                            <div class="text-sm space-y-1">
                                <div><span class="text-muted-foreground">PHP:</span> {{ systemInfo.php_version }}</div>
                                <div><span class="text-muted-foreground">Uptime:</span> {{ systemInfo.uptime }}</div>
                            </div>
                        </div>
                        <div>
                            <h3 class="font-semibold mb-2">Disk Usage</h3>
                            <div class="text-sm space-y-1">
                                <div>
                                    <span class="text-muted-foreground">Used:</span>
                                    {{ formatBytes(systemInfo.disk_usage.used) }}
                                </div>
                                <div>
                                    <span class="text-muted-foreground">Free:</span>
                                    {{ formatBytes(systemInfo.disk_usage.free) }}
                                </div>
                                <div>
                                    <span class="text-muted-foreground">Usage:</span>
                                    {{ systemInfo.disk_usage.percentage }}%
                                </div>
                            </div>
                        </div>
                    </div>
                </Card>

                <!-- Terminal -->
                <Card class="p-0 overflow-hidden">
                    <div class="p-4 border-b">
                        <div class="font-semibold">Terminal</div>
                        <div class="text-xs text-muted-foreground mt-1">
                            Use Ctrl+Up/Down for command history, Ctrl+L to clear
                        </div>
                    </div>

                    <!-- Terminal Output -->
                    <div
                        id="terminal-output"
                        class="h-96 bg-black text-green-400 p-4 overflow-auto font-mono text-sm"
                        style="font-family: 'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace"
                    >
                        <div v-for="line in terminalLines" :key="line.id" class="mb-1">
                            <span v-if="line.type === 'command'" class="text-green-400 font-medium">
                                {{ line.content }}
                            </span>
                            <span v-else-if="line.type === 'error'" class="text-red-400">
                                {{ line.content }}
                            </span>
                            <span v-else-if="line.type === 'info'" class="text-blue-400">
                                [{{ line.timestamp }}] {{ line.content }}
                            </span>
                            <span v-else class="text-gray-300">
                                {{ line.content }}
                            </span>
                        </div>

                        <!-- Loading indicator -->
                        <div v-if="isLoading" class="flex items-center gap-2 text-yellow-400">
                            <div class="animate-pulse">●</div>
                            <span>Executing command...</span>
                        </div>
                    </div>

                    <!-- Command Input -->
                    <div class="p-4 border-t bg-gray-900">
                        <div class="flex items-center gap-2">
                            <span class="text-green-400 font-mono text-sm shrink-0">{{ getPrompt() }}</span>
                            <Input
                                v-model="commandInput"
                                class="bg-transparent border-none text-green-400 font-mono text-sm focus:ring-0 focus:border-none flex-1"
                                placeholder="Enter command..."
                                :disabled="isLoading"
                                autocomplete="off"
                                spellcheck="false"
                                @keydown="handleKeydown"
                            />
                        </div>
                    </div>
                </Card>

                <!-- Quick Commands -->
                <Card class="p-4">
                    <div class="font-semibold mb-3">Quick Commands</div>
                    <div class="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-6 gap-2">
                        <Button
                            v-for="cmd in [
                                'ls -la',
                                'pwd',
                                'whoami',
                                'date',
                                'df -h',
                                'free -h',
                                'ps aux',
                                'top',
                                'git status',
                                'composer --version',
                                'npm --version',
                                'php --version',
                            ]"
                            :key="cmd"
                            variant="outline"
                            size="sm"
                            class="text-xs"
                            :disabled="isLoading"
                            @click="
                                commandInput = cmd;
                                executeCommand();
                            "
                        >
                            {{ cmd }}
                        </Button>
                    </div>
                </Card>
            </div>
        </div>
    </DashboardLayout>
</template>

<style scoped>
/* Terminal styling */
#terminal-output {
    scrollbar-width: thin;
    scrollbar-color: #4a5568 #1a202c;
}

#terminal-output::-webkit-scrollbar {
    width: 8px;
}

#terminal-output::-webkit-scrollbar-track {
    background: #1a202c;
}

#terminal-output::-webkit-scrollbar-thumb {
    background: #4a5568;
    border-radius: 4px;
}

#terminal-output::-webkit-scrollbar-thumb:hover {
    background: #718096;
}

/* Command input styling */
:deep(input) {
    font-family: 'JetBrains Mono', 'Fira Code', 'Monaco', 'Consolas', monospace !important;
}

/* Blinking cursor effect */
:deep(input:focus) {
    box-shadow: none !important;
    border-color: transparent !important;
}
</style>
