// frontendv2/src/app/(docs)/icanhasfeatherpanel/events/log-viewer/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
'use client';

import Link from 'next/link';
import { ArrowLeft, Zap, Code } from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

const categoryData = {
    name: "LogViewer",
    events: [
  {
    "method": "onLogCleared",
    "name": "featherpanel:admin:log_viewer:cleared",
    "callback": "string log type, string file name.",
    "category": "LogViewer",
    "actualData": [
      "cleared_by",
      "log_file",
      "log_type"
    ],
    "sourceFiles": [
      "backend/app/Controllers/Admin/LogViewerController.php"
    ],
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\LogViewerEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(LogViewerEvent::onLogCleared(), function ($clearedBy, $logFile, $logType) {\n        // Handle featherpanel:admin:log_viewer:cleared\n        // Data keys: cleared_by, log_file, log_type\n    });\n}"
  },
  {
    "method": "onLogsUploaded",
    "name": "featherpanel:admin:log_viewer:uploaded",
    "callback": "array upload results.",
    "category": "LogViewer",
    "actualData": [
      "results",
      "uploaded_by"
    ],
    "sourceFiles": [
      "backend/app/Controllers/Admin/LogViewerController.php"
    ],
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\LogViewerEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(LogViewerEvent::onLogsUploaded(), function ($results, $uploadedBy) {\n        // Handle featherpanel:admin:log_viewer:uploaded\n        // Data keys: results, uploaded_by\n    });\n}"
  },
  {
    "method": "onLogViewed",
    "name": "featherpanel:admin:log_viewer:viewed",
    "callback": "string log type, string file name.",
    "category": "LogViewer",
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\LogViewerEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(LogViewerEvent::onLogViewed(), function ($type, $name) {\n        // Handle featherpanel:admin:log_viewer:viewed\n        // Parameters: string log type, string file name.\n    });\n}"
  },
  {
    "method": "onLogViewerError",
    "name": "featherpanel:admin:log_viewer:error",
    "callback": "string error message, array context.",
    "category": "LogViewer",
    "exampleCode": "use App\\Plugins\\PluginEvents;\nuse App\\Plugins\\Events\\Events\\LogViewerEvent;\n\npublic static function processEvents(PluginEvents $evt): void\n{\n    $evt->on(LogViewerEvent::onLogViewerError(), function ($message, $context) {\n        // Handle featherpanel:admin:log_viewer:error\n        // Parameters: string error message, array context.\n    });\n}"
  }
]
};

export default function CategoryEventsPage() {
    // Helper to unescape JSON-escaped strings
    const unescapeCode = (str) => {
        // Replace double backslashes (escaped in JSON) with single backslash
        // Replace escaped newlines with actual newlines
        return str.replace(/\\\\/g, '\\').replace(/\\n/g, '\n');
    };
    
    return (
        <div className='min-h-screen bg-background'>
            <div className='container mx-auto px-4 py-16 max-w-6xl'>
                <Link href='/icanhasfeatherpanel/events'>
                    <Button variant='ghost' className='mb-8 -ml-4'>
                        <ArrowLeft className='w-4 h-4 mr-2' />
                        Back to Events
                    </Button>
                </Link>

                <div className='mb-12 space-y-4'>
                    <div className='flex items-center gap-3'>
                        <div className='p-3 rounded-xl bg-primary/10 border border-primary/20 backdrop-blur-sm'>
                            <Zap className='w-6 h-6 text-primary' />
                        </div>
                        <div>
                            <h1 className='text-4xl font-black tracking-tight bg-gradient-to-r from-foreground to-foreground/70 bg-clip-text text-transparent'>
                                {categoryData.name}
                            </h1>
                            <p className='text-muted-foreground mt-1'>
                                {categoryData.events.length} event{categoryData.events.length !== 1 ? 's' : ''} in this category
                            </p>
                        </div>
                    </div>
                </div>

                <div className='space-y-4'>
                    {categoryData.events.map((event) => (
                        <Card key={event.name} className='border-border/50 bg-card/50 backdrop-blur-sm hover:bg-card/80 transition-colors'>
                            <CardHeader>
                                <div className='flex items-start justify-between gap-4 flex-wrap'>
                                    <div className='flex-1 min-w-0'>
                                        <div className='flex items-center gap-2 mb-2 flex-wrap'>
                                            <Code className='w-4 h-4 text-primary flex-shrink-0' />
                                            <CardTitle className='text-lg font-mono text-foreground break-all'>
                                                {event.name}
                                            </CardTitle>
                                        </div>
                                        <CardDescription className='text-muted-foreground mb-3'>
                                            <span className='font-semibold'>Callback parameters:</span> {event.callback}
                                        </CardDescription>
                                    </div>
                                    <Badge variant='outline' className='text-xs font-mono bg-muted/30 border-border/50 text-foreground/80 flex-shrink-0'>
                                        {event.method}
                                    </Badge>
                                </div>
                            </CardHeader>
                            <CardContent className='space-y-4'>
                                {event.actualData && event.actualData.length > 0 && (
                                    <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                        <h4 className='text-sm font-semibold text-foreground mb-2'>Event Data Structure</h4>
                                        <p className='text-xs text-muted-foreground mb-3'>
                                            This event receives the following data when emitted:
                                        </p>
                                        <div className='flex flex-wrap gap-2'>
                                            {event.actualData.map((key) => (
                                                <Badge 
                                                    key={key} 
                                                    variant='outline' 
                                                    className='text-xs font-mono bg-muted/50 border-border/50 text-foreground/80'
                                                >
                                                    {key}
                                                </Badge>
                                            ))}
                                        </div>
                                        {event.sourceFiles && event.sourceFiles.length > 0 && (
                                            <div className='mt-3 pt-3 border-t border-border/30'>
                                                <p className='text-xs text-muted-foreground mb-1'>Emitted from:</p>
                                                <div className='space-y-1'>
                                                    {event.sourceFiles.slice(0, 2).map((file) => (
                                                        <code key={file} className='text-xs text-muted-foreground block truncate'>
                                                            {file}
                                                        </code>
                                                    ))}
                                                    {event.sourceFiles.length > 2 && (
                                                        <p className='text-xs text-muted-foreground italic'>
                                                            +{event.sourceFiles.length - 2} more location{event.sourceFiles.length - 2 !== 1 ? 's' : ''}
                                                        </p>
                                                    )}
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                )}
                                <div className='p-4 rounded-lg bg-muted/30 border border-border/50 backdrop-blur-sm'>
                                    <h4 className='text-sm font-semibold text-foreground mb-2'>Usage Example</h4>
                                    <pre className='p-3 rounded-lg bg-muted/50 border border-border/50 overflow-x-auto'>
                                        <code className='text-xs font-mono text-foreground'>
{unescapeCode(event.exampleCode)}
                                        </code>
                                    </pre>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </div>
        </div>
    );
}

// frontend/src/pages/admin/dev/LogViewer.vue
<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, onUnmounted, nextTick } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';

interface LogFile {
    name: string;
    size: number;
    modified: number;
    type: string;
}

interface LogResponse {
    success: boolean;
    data: {
        logs: string;
        file: string;
        type: string;
        lines_count: number;
    };
}

interface LogFilesResponse {
    success: boolean;
    data: {
        files: LogFile[];
    };
}

const loading = ref(false);
const logs = ref('');
const currentLogType = ref('app');
const lines = ref(100);
const logFiles = ref<LogFile[]>([]);
const autoRefresh = ref(false);
const refreshInterval = ref<ReturnType<typeof setInterval> | null>(null);
const logsContainer = ref<HTMLElement | null>(null);

async function fetchLogFiles() {
    try {
        const resp = await fetch('/api/admin/log-viewer/files');
        const json: LogFilesResponse = await resp.json();
        if (json.success) {
            logFiles.value = json.data.files;
        }
    } catch (e) {
        console.error('Failed to fetch log files:', e);
    }
}

async function fetchLogs() {
    loading.value = true;
    try {
        const params = new URLSearchParams({
            type: currentLogType.value,
            lines: lines.value.toString(),
        });
        const resp = await fetch(`/api/admin/log-viewer/get?${params}`);
        const json: LogResponse = await resp.json();
        if (json.success) {
            logs.value = json.data.logs;
            // Scroll to bottom after logs are updated
            nextTick(() => {
                scrollToBottom();
            });
        }
    } catch (e) {
        console.error('Failed to fetch logs:', e);
    } finally {
        loading.value = false;
    }
}

async function clearLogs() {
    try {
        const resp = await fetch('/api/admin/log-viewer/clear', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                type: currentLogType.value,
            }),
        });
        const json = await resp.json();
        if (json.success) {
            logs.value = '';
        }
    } catch (e) {
        console.error('Failed to clear logs:', e);
    }
}

function toggleAutoRefresh() {
    autoRefresh.value = !autoRefresh.value;

    if (autoRefresh.value) {
        refreshInterval.value = setInterval(() => {
            fetchLogs();
        }, 10000); // 10 seconds
    } else {
        if (refreshInterval.value) {
            clearInterval(refreshInterval.value);
            refreshInterval.value = null;
        }
    }
}

function formatFileSize(bytes: number): string {
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    if (bytes === 0) return '0 Bytes';
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round((bytes / Math.pow(1024, i)) * 100) / 100 + ' ' + sizes[i];
}

function formatDate(timestamp: number): string {
    return new Date(timestamp * 1000).toLocaleString();
}

function scrollToBottom() {
    if (logsContainer.value) {
        logsContainer.value.scrollTop = logsContainer.value.scrollHeight;
    }
}

onMounted(() => {
    fetchLogFiles();
    fetchLogs();
});

onUnmounted(() => {
    if (refreshInterval.value) {
        clearInterval(refreshInterval.value);
    }
});
</script>

<template>
    <DashboardLayout
        :breadcrumbs="[
            { text: 'Dev', href: '/admin/dev' },
            { text: 'Log Viewer', isCurrent: true, href: '/admin/dev/logs' },
        ]"
    >
        <div class="min-h-screen bg-background">
            <div class="p-6 space-y-6">
                <!-- Header -->
                <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                    <div>
                        <h1 class="text-3xl font-bold text-foreground mb-1">Log Viewer</h1>
                        <p class="text-muted-foreground">View and manage application logs</p>
                    </div>
                    <div class="flex items-center gap-2">
                        <Button variant="outline" :disabled="loading" @click="fetchLogs">Refresh</Button>
                        <Button
                            :variant="autoRefresh ? 'default' : 'outline'"
                            :disabled="loading"
                            @click="toggleAutoRefresh"
                        >
                            <span
                                v-if="autoRefresh"
                                class="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"
                            ></span>
                            {{ autoRefresh ? 'Stop Auto' : 'Auto Refresh' }}
                        </Button>
                        <Button variant="destructive" :disabled="loading" @click="clearLogs">Clear Logs</Button>
                    </div>
                </div>

                <!-- Controls -->
                <Card class="p-4">
                    <div class="flex flex-col md:flex-row gap-4 items-start md:items-center">
                        <div class="flex items-center gap-2">
                            <label class="text-sm font-medium">Log Type:</label>
                            <select v-model="currentLogType" class="px-3 py-1 border rounded" @change="fetchLogs">
                                <option value="app">App Logs</option>
                                <option value="web">Web Logs</option>
                            </select>
                        </div>
                        <div class="flex items-center gap-2">
                            <label class="text-sm font-medium">Lines:</label>
                            <select v-model="lines" class="px-3 py-1 border rounded" @change="fetchLogs">
                                <option value="50">50</option>
                                <option value="100">100</option>
                                <option value="200">200</option>
                                <option value="500">500</option>
                            </select>
                        </div>
                    </div>
                </Card>

                <!-- Loading -->
                <div v-if="loading" class="flex items-center justify-center py-12">
                    <div class="flex items-center gap-3">
                        <div
                            class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"
                        ></div>
                        <span class="text-muted-foreground">Loading logs...</span>
                    </div>
                </div>

                <!-- Log Files Info -->
                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    <Card v-for="file in logFiles" :key="file.name" class="p-4">
                        <div class="flex items-center justify-between mb-2">
                            <div class="font-semibold text-sm">{{ file.type.toUpperCase() }}</div>
                            <div class="text-xs text-muted-foreground">{{ formatFileSize(file.size) }}</div>
                        </div>
                        <div class="text-xs text-muted-foreground">
                            <div>{{ file.name }}</div>
                            <div>Modified: {{ formatDate(file.modified) }}</div>
                        </div>
                    </Card>
                </div>

                <!-- Logs Output -->
                <Card class="p-0 overflow-hidden">
                    <div class="p-4 flex items-center justify-between">
                        <div class="font-semibold">Logs Output</div>
                        <div class="flex items-center gap-2">
                            <span class="text-sm text-muted-foreground">{{ logs.split('\n').length }} lines</span>
                            <Button variant="outline" size="sm" @click="logs = ''">Clear</Button>
                        </div>
                    </div>
                    <pre
                        ref="logsContainer"
                        class="text-xs whitespace-pre-wrap bg-black text-green-300 p-4 min-h-[400px] max-h-[600px] overflow-auto"
                        >{{ logs || 'No logs available' }}</pre
                    >
                </Card>
            </div>
        </div>
    </DashboardLayout>
</template>

<style scoped>
.min-h-\[400px\] {
    min-height: 400px;
}
.max-h-\[600px\] {
    max-height: 600px;
}
</style>
