// frontend/src/pages/admin/Locations.vue
<template>
    <DashboardLayout :breadcrumbs="[{ text: 'Locations', isCurrent: true, href: '/admin/locations' }]">
        <div class="min-h-screen bg-background">
            <!-- Plugin Widgets: Top of Page -->
            <WidgetRenderer v-if="widgetsTopOfPage.length > 0" :widgets="widgetsTopOfPage" />

            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading locations...</span>
                </div>
            </div>

            <!-- Locations Table -->
            <div v-else class="p-6">
                <!-- Plugin Widgets: Before Table -->
                <WidgetRenderer v-if="widgetsBeforeTable.length > 0" :widgets="widgetsBeforeTable" />

                <TableComponent
                    title="Locations"
                    description="Manage all locations in your system."
                    :columns="tableColumns"
                    :data="locations"
                    :search-placeholder="'Search by name or country...'"
                    :server-side-pagination="true"
                    :total-records="pagination.total"
                    :total-pages="Math.ceil(pagination.total / pagination.pageSize)"
                    :current-page="pagination.page"
                    :has-next="pagination.hasNext"
                    :has-prev="pagination.hasPrev"
                    :from="pagination.from"
                    :to="pagination.to"
                    local-storage-key="featherpanel-locations-table-columns"
                    @search="handleSearch"
                    @page-change="changePage"
                >
                    <template #header-actions>
                        <Button
                            variant="outline"
                            size="sm"
                            data-umami-event="Create location"
                            @click="openCreateDrawer"
                        >
                            <Plus class="h-4 w-4 mr-2" />
                            Create Location
                        </Button>
                    </template>

                    <!-- Custom cell templates -->
                    <template #cell-actions="{ item }">
                        <div class="flex gap-2">
                            <Button
                                size="sm"
                                variant="outline"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="View location details"
                                data-umami-event="View location"
                                :data-umami-event-location="(item as Location).name"
                                @click="onView(item as Location)"
                            >
                                <Eye :size="16" />
                            </Button>
                            <Button
                                size="sm"
                                variant="secondary"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="Edit location"
                                data-umami-event="Edit location"
                                :data-umami-event-location="(item as Location).name"
                                @click="onEdit(item as Location)"
                            >
                                <Pencil :size="16" />
                            </Button>
                            <Button
                                size="sm"
                                variant="secondary"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="View location nodes"
                                data-umami-event="View location nodes"
                                :data-umami-event-location="(item as Location).name"
                                @click="onViewNodes(item as Location)"
                            >
                                <Server :size="16" />
                            </Button>
                            <template v-if="confirmDeleteRow === (item as Location).id">
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    :loading="deleting"
                                    title="Confirm deletion"
                                    data-umami-event="Confirm delete location"
                                    :data-umami-event-location="(item as Location).name"
                                    @click="confirmDelete(item as Location)"
                                >
                                    Confirm Delete
                                </Button>
                                <Button
                                    size="sm"
                                    variant="outline"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    :disabled="deleting"
                                    title="Cancel deletion"
                                    @click="onCancelDelete"
                                >
                                    Cancel
                                </Button>
                            </template>
                            <template v-else>
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    title="Delete location"
                                    data-umami-event="Delete location"
                                    :data-umami-event-location="(item as Location).name"
                                    @click="onDelete(item as Location)"
                                >
                                    <Trash2 :size="16" />
                                </Button>
                            </template>
                        </div>
                    </template>
                </TableComponent>

                <!-- Plugin Widgets: After Table -->
                <WidgetRenderer v-if="widgetsAfterTable.length > 0" :widgets="widgetsAfterTable" />

                <!-- Helpful info cards under the table -->
                <div class="mt-6 grid grid-cols-1 md:grid-cols-3 gap-4">
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <MapPin class="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">What are Locations?</div>
                                    <p>
                                        Locations group nodes by geography or purpose. Keep your infrastructure
                                        organized and easy to navigate across regions and data centers.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <Flag class="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Examples</div>
                                    <ul class="list-disc list-inside space-y-1">
                                        <li><b>USA</b>: nodes where Wings runs for US servers</li>
                                        <li><b>Romania</b>: nodes where Romanian servers run (or other workloads)</li>
                                    </ul>
                                    <p class="mt-2">
                                        Use specific names like <b>USA-East</b>, <b>USA-West</b>, or
                                        <b>Romania-Bucharest</b> for clarity.
                                    </p>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                    <Card>
                        <CardContent>
                            <div class="p-4 flex items-start gap-3 text-sm text-muted-foreground">
                                <Rocket class="h-5 w-5 text-muted-foreground shrink-0 mt-0.5" />
                                <div>
                                    <div class="font-semibold text-foreground mb-1">Getting started</div>
                                    <ol class="list-decimal list-inside space-y-1">
                                        <li>Click <b>Create Location</b> above to add your first location.</li>
                                        <li>After creating, a <b>Nodes</b> button appears next to row actions.</li>
                                        <li>Click <b>Nodes</b> to add and manage nodes for that location.</li>
                                    </ol>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                </div>

                <!-- Plugin Widgets: After Help Cards -->
                <WidgetRenderer v-if="widgetsAfterHelpCards.length > 0" :widgets="widgetsAfterHelpCards" />
            </div>

            <!-- Plugin Widgets: Bottom of Page -->
            <WidgetRenderer v-if="widgetsBottomOfPage.length > 0" :widgets="widgetsBottomOfPage" />
        </div>
    </DashboardLayout>

    <!-- View Drawer -->
    <Drawer
        class="w-full"
        :open="viewing"
        @update:open="
            (val: boolean) => {
                if (!val) closeView();
            }
        "
    >
        <DrawerContent v-if="selectedLocation">
            <DrawerHeader>
                <DrawerTitle>Location Info</DrawerTitle>
                <DrawerDescription>Viewing details for location: {{ selectedLocation.name }}</DrawerDescription>
            </DrawerHeader>
            <div class="px-6 pt-6 space-y-2">
                <div><b>Name:</b> {{ selectedLocation.name }}</div>
                <div><b>Description:</b> {{ selectedLocation.description || '-' }}</div>
                <div><b>Created At:</b> {{ selectedLocation.created_at }}</div>
                <div><b>Updated At:</b> {{ selectedLocation.updated_at }}</div>
            </div>
            <div class="p-4 flex justify-end">
                <DrawerClose as-child>
                    <Button variant="outline" @click="closeView">Close</Button>
                </DrawerClose>
            </div>
        </DrawerContent>
    </Drawer>

    <!-- Edit Drawer -->
    <Drawer
        :open="editDrawerOpen"
        @update:open="
            (val: boolean) => {
                if (!val) closeEditDrawer();
            }
        "
    >
        <DrawerContent v-if="editingLocation">
            <DrawerHeader>
                <DrawerTitle>Edit Location</DrawerTitle>
                <DrawerDescription>Edit details for location: {{ editingLocation.name }}</DrawerDescription>
            </DrawerHeader>
            <form class="space-y-4 px-6 pb-6 pt-2" @submit.prevent="submitEdit">
                <label for="edit-name" class="block mb-1 font-medium">Name</label>
                <Input id="edit-name" v-model="editForm.name" label="Name" placeholder="Name" required />
                <label for="edit-description" class="block mb-1 font-medium">Description</label>
                <Input
                    id="edit-description"
                    v-model="editForm.description"
                    label="Description"
                    placeholder="Description"
                />
                <div class="flex justify-end gap-2 mt-4">
                    <Button type="button" variant="outline" @click="closeEditDrawer">Cancel</Button>
                    <Button type="submit" variant="default">Save</Button>
                </div>
            </form>
        </DrawerContent>
    </Drawer>

    <!-- Create Drawer -->
    <Drawer
        :open="createDrawerOpen"
        @update:open="
            (val) => {
                if (!val) closeCreateDrawer();
            }
        "
    >
        <DrawerContent>
            <DrawerHeader>
                <DrawerTitle>Create Location</DrawerTitle>
                <DrawerDescription>Fill in the details to create a new location.</DrawerDescription>
            </DrawerHeader>
            <form class="space-y-4 px-6 pb-6 pt-2" @submit.prevent="submitCreate">
                <label for="create-name" class="block mb-1 font-medium">Name</label>
                <Input id="create-name" v-model="createForm.name" label="Name" placeholder="Name" required />
                <label for="create-description" class="block mb-1 font-medium">Description</label>
                <Input
                    id="create-description"
                    v-model="createForm.description"
                    label="Description"
                    placeholder="Description"
                />
                <div class="flex justify-end gap-2 mt-4">
                    <Button type="button" variant="outline" @click="closeCreateDrawer">Cancel</Button>
                    <Button type="submit" variant="default">Create</Button>
                </div>
            </form>
        </DrawerContent>
    </Drawer>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { computed, ref, onMounted, watch } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import WidgetRenderer from '@/components/plugins/WidgetRenderer.vue';
import { usePluginWidgets, getWidgets } from '@/composables/usePluginWidgets';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Eye, Pencil, Trash2, Server, Plus, MapPin, Flag, Rocket } from 'lucide-vue-next';
import axios from 'axios';
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerClose,
} from '@/components/ui/drawer';
import { useRouter } from 'vue-router';
import TableComponent from '@/kit/TableComponent.vue';
import type { TableColumn } from '@/kit/types';
import { Card, CardContent } from '@/components/ui/card';
import { useToast } from 'vue-toastification';

type Location = {
    id: number;
    name: string;
    description?: string;
    created_at: string;
    updated_at: string;
};

const toast = useToast();
const router = useRouter();

// Plugin widgets
const { fetchWidgets: fetchPluginWidgets } = usePluginWidgets('admin-locations');
const widgetsTopOfPage = computed(() => getWidgets('admin-locations', 'top-of-page'));
const widgetsBeforeTable = computed(() => getWidgets('admin-locations', 'before-table'));
const widgetsAfterTable = computed(() => getWidgets('admin-locations', 'after-table'));
const widgetsAfterHelpCards = computed(() => getWidgets('admin-locations', 'after-help-cards'));
const widgetsBottomOfPage = computed(() => getWidgets('admin-locations', 'bottom-of-page'));

const locations = ref<Location[]>([]);
const searchQuery = ref('');
// Pagination
const pagination = ref({
    page: 1,
    pageSize: 10,
    total: 0,
    hasNext: false,
    hasPrev: false,
    from: 0,
    to: 0,
});
const loading = ref(true);
const deleting = ref(false);
const confirmDeleteRow = ref<number | null>(null);
const selectedLocation = ref<Location | null>(null);
const viewing = ref(false);
const editingLocation = ref<Location | null>(null);
const editDrawerOpen = ref(false);
const editForm = ref({
    name: '',
    description: '',
});
const createDrawerOpen = ref(false);
const createForm = ref({
    name: '',
    description: '',
});

// Table columns configuration
const tableColumns: TableColumn[] = [
    { key: 'name', label: 'Name', searchable: true },
    { key: 'description', label: 'Description', searchable: true },
    { key: 'created_at', label: 'Created' },
    { key: 'actions', label: 'Actions', headerClass: 'w-[120px] font-semibold' },
];

async function fetchLocations() {
    loading.value = true;
    try {
        const { data } = await axios.get('/api/admin/locations', {
            params: {
                page: pagination.value.page,
                limit: pagination.value.pageSize,
                search: searchQuery.value || undefined,
            },
        });
        locations.value = data.data.locations || [];

        // Map the API response pagination to our expected format
        const apiPagination = data.data.pagination;
        pagination.value = {
            page: apiPagination.current_page,
            pageSize: apiPagination.per_page,
            total: apiPagination.total_records,
            hasNext: apiPagination.has_next,
            hasPrev: apiPagination.has_prev,
            from: apiPagination.from,
            to: apiPagination.to,
        };
    } finally {
        loading.value = false;
    }
}

onMounted(async () => {
    // Fetch plugin widgets
    await fetchPluginWidgets();

    await fetchLocations();
});
watch([() => pagination.value.page, () => pagination.value.pageSize, searchQuery], fetchLocations);

function handleSearch(query: string) {
    searchQuery.value = query;
    pagination.value.page = 1; // Reset to first page when searching
    fetchLocations();
}

function changePage(page: number) {
    pagination.value.page = page;
    fetchLocations();
}

async function onView(location: Location) {
    viewing.value = true;
    try {
        const { data } = await axios.get(`/api/admin/locations/${location.id}`);
        selectedLocation.value = data.data.location;
    } catch {
        selectedLocation.value = null;
        toast.error('Failed to fetch location details');
    }
}

function onEdit(location: Location) {
    openEditDrawer(location);
}

async function confirmDelete(location: Location) {
    deleting.value = true;
    let success = false;
    try {
        const response = await axios.delete(`/api/admin/locations/${location.id}`);
        if (response.data && response.data.success) {
            toast.success('Location deleted successfully');
            await fetchLocations();
            success = true;
        } else {
            toast.error(response.data?.message || 'Failed to delete location');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to delete location';
        toast.error(errorMessage);
    } finally {
        deleting.value = false;
        if (success) confirmDeleteRow.value = null;
    }
}

function onDelete(location: Location) {
    confirmDeleteRow.value = location.id;
}

function onCancelDelete() {
    confirmDeleteRow.value = null;
}

function closeView() {
    viewing.value = false;
    selectedLocation.value = null;
}

async function openEditDrawer(location: Location) {
    try {
        const { data } = await axios.get(`/api/admin/locations/${location.id}`);
        const l: Location = data.data.location;
        editingLocation.value = l;
        editForm.value = {
            name: l.name || '',
            description: l.description || '',
        };
        editDrawerOpen.value = true;
    } catch {
        toast.error('Failed to fetch location details for editing');
    }
}

function closeEditDrawer() {
    editDrawerOpen.value = false;
    editingLocation.value = null;
}

async function submitEdit() {
    if (!editingLocation.value) return;
    try {
        const patchData = { ...editForm.value };
        const { data } = await axios.patch(`/api/admin/locations/${editingLocation.value.id}`, patchData);
        if (data && data.success) {
            toast.success('Location updated successfully');
            await fetchLocations();
            closeEditDrawer();
        } else {
            toast.error(data?.message || 'Failed to update location');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to update location';
        toast.error(errorMessage);
    }
}

function openCreateDrawer() {
    createDrawerOpen.value = true;
    createForm.value = { name: '', description: '' };
}

function closeCreateDrawer() {
    createDrawerOpen.value = false;
}

async function submitCreate() {
    try {
        const { data } = await axios.put('/api/admin/locations', createForm.value);
        if (data && data.success) {
            toast.success('Location created successfully');
            await fetchLocations();
            closeCreateDrawer();
        } else {
            toast.error(data?.message || 'Failed to create location');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to create location';
        toast.error(errorMessage);
    }
}

function onViewNodes(location: Location) {
    router.push(`/admin/nodes?location_id=${location.id}`);
}
</script>

// featherpanel-frontendv2/src/app/admin/locations/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import { useState, useEffect } from 'react';
import { useRouter } from 'next/navigation';
import axios, { isAxiosError } from 'axios';
import { useTranslation } from '@/contexts/TranslationContext';
import { PageHeader } from '@/components/featherui/PageHeader';
import { Button } from '@/components/featherui/Button';
import { Input } from '@/components/featherui/Input';
import { PageCard } from '@/components/featherui/PageCard';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { TableSkeleton } from '@/components/featherui/TableSkeleton';
import { EmptyState } from '@/components/featherui/EmptyState';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from '@/components/ui/sheet';
import { Select } from '@/components/ui/select-native';
import { Label } from '@/components/ui/label';
import { usePluginWidgets } from '@/hooks/usePluginWidgets';
import { WidgetRenderer } from '@/components/server/WidgetRenderer';
import { toast } from 'sonner';
import {
    Globe,
    Plus,
    Search,
    Pencil,
    Trash2,
    Server,
    ChevronLeft,
    ChevronRight,
    MapPin,
    Flag,
    Rocket,
} from 'lucide-react';
import NextImage from 'next/image';

interface Location {
    id: number;
    name: string;
    description?: string;
    flag_code?: string | null;
    created_at: string;
    updated_at: string;
}

interface Pagination {
    page: number;
    pageSize: number;
    total: number;
    totalPages: number;
    hasNext: boolean;
    hasPrev: boolean;
}

export default function LocationsPage() {
    const { t } = useTranslation();
    const router = useRouter();
    const [loading, setLoading] = useState(true);
    const [locations, setLocations] = useState<Location[]>([]);
    const [searchQuery, setSearchQuery] = useState('');
    const [debouncedSearchQuery, setDebouncedSearchQuery] = useState('');

    // Pagination
    const [pagination, setPagination] = useState<Pagination>({
        page: 1,
        pageSize: 10,
        total: 0,
        totalPages: 0,
        hasNext: false,
        hasPrev: false,
    });

    // Sheets
    const [editOpen, setEditOpen] = useState(false);
    const [createOpen, setCreateOpen] = useState(false);

    // Selected items
    const [editingLocation, setEditingLocation] = useState<Location | null>(null);

    // Form states
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [editForm, setEditForm] = useState({ name: '', description: '', flag_code: '' });
    const [createForm, setCreateForm] = useState({ name: '', description: '', flag_code: '' });
    const [refreshKey, setRefreshKey] = useState(0);
    const [confirmDeleteId, setConfirmDeleteId] = useState<number | null>(null);
    const [deleting, setDeleting] = useState(false);

    // Country codes
    const [countryCodes, setCountryCodes] = useState<Record<string, string>>({});

    // Plugin Widgets
    const { fetchWidgets, getWidgets } = usePluginWidgets('admin-locations');

    useEffect(() => {
        fetchWidgets();
    }, [fetchWidgets]);

    // Debounce search
    useEffect(() => {
        const timer = setTimeout(() => {
            setDebouncedSearchQuery(searchQuery);
            if (searchQuery !== debouncedSearchQuery) {
                setPagination((p) => ({ ...p, page: 1 }));
            }
        }, 500);
        return () => clearTimeout(timer);
    }, [searchQuery, debouncedSearchQuery]);

    // Fetch country codes
    useEffect(() => {
        const fetchCountryCodes = async () => {
            try {
                const { data } = await axios.get('/api/system/country-codes');
                if (data && data.success && data.data?.country_codes) {
                    const sorted = Object.entries(data.data.country_codes as Record<string, string>).sort((a, b) =>
                        a[1].localeCompare(b[1]),
                    );
                    setCountryCodes(Object.fromEntries(sorted) as Record<string, string>);
                }
            } catch (error) {
                console.error('Error fetching country codes:', error);
                toast.error(t('admin.locations.messages.country_codes_failed'));
            }
        };
        fetchCountryCodes();
    }, [t]);

    // Fetch locations
    useEffect(() => {
        const fetchLocations = async () => {
            setLoading(true);
            try {
                const { data } = await axios.get('/api/admin/locations', {
                    params: {
                        page: pagination.page,
                        limit: pagination.pageSize,
                        search: debouncedSearchQuery || undefined,
                    },
                });

                setLocations(data.data.locations || []);
                const apiPagination = data.data.pagination;
                setPagination({
                    page: apiPagination.current_page,
                    pageSize: apiPagination.per_page,
                    total: apiPagination.total_records,
                    totalPages: Math.ceil(apiPagination.total_records / apiPagination.per_page),
                    hasNext: apiPagination.has_next,
                    hasPrev: apiPagination.has_prev,
                });
            } catch (error) {
                console.error('Error fetching locations:', error);
                toast.error(t('admin.locations.messages.fetch_failed'));
            } finally {
                setLoading(false);
            }
        };

        fetchLocations();
    }, [pagination.page, pagination.pageSize, debouncedSearchQuery, refreshKey, t]);

    // CRUD Operations
    const handleEdit = async (location: Location) => {
        try {
            const { data } = await axios.get(`/api/admin/locations/${location.id}`);
            const loc = data.data.location;
            setEditingLocation(loc);
            setEditForm({
                name: loc.name || '',
                description: loc.description || '',
                flag_code: loc.flag_code || '__NONE__',
            });
            setEditOpen(true);
        } catch (error) {
            console.error('Error fetching location:', error);
            toast.error(t('admin.locations.messages.fetch_details_failed'));
        }
    };

    const handleDelete = (location: Location) => {
        setConfirmDeleteId(location.id);
    };

    const confirmDelete = async (location: Location) => {
        setDeleting(true);
        try {
            await axios.delete(`/api/admin/locations/${location.id}`);
            toast.success(t('admin.locations.messages.deleted'));
            setRefreshKey((prev) => prev + 1);
            setConfirmDeleteId(null);
        } catch (error) {
            console.error('Error deleting location:', error);
            if (isAxiosError(error) && error.response?.data?.message) {
                toast.error(error.response.data.message);
            } else {
                toast.error(t('admin.locations.messages.delete_failed'));
            }
        } finally {
            setDeleting(false);
        }
    };

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsSubmitting(true);
        try {
            const createData: { name: string; description?: string; flag_code?: string | null } = {
                name: createForm.name,
            };
            if (createForm.description) {
                createData.description = createForm.description;
            }
            createData.flag_code = createForm.flag_code === '__NONE__' ? null : createForm.flag_code || null;

            await axios.put('/api/admin/locations', createData);
            toast.success(t('admin.locations.messages.created'));
            setCreateOpen(false);
            setCreateForm({ name: '', description: '', flag_code: '' });
            setRefreshKey((prev) => prev + 1);
        } catch (error) {
            console.error('Error creating location:', error);
            if (isAxiosError(error) && error.response?.data?.message) {
                toast.error(error.response.data.message);
            } else {
                toast.error(t('admin.locations.messages.create_failed'));
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleUpdate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!editingLocation) return;
        setIsSubmitting(true);
        try {
            const patchData: { name: string; description?: string; flag_code?: string | null } = {
                name: editForm.name,
            };
            if (editForm.description !== undefined) {
                patchData.description = editForm.description || undefined;
            }
            patchData.flag_code = editForm.flag_code === '__NONE__' ? null : editForm.flag_code || null;

            await axios.patch(`/api/admin/locations/${editingLocation.id}`, patchData);
            toast.success(t('admin.locations.messages.updated'));
            setEditOpen(false);
            setRefreshKey((prev) => prev + 1);
        } catch (error) {
            console.error('Error updating location:', error);
            if (isAxiosError(error) && error.response?.data?.message) {
                toast.error(error.response.data.message);
            } else {
                toast.error(t('admin.locations.messages.update_failed'));
            }
        } finally {
            setIsSubmitting(false);
        }
    };

    const handleViewNodes = (location: Location) => {
        router.push(`/admin/nodes?location_id=${location.id}`);
    };

    return (
        <div className='space-y-6'>
            {/* Plugin Widgets: Top of Page */}
            <WidgetRenderer widgets={getWidgets('admin-locations', 'top-of-page')} />

            <PageHeader
                title={t('admin.locations.title')}
                description={t('admin.locations.subtitle')}
                icon={Globe}
                actions={
                    <Button onClick={() => setCreateOpen(true)}>
                        <Plus className='h-4 w-4 mr-2' />
                        {t('admin.locations.create')}
                    </Button>
                }
            />

            {/* Plugin Widgets: After Header */}
            <WidgetRenderer widgets={getWidgets('admin-locations', 'after-header')} />

            <div className='flex flex-col sm:flex-row gap-4 items-center bg-card/40 backdrop-blur-md p-4 rounded-2xl shadow-sm'>
                <div className='relative flex-1 group w-full'>
                    <Search className='absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors' />
                    <Input
                        placeholder={t('admin.locations.search_placeholder')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className='pl-10 h-11 w-full'
                    />
                </div>
            </div>

            {/* Plugin Widgets: Before List */}
            <WidgetRenderer widgets={getWidgets('admin-locations', 'before-list')} />

            {loading ? (
                <TableSkeleton count={5} />
            ) : locations.length === 0 ? (
                <EmptyState
                    icon={Globe}
                    title={t('admin.locations.no_results')}
                    description={t('admin.locations.create_description')}
                    action={
                        <Button onClick={() => setCreateOpen(true)}>
                            <Plus className='h-4 w-4 mr-2' />
                            {t('admin.locations.create')}
                        </Button>
                    }
                />
            ) : (
                <div className='grid grid-cols-1 gap-4'>
                    {locations.map((location) => (
                        <ResourceCard
                            key={location.id}
                            title={location.name}
                            subtitle={new Date(location.created_at).toLocaleDateString()}
                            icon={Globe}
                            description={
                                <div className='flex items-center gap-2 text-sm text-muted-foreground mt-1'>
                                    {location.flag_code && (
                                        <NextImage
                                            src={`https://flagcdn.com/16x12/${location.flag_code}.png`}
                                            alt={location.flag_code}
                                            width={16}
                                            height={12}
                                            className='rounded-sm'
                                            unoptimized
                                        />
                                    )}
                                    <span>{location.description || t('common.nA')}</span>
                                </div>
                            }
                            actions={
                                <div className='flex items-center gap-2'>
                                    <Button
                                        size='sm'
                                        variant='ghost'
                                        onClick={() => handleEdit(location)}
                                        title={t('admin.locations.actions.edit')}
                                    >
                                        <Pencil className='h-4 w-4' />
                                    </Button>
                                    <Button
                                        size='sm'
                                        variant='ghost'
                                        onClick={() => handleViewNodes(location)}
                                        title={t('admin.locations.actions.view_nodes')}
                                    >
                                        <Server className='h-4 w-4' />
                                    </Button>
                                    {confirmDeleteId === location.id ? (
                                        <>
                                            <Button
                                                size='sm'
                                                variant='destructive'
                                                onClick={() => confirmDelete(location)}
                                                loading={deleting}
                                                title={t('admin.locations.actions.confirm_delete')}
                                            >
                                                {t('common.confirm')}
                                            </Button>
                                            <Button
                                                size='sm'
                                                variant='outline'
                                                onClick={() => setConfirmDeleteId(null)}
                                                disabled={deleting}
                                                title={t('admin.locations.actions.cancel_delete')}
                                            >
                                                {t('common.cancel')}
                                            </Button>
                                        </>
                                    ) : (
                                        <Button
                                            size='sm'
                                            variant='ghost'
                                            className='text-destructive hover:text-destructive hover:bg-destructive/10'
                                            onClick={() => handleDelete(location)}
                                            title={t('admin.locations.actions.delete')}
                                        >
                                            <Trash2 className='h-4 w-4' />
                                        </Button>
                                    )}
                                </div>
                            }
                        />
                    ))}
                </div>
            )}

            {pagination.totalPages > 1 && (
                <div className='flex items-center justify-center gap-2 mt-8'>
                    <Button
                        variant='outline'
                        size='icon'
                        disabled={!pagination.hasPrev}
                        onClick={() => setPagination((p) => ({ ...p, page: p.page - 1 }))}
                    >
                        <ChevronLeft className='h-4 w-4' />
                    </Button>
                    <span className='text-sm font-medium'>
                        {pagination.page} / {pagination.totalPages}
                    </span>
                    <Button
                        variant='outline'
                        size='icon'
                        disabled={!pagination.hasNext}
                        onClick={() => setPagination((p) => ({ ...p, page: p.page + 1 }))}
                    >
                        <ChevronRight className='h-4 w-4' />
                    </Button>
                </div>
            )}

            {/* Help Cards */}
            <div className='grid grid-cols-1 md:grid-cols-3 gap-6'>
                <PageCard title={t('admin.locations.help.what.title')} icon={MapPin}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.locations.help.what.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.locations.help.examples.title')} icon={Flag}>
                    <div className='text-sm text-muted-foreground leading-relaxed space-y-2'>
                        <ul className='list-disc list-inside space-y-1'>
                            <li>
                                <b>{t('admin.locations.help.examples.usa')}</b>:{' '}
                                {t('admin.locations.help.examples.usa_desc')}
                            </li>
                            <li>
                                <b>{t('admin.locations.help.examples.romania')}</b>:{' '}
                                {t('admin.locations.help.examples.romania_desc')}
                            </li>
                        </ul>
                        <p>{t('admin.locations.help.examples.naming')}</p>
                    </div>
                </PageCard>
                <PageCard title={t('admin.locations.help.getting_started.title')} icon={Rocket}>
                    <div className='text-sm text-muted-foreground leading-relaxed'>
                        <ol className='list-decimal list-inside space-y-1'>
                            <li>{t('admin.locations.help.getting_started.step1')}</li>
                            <li>{t('admin.locations.help.getting_started.step2')}</li>
                            <li>{t('admin.locations.help.getting_started.step3')}</li>
                        </ol>
                    </div>
                </PageCard>
            </div>

            {/* Edit Sheet */}
            <Sheet open={editOpen} onOpenChange={setEditOpen}>
                <SheetContent>
                    <SheetHeader>
                        <SheetTitle>{t('admin.locations.form.edit_title')}</SheetTitle>
                        <SheetDescription>
                            {editingLocation
                                ? t('admin.locations.form.edit_description', { name: editingLocation.name })
                                : ''}
                        </SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleUpdate} className='space-y-4 mt-6'>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-name'>{t('admin.locations.form.name')} *</Label>
                            <Input
                                id='edit-name'
                                value={editForm.name}
                                onChange={(e) => setEditForm({ ...editForm, name: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-description'>{t('admin.locations.form.description')}</Label>
                            <Input
                                id='edit-description'
                                value={editForm.description}
                                onChange={(e) => setEditForm({ ...editForm, description: e.target.value })}
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-flag'>{t('admin.locations.form.flag')}</Label>
                            <Select
                                id='edit-flag'
                                value={editForm.flag_code}
                                onChange={(e) => setEditForm({ ...editForm, flag_code: e.target.value })}
                            >
                                <option value='__NONE__'>{t('admin.locations.form.flag_none')}</option>
                                {Object.entries(countryCodes).map(([code, name]) => (
                                    <option key={code} value={code}>
                                        {name}
                                    </option>
                                ))}
                            </Select>
                        </div>
                        <SheetFooter>
                            <Button type='button' variant='outline' onClick={() => setEditOpen(false)}>
                                {t('common.cancel')}
                            </Button>
                            <Button type='submit' loading={isSubmitting}>
                                {t('common.saveChanges')}
                            </Button>
                        </SheetFooter>
                    </form>
                </SheetContent>
            </Sheet>

            {/* Create Sheet */}
            <Sheet open={createOpen} onOpenChange={setCreateOpen}>
                <SheetContent>
                    <SheetHeader>
                        <SheetTitle>{t('admin.locations.form.create_title')}</SheetTitle>
                        <SheetDescription>{t('admin.locations.form.create_description')}</SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleCreate} className='space-y-4 mt-6'>
                        <div className='space-y-2'>
                            <Label htmlFor='create-name'>{t('admin.locations.form.name')} *</Label>
                            <Input
                                id='create-name'
                                value={createForm.name}
                                onChange={(e) => setCreateForm({ ...createForm, name: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='create-description'>{t('admin.locations.form.description')}</Label>
                            <Input
                                id='create-description'
                                value={createForm.description}
                                onChange={(e) => setCreateForm({ ...createForm, description: e.target.value })}
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='create-flag'>{t('admin.locations.form.flag')}</Label>
                            <Select
                                id='create-flag'
                                value={createForm.flag_code}
                                onChange={(e) => setCreateForm({ ...createForm, flag_code: e.target.value })}
                            >
                                <option value='__NONE__'>{t('admin.locations.form.flag_none')}</option>
                                {Object.entries(countryCodes).map(([code, name]) => (
                                    <option key={code} value={code}>
                                        {name}
                                    </option>
                                ))}
                            </Select>
                        </div>
                        <SheetFooter>
                            <Button type='button' variant='outline' onClick={() => setCreateOpen(false)}>
                                {t('common.cancel')}
                            </Button>
                            <Button type='submit' loading={isSubmitting}>
                                {t('common.create')}
                            </Button>
                        </SheetFooter>
                    </form>
                </SheetContent>
            </Sheet>

            {/* Plugin Widgets: Bottom of Page */}
            <WidgetRenderer widgets={getWidgets('admin-locations', 'bottom-of-page')} />
        </div>
    );
}
