// featherpanel-frontendv2/src/components/admin/CronStatusWidget.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client'

import React from 'react'
import { Activity, CheckCircle2, AlertTriangle, XCircle, Clock } from 'lucide-react'
import { useTranslation } from '@/contexts/TranslationContext'
import { PageCard } from '@/components/featherui/PageCard'
import { cn } from '@/lib/utils'

interface CronTask {
    id: number
    task_name: string
    last_run_at: string | null
    last_run_success: boolean
    late: boolean
}

interface CronStatusWidgetProps {
    tasks?: CronTask[]
    loading?: boolean
}

export function CronStatusWidget({ tasks, loading }: CronStatusWidgetProps) {
    const { t } = useTranslation()

    return (
        <PageCard
            title={t('admin.cron.title')}
            description={t('admin.cron.description')}
            icon={Activity}
        >
            <div className="space-y-4">
                {loading ? (
                    Array.from({ length: 3 }).map((_, i) => (
                        <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-muted/20 animate-pulse">
                            <div className="space-y-2">
                                <div className="h-4 w-32 bg-muted rounded" />
                                <div className="h-3 w-24 bg-muted rounded" />
                            </div>
                            <div className="h-6 w-16 bg-muted rounded" />
                        </div>
                    ))
                ) : tasks && tasks.length > 0 ? (
                    tasks.map((task) => (
                        <div 
                            key={task.id} 
                            className="flex items-center justify-between p-4 rounded-2xl bg-muted/10 border border-border/50 group hover:bg-muted/20 transition-all"
                        >
                            <div className="flex items-center gap-3 min-w-0">
                                <div className={cn(
                                    "h-10 w-10 rounded-xl flex items-center justify-center shrink-0",
                                    task.last_run_success && !task.late ? "bg-green-500/10 text-green-500" :
                                    task.late ? "bg-orange-500/10 text-orange-500" : "bg-red-500/10 text-red-500"
                                )}>
                                    {task.last_run_success && !task.late ? <CheckCircle2 className="h-5 w-5" /> :
                                     task.late ? <Clock className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}
                                </div>
                                <div className="min-w-0">
                                    <p className="text-sm font-bold tracking-tight truncate">{task.task_name}</p>
                                    <p className="text-[10px] text-muted-foreground uppercase font-bold opacity-70 truncate">
                                        {t('admin.cron.last_run', { date: task.last_run_at ? new Date(task.last_run_at).toLocaleString() : t('admin.cron.never') })}
                                    </p>
                                </div>
                            </div>
                            <div className={cn(
                                "px-2 py-1 rounded-lg text-[10px] font-black uppercase tracking-wider shrink-0",
                                task.last_run_success && !task.late ? "bg-green-500/20 text-green-500" :
                                task.late ? "bg-orange-500/20 text-orange-500" : "bg-red-500/20 text-red-500"
                            )}>
                                {task.last_run_success && !task.late ? t('admin.cron.healthy') : task.late ? t('admin.cron.late') : t('admin.cron.failed')}
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="text-center py-8">
                        <AlertTriangle className="h-12 w-12 text-muted-foreground/30 mx-auto mb-3" />
                        <p className="text-sm text-muted-foreground font-bold italic">{t('admin.cron.no_tasks')}</p>
                    </div>
                )}
            </div>
        </PageCard>
    )
}

// frontend/src/components/admin/CronStatusWidget.vue
<template>
    <div v-if="cronRecent || cronSummary" class="p-6 space-y-4">
        <div class="flex items-center justify-between">
            <h2 class="text-xl font-semibold">Automation Tasks Status</h2>
            <div v-if="cronRecent" class="text-xs text-muted-foreground">Updated just now</div>
        </div>
        <div v-if="cronSummary" class="text-sm text-muted-foreground bg-muted/50 border rounded-md p-4">
            {{ cronSummary }}
        </div>
        <div v-else class="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card v-for="item in cronRecent" :key="item.id" class="p-4 border hover:shadow-md transition-shadow">
                <div class="flex items-start gap-3">
                    <div
                        class="h-9 w-9 rounded-full flex items-center justify-center flex-shrink-0"
                        :class="
                            item.last_run_success
                                ? 'bg-emerald-500/10 text-emerald-600'
                                : 'bg-destructive/10 text-destructive'
                        "
                    >
                        <component :is="item.last_run_success ? CheckCircle2 : AlertTriangle" :size="18" />
                    </div>
                    <div class="flex-1 min-w-0">
                        <div class="flex items-center justify-between gap-2">
                            <div class="font-medium capitalize truncate">{{ prettyTaskName(item.task_name) }}</div>
                            <div class="flex items-center gap-2 flex-shrink-0">
                                <span
                                    class="text-xs px-2 py-0.5 rounded-full"
                                    :class="
                                        item.last_run_success
                                            ? 'bg-emerald-500/10 text-emerald-600'
                                            : 'bg-destructive/10 text-destructive'
                                    "
                                >
                                    {{ item.last_run_success ? 'OK' : 'FAIL' }}
                                </span>
                                <span
                                    v-if="item.late"
                                    class="text-xs px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-600"
                                >
                                    Late
                                </span>
                            </div>
                        </div>
                        <div class="mt-1 text-sm text-muted-foreground">
                            Last run {{ formatAgo(item.last_run_at) }} • every ~{{
                                formatEvery(item.expected_interval_seconds)
                            }}
                        </div>
                        <div
                            v-if="item.last_run_message"
                            class="mt-2 text-xs rounded-md border bg-muted/40 p-2 text-muted-foreground break-words"
                            :title="item.last_run_message"
                        >
                            {{ truncate(item.last_run_message, 120) }}
                        </div>
                    </div>
                </div>
            </Card>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { computed } from 'vue';
import { Card } from '@/components/ui/card';
import { CheckCircle2, AlertTriangle } from 'lucide-vue-next';
import { useDashboardStore } from '@/stores/dashboard';

const dashboardStore = useDashboardStore();

const cronRecent = computed(() => dashboardStore.cronRecent);
const cronSummary = computed(() => dashboardStore.cronSummary);

function formatAgo(dateStr: string | null): string {
    if (!dateStr) return 'never';
    const d = new Date(dateStr.replace(' ', 'T'));
    const diffMs = Date.now() - d.getTime();
    if (Number.isNaN(diffMs)) return dateStr;
    const minutes = Math.floor(diffMs / 60000);
    if (minutes < 1) return 'just now';
    if (minutes < 60) return `${minutes}m ago`;
    const hours = Math.floor(minutes / 60);
    if (hours < 24) return `${hours}h ago`;
    const days = Math.floor(hours / 24);
    return `${days}d ago`;
}

function formatEvery(seconds: number): string {
    if (!seconds || seconds <= 0) return 'n/a';
    if (seconds < 90) return `${Math.max(1, Math.round(seconds / 60))}m`;
    if (seconds < 3600) return `${Math.round(seconds / 60)}m`;
    if (seconds < 86400) return `${Math.round(seconds / 3600)}h`;
    return `${Math.round(seconds / 86400)}d`;
}

function truncate(text: string, maxLen = 120): string {
    if (!text) return '';
    return text.length > maxLen ? text.slice(0, maxLen - 1) + '…' : text;
}

function prettyTaskName(name: string): string {
    switch (name) {
        case 'server-schedule-processor':
            return 'Server Schedule Processor';
        case 'mail-sender':
            return 'Mail Sender';
        case 'update-env':
            return 'Update Env';
        default:
            return name.replace(/[-_]/g, ' ');
    }
}
</script>
