// frontend/src/pages/admin/MailTemplates.vue
<template>
    <DashboardLayout :breadcrumbs="[{ text: 'Mail Templates', isCurrent: true, href: '/admin/mail-templates' }]">
        <div class="min-h-screen bg-background">
            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading mail templates...</span>
                </div>
            </div>

            <!-- Error State -->
            <div
                v-else-if="message?.type === 'error'"
                class="flex flex-col items-center justify-center py-12 text-center"
            >
                <div class="text-red-500 mb-4">
                    <svg class="h-12 w-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"
                        />
                    </svg>
                </div>
                <h3 class="text-lg font-medium text-muted-foreground mb-2">Failed to load mail templates</h3>
                <p class="text-sm text-muted-foreground max-w-sm">
                    {{ message.text }}
                </p>
                <Button class="mt-4" @click="fetchTemplates">Try Again</Button>
            </div>

            <!-- Templates Table -->
            <div v-else class="p-6">
                <TableComponent
                    title="Mail Templates"
                    description="Manage email templates for your system."
                    :columns="tableColumns"
                    :data="templates"
                    :search-placeholder="'Search by name or subject...'"
                    :server-side-pagination="true"
                    :total-records="pagination.total"
                    :total-pages="Math.ceil(pagination.total / pagination.pageSize)"
                    :current-page="pagination.page"
                    :has-next="pagination.hasNext"
                    :has-prev="pagination.hasPrev"
                    :from="pagination.from"
                    :to="pagination.to"
                    local-storage-key="featherpanel-mail-templates-table-columns"
                    @search="handleSearch"
                    @page-change="changePage"
                    @column-toggle="handleColumnToggle"
                >
                    <template #header-actions>
                        <div class="flex gap-2">
                            <Button variant="outline" size="sm" @click="openCreateDrawer">
                                <Plus class="h-4 w-4 mr-2" />
                                Create Template
                            </Button>
                        </div>
                    </template>

                    <!-- Custom cell templates -->
                    <template #cell-name="{ item }">
                        <div class="flex items-center gap-2">
                            <Mail class="h-4 w-4 text-muted-foreground" />
                            <span class="font-medium">{{ (item as unknown as MailTemplate).name }}</span>
                        </div>
                    </template>

                    <template #cell-subject="{ item }">
                        <span class="text-sm">{{ (item as unknown as MailTemplate).subject }}</span>
                    </template>

                    <template #cell-body="{ item }">
                        <div class="max-w-xs">
                            <p class="text-sm text-muted-foreground truncate">
                                {{ (item as unknown as MailTemplate).body.substring(0, 100) }}
                                {{ (item as unknown as MailTemplate).body.length > 100 ? '...' : '' }}
                            </p>
                        </div>
                    </template>

                    <template #cell-created_at="{ item }">
                        <span class="text-sm text-muted-foreground">
                            {{ formatDate((item as unknown as MailTemplate).created_at) }}
                        </span>
                    </template>

                    <template #cell-updated_at="{ item }">
                        <span class="text-sm text-muted-foreground">
                            {{ formatDate((item as unknown as MailTemplate).updated_at) }}
                        </span>
                    </template>

                    <template #cell-actions="{ item }">
                        <div class="flex gap-2">
                            <Button size="sm" variant="outline" @click="onView(item as unknown as MailTemplate)">
                                <Eye :size="16" />
                            </Button>
                            <Button size="sm" variant="secondary" @click="onEdit(item as unknown as MailTemplate)">
                                <Pencil :size="16" />
                            </Button>
                            <Button size="sm" variant="outline" @click="onPreview(item as unknown as MailTemplate)">
                                <Eye :size="16" />
                            </Button>
                            <template v-if="confirmDeleteRow === (item as unknown as MailTemplate).id">
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    :loading="deleting"
                                    @click="confirmDelete(item as unknown as MailTemplate)"
                                >
                                    Confirm Delete
                                </Button>
                                <Button size="sm" variant="outline" :disabled="deleting" @click="onCancelDelete">
                                    Cancel
                                </Button>
                            </template>
                            <template v-else>
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    :disabled="deleting"
                                    @click="onDelete(item as unknown as MailTemplate)"
                                >
                                    <Trash2 :size="16" />
                                </Button>
                            </template>
                        </div>
                    </template>
                </TableComponent>
            </div>
        </div>

        <!-- View Drawer -->
        <Drawer
            :open="viewDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeViewDrawer();
                }
            "
        >
            <DrawerContent v-if="selectedTemplate">
                <DrawerHeader>
                    <DrawerTitle>Template Details</DrawerTitle>
                    <DrawerDescription>Viewing details for template: {{ selectedTemplate.name }}</DrawerDescription>
                </DrawerHeader>

                <div class="px-6 pb-6 space-y-6">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label class="text-sm font-medium">Name</Label>
                            <p class="text-sm text-muted-foreground mt-1">{{ selectedTemplate.name }}</p>
                        </div>
                        <div>
                            <Label class="text-sm font-medium">Subject</Label>
                            <p class="text-sm text-muted-foreground mt-1">{{ selectedTemplate.subject }}</p>
                        </div>
                    </div>

                    <div>
                        <Label class="text-sm font-medium">Body</Label>
                        <div class="mt-2 p-4 bg-muted rounded-lg">
                            <pre class="text-sm whitespace-pre-wrap">{{ selectedTemplate.body }}</pre>
                        </div>
                    </div>

                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label class="text-sm font-medium">Created At</Label>
                            <p class="text-sm text-muted-foreground mt-1">
                                {{ formatDate(selectedTemplate.created_at) }}
                            </p>
                        </div>
                        <div>
                            <Label class="text-sm font-medium">Updated At</Label>
                            <p class="text-sm text-muted-foreground mt-1">
                                {{ formatDate(selectedTemplate.updated_at) }}
                            </p>
                        </div>
                    </div>
                </div>

                <DrawerFooter>
                    <DrawerClose as-child>
                        <Button variant="outline">Close</Button>
                    </DrawerClose>
                </DrawerFooter>
            </DrawerContent>
        </Drawer>

        <!-- Edit Drawer -->
        <Drawer
            :open="editDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeEditDrawer();
                }
            "
        >
            <DrawerContent v-if="editingTemplate">
                <DrawerHeader>
                    <DrawerTitle>Edit Template</DrawerTitle>
                    <DrawerDescription>Edit details for template: {{ editingTemplate.name }}</DrawerDescription>
                </DrawerHeader>

                <form class="px-6 pb-6 space-y-6" @submit.prevent="updateTemplate">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="space-y-2">
                            <Label for="edit-name">Name</Label>
                            <Input id="edit-name" v-model="editingTemplate.name" placeholder="Template name" required />
                        </div>
                        <div class="space-y-2">
                            <Label for="edit-subject">Subject</Label>
                            <Input
                                id="edit-subject"
                                v-model="editingTemplate.subject"
                                placeholder="Email subject"
                                required
                            />
                        </div>
                    </div>

                    <div class="space-y-2">
                        <Label for="edit-body">Body</Label>
                        <Textarea
                            id="edit-body"
                            v-model="editingTemplate.body"
                            placeholder="Enter email template body (HTML supported)"
                            class="min-h-96 font-mono text-sm"
                            rows="15"
                        />
                    </div>

                    <div class="flex gap-2">
                        <Button type="submit" :loading="updating">
                            {{ updating ? 'Updating...' : 'Update Template' }}
                        </Button>
                        <Button type="button" variant="outline" @click="closeEditDrawer">Cancel</Button>
                    </div>
                </form>
            </DrawerContent>
        </Drawer>

        <!-- Create Drawer -->
        <Drawer
            :open="createDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closeCreateDrawer();
                }
            "
        >
            <DrawerContent>
                <DrawerHeader>
                    <DrawerTitle>Create Template</DrawerTitle>
                    <DrawerDescription>Fill in the details to create a new email template.</DrawerDescription>
                </DrawerHeader>

                <form class="px-6 pb-6 space-y-6" @submit.prevent="createTemplate">
                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div class="space-y-2">
                            <Label for="create-name">Name</Label>
                            <Input id="create-name" v-model="newTemplate.name" placeholder="Template name" required />
                        </div>
                        <div class="space-y-2">
                            <Label for="create-subject">Subject</Label>
                            <Input
                                id="create-subject"
                                v-model="newTemplate.subject"
                                placeholder="Email subject"
                                required
                            />
                        </div>
                    </div>

                    <div class="space-y-2">
                        <Label for="create-body">Body</Label>
                        <Textarea
                            id="create-body"
                            v-model="newTemplate.body"
                            placeholder="Enter email template body (HTML supported)"
                            class="min-h-96 font-mono text-sm"
                            rows="15"
                        />
                    </div>

                    <div class="flex gap-2">
                        <Button type="submit" :loading="creating">
                            {{ creating ? 'Creating...' : 'Create Template' }}
                        </Button>
                        <Button type="button" variant="outline" @click="closeCreateDrawer">Cancel</Button>
                    </div>
                </form>
            </DrawerContent>
        </Drawer>

        <!-- Preview Drawer -->
        <Drawer
            :open="previewDrawerOpen"
            @update:open="
                (val) => {
                    if (!val) closePreviewDrawer();
                }
            "
        >
            <DrawerContent v-if="previewTemplate">
                <DrawerHeader>
                    <DrawerTitle>Template Preview</DrawerTitle>
                    <DrawerDescription>Preview for template: {{ previewTemplate.name }}</DrawerDescription>
                </DrawerHeader>

                <div class="px-6 pb-6">
                    <div class="space-y-4">
                        <div>
                            <Label class="text-sm font-medium">Subject</Label>
                            <p class="text-sm text-muted-foreground mt-1">{{ previewTemplate.subject }}</p>
                        </div>

                        <div>
                            <Label class="text-sm font-medium">Body Preview</Label>
                            <div class="mt-2 border rounded-lg p-4 bg-white dark:bg-gray-900">
                                <!-- eslint-disable-next-line vue/no-v-html -->
                                <div class="prose prose-sm max-w-none" v-html="previewTemplate.body"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <DrawerFooter>
                    <DrawerClose as-child>
                        <Button variant="outline">Close</Button>
                    </DrawerClose>
                </DrawerFooter>
            </DrawerContent>
        </Drawer>
    </DashboardLayout>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { useToast } from 'vue-toastification';
import axios from 'axios';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import TableComponent from '@/kit/TableComponent.vue';
import type { TableColumn } from '@/kit/types';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerFooter,
    DrawerClose,
} from '@/components/ui/drawer';
import { Plus, Eye, Pencil, Trash2, Mail } from 'lucide-vue-next';

// Types
interface MailTemplate {
    id: number;
    name: string;
    subject: string;
    body: string;
    created_at: string;
    updated_at: string;
    deleted: string;
}

interface Message {
    type: 'success' | 'error' | 'info' | 'warning';
    text: string;
}

// Reactive state
const loading = ref(true);
const templates = ref<MailTemplate[]>([]);
const pagination = ref({
    page: 1,
    pageSize: 10,
    total: 0,
    hasNext: false,
    hasPrev: false,
    from: 0,
    to: 0,
});
const message = ref<Message | null>(null);
const searchQuery = ref('');
const includeDeleted = ref(false);

// Drawer states
const viewDrawerOpen = ref(false);
const editDrawerOpen = ref(false);
const createDrawerOpen = ref(false);
const previewDrawerOpen = ref(false);

// Selected items
const selectedTemplate = ref<MailTemplate | null>(null);
const editingTemplate = ref<MailTemplate | null>(null);
const previewTemplate = ref<MailTemplate | null>(null);

// Form states
const creating = ref(false);
const updating = ref(false);
const deleting = ref(false);
const confirmDeleteRow = ref<number | null>(null);

// New template form
const newTemplate = ref({
    name: '',
    subject: '',
    body: '<h1>Welcome!</h1>\n<p>This is a sample email template.</p>',
});

// Table columns configuration
const tableColumns: TableColumn[] = [
    { key: 'name', label: 'Name', searchable: true },
    { key: 'subject', label: 'Subject', searchable: true },
    { key: 'body', label: 'Body Preview', searchable: false },
    { key: 'created_at', label: 'Created' },
    { key: 'updated_at', label: 'Updated' },
    { key: 'actions', label: 'Actions', headerClass: 'w-[120px] font-semibold' },
];

const toast = useToast();

async function fetchTemplates() {
    loading.value = true;
    try {
        const { data } = await axios.get('/api/admin/mail-templates', {
            params: {
                page: pagination.value.page,
                limit: pagination.value.pageSize,
                search: searchQuery.value || undefined,
                include_deleted: includeDeleted.value,
            },
        });
        templates.value = data.data.templates || [];

        // Map the API response pagination to our expected format
        const apiPagination = data.data.pagination;
        pagination.value = {
            page: apiPagination.current_page,
            pageSize: apiPagination.per_page,
            total: apiPagination.total_records,
            hasNext: apiPagination.has_next,
            hasPrev: apiPagination.has_prev,
            from: apiPagination.from,
            to: apiPagination.to,
        };
    } catch (error) {
        console.error('Error fetching templates:', error);
        message.value = {
            type: 'error',
            text: error instanceof Error ? error.message : 'Failed to fetch templates',
        };
    } finally {
        loading.value = false;
    }
}

const handleSearch = (query: string) => {
    searchQuery.value = query;
    pagination.value.page = 1;
    fetchTemplates();
};

const changePage = (page: number) => {
    pagination.value.page = page;
    fetchTemplates();
};

const handleColumnToggle = (columns: string[]) => {
    // Column preferences are automatically saved by the TableComponent
    console.log('Columns changed:', columns);
};

// Drawer methods
const openViewDrawer = (template: MailTemplate) => {
    selectedTemplate.value = template;
    viewDrawerOpen.value = true;
};

const closeViewDrawer = () => {
    viewDrawerOpen.value = false;
    selectedTemplate.value = null;
};

const openEditDrawer = (template: MailTemplate) => {
    editingTemplate.value = { ...template };
    editDrawerOpen.value = true;
};

const closeEditDrawer = () => {
    editDrawerOpen.value = false;
    editingTemplate.value = null;
};

const openCreateDrawer = () => {
    newTemplate.value = {
        name: '',
        subject: '',
        body: '<h1>Welcome!</h1>\n<p>This is a sample email template.</p>',
    };
    createDrawerOpen.value = true;
};

const closeCreateDrawer = () => {
    createDrawerOpen.value = false;
    newTemplate.value = {
        name: '',
        subject: '',
        body: '<h1>Welcome!</h1>\n<p>This is a sample email template.</p>',
    };
};

const openPreviewDrawer = (template: MailTemplate) => {
    previewTemplate.value = template;
    previewDrawerOpen.value = true;
};

const closePreviewDrawer = () => {
    previewDrawerOpen.value = false;
    previewTemplate.value = null;
};

async function createTemplate() {
    if (!newTemplate.value.name || !newTemplate.value.subject || !newTemplate.value.body) {
        toast.error('Please fill in all required fields');
        return;
    }

    try {
        creating.value = true;
        const { data } = await axios.post('/api/admin/mail-templates', newTemplate.value);

        if (data && data.success) {
            toast.success('Template created successfully');
            closeCreateDrawer();
            await fetchTemplates();
        } else {
            toast.error(data?.message || 'Failed to create template');
        }
    } catch (error) {
        console.error('Error creating template:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to create template');
    } finally {
        creating.value = false;
    }
}

async function updateTemplate() {
    if (!editingTemplate.value) return;

    try {
        updating.value = true;
        const { data } = await axios.patch(
            `/api/admin/mail-templates/${editingTemplate.value.id}`,
            editingTemplate.value,
        );

        if (data && data.success) {
            toast.success('Template updated successfully');
            closeEditDrawer();
            await fetchTemplates();
        } else {
            toast.error(data?.message || 'Failed to update template');
        }
    } catch (error) {
        console.error('Error updating template:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to update template');
    } finally {
        updating.value = false;
    }
}

const onDelete = (template: MailTemplate) => {
    confirmDeleteRow.value = template.id;
};

const onCancelDelete = () => {
    confirmDeleteRow.value = null;
};

async function confirmDelete(template: MailTemplate) {
    deleting.value = true;
    let success = false;
    try {
        const response = await axios.delete(`/api/admin/mail-templates/${template.id}`);
        if (response.data && response.data.success) {
            toast.success('Template deleted successfully');
            await fetchTemplates();
            success = true;
        } else {
            toast.error(response.data?.message || 'Failed to delete template');
        }
    } catch (error) {
        console.error('Error deleting template:', error);
        toast.error(error instanceof Error ? error.message : 'Failed to delete template');
    } finally {
        deleting.value = false;
        if (success) confirmDeleteRow.value = null;
    }
}

// Action handlers
const onView = (template: MailTemplate) => {
    openViewDrawer(template);
};

const onEdit = (template: MailTemplate) => {
    openEditDrawer(template);
};

const onPreview = (template: MailTemplate) => {
    openPreviewDrawer(template);
};

// Utility functions
const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
    });
};

onMounted(fetchTemplates);
watch([() => pagination.value.page, () => pagination.value.pageSize, searchQuery], fetchTemplates);
</script>

// frontendv2/src/app/(app)/admin/mail-templates/page.tsx
/*
This file is part of FeatherPanel.

Copyright (C) 2025 MythicalSystems Studios
Copyright (C) 2025 FeatherPanel Contributors
Copyright (C) 2025 Cassian Gherman (aka NaysKutzu)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the LICENSE file or <https://www.gnu.org/licenses/>.
*/

'use client';

import { useState, useEffect, useCallback } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import { PageHeader } from '@/components/featherui/PageHeader';
import { Button } from '@/components/featherui/Button';
import { Input } from '@/components/featherui/Input';
import { PageCard } from '@/components/featherui/PageCard';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { TableSkeleton } from '@/components/featherui/TableSkeleton';
import { EmptyState } from '@/components/featherui/EmptyState';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/featherui/Textarea';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Sheet, SheetHeader, SheetTitle, SheetDescription, SheetFooter } from '@/components/ui/sheet';
import {
    Plus,
    Search,
    Eye,
    Pencil,
    Trash2,
    Mail,
    FileText,
    Send,
    Scale,
    AlertTriangle,
    ChevronLeft,
    ChevronRight,
    Calendar,
} from 'lucide-react';
import axios, { isAxiosError } from 'axios';
import { toast } from 'sonner';
import { usePluginWidgets } from '@/hooks/usePluginWidgets';
import { WidgetRenderer } from '@/components/server/WidgetRenderer';

interface MailTemplate {
    id: number;
    name: string;
    subject: string;
    body: string;
    created_at: string;
    updated_at: string;
}

interface Pagination {
    page: number;
    pageSize: number;
    total: number;
    hasNext: boolean;
    hasPrev: boolean;
    from: number;
    to: number;
}

export default function MailTemplatesPage() {
    const { t } = useTranslation();
    const [loading, setLoading] = useState(true);
    const [templates, setTemplates] = useState<MailTemplate[]>([]);
    const [pagination, setPagination] = useState<Pagination>({
        page: 1,
        pageSize: 10,
        total: 0,
        hasNext: false,
        hasPrev: false,
        from: 0,
        to: 0,
    });
    const [searchQuery, setSearchQuery] = useState('');
    const [debouncedSearchQuery, setDebouncedSearchQuery] = useState('');

    // Sheet states
    const [createOpen, setCreateOpen] = useState(false);
    const [editOpen, setEditOpen] = useState(false);
    const [previewOpen, setPreviewOpen] = useState(false);
    const [massEmailOpen, setMassEmailOpen] = useState(false);

    // Selected content
    const [selectedTemplate, setSelectedTemplate] = useState<MailTemplate | null>(null);
    const [formData, setFormData] = useState({ name: '', subject: '', body: '' });
    const [massEmailData, setMassEmailData] = useState({ subject: '', body: '' });

    // Action states
    const [processing, setProcessing] = useState(false);
    const [refreshKey, setRefreshKey] = useState(0);

    const { fetchWidgets, getWidgets } = usePluginWidgets('admin-mail-templates');

    // Debounce search
    useEffect(() => {
        const timer = setTimeout(() => {
            setDebouncedSearchQuery(searchQuery);
            if (searchQuery !== debouncedSearchQuery) {
                setPagination((p) => ({ ...p, page: 1 }));
            }
        }, 500);
        return () => clearTimeout(timer);
    }, [searchQuery, debouncedSearchQuery]);

    const fetchTemplates = useCallback(async () => {
        setLoading(true);
        try {
            const { data } = await axios.get('/api/admin/mail-templates', {
                params: {
                    page: pagination.page,
                    limit: pagination.pageSize,
                    search: debouncedSearchQuery || undefined,
                },
            });
            if (data.success) {
                setTemplates(data.data.templates || []);
                const apiPag = data.data.pagination;
                setPagination({
                    page: apiPag.current_page,
                    pageSize: apiPag.per_page,
                    total: apiPag.total_records,
                    hasNext: apiPag.has_next,
                    hasPrev: apiPag.has_prev,
                    from: apiPag.from,
                    to: apiPag.to,
                });
            } else {
                toast.error(data.message || t('admin.mail_templates.messages.fetch_failed'));
            }
        } catch (error) {
            console.error('Error fetching templates:', error);
            toast.error(t('admin.mail_templates.messages.fetch_failed'));
        } finally {
            setLoading(false);
        }
    }, [pagination.page, pagination.pageSize, debouncedSearchQuery, t]);

    useEffect(() => {
        fetchTemplates();
        fetchWidgets();
    }, [fetchTemplates, refreshKey, fetchWidgets]);

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        setProcessing(true);
        try {
            const { data } = await axios.post('/api/admin/mail-templates', formData);
            if (data.success) {
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.mail_templates.messages.create_failed'));
            }
        } catch (error: unknown) {
            let message = t('admin.mail_templates.messages.create_failed');
            if (isAxiosError(error) && error.response?.data?.message) {
                message = error.response.data.message;
            }
            toast.error(message);
        } finally {
            setProcessing(false);
        }
    };

    const handleUpdate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedTemplate) return;
        setProcessing(true);
        try {
            const { data } = await axios.patch(`/api/admin/mail-templates/${selectedTemplate.id}`, formData);
            if (data.success) {
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.mail_templates.messages.update_failed'));
            }
        } catch (error: unknown) {
            let message = t('admin.mail_templates.messages.update_failed');
            if (isAxiosError(error) && error.response?.data?.message) {
                message = error.response.data.message;
            }
            toast.error(message);
        } finally {
            setProcessing(false);
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm(t('admin.mail_templates.messages.delete_confirm'))) return;
        try {
            const { data } = await axios.delete(`/api/admin/mail-templates/${id}`);
            if (data.success) {
                toast.success(t('admin.mail_templates.messages.deleted'));
                setRefreshKey((prev) => prev + 1);
            } else {
                toast.error(data.message || t('admin.mail_templates.messages.delete_failed'));
            }
        } catch {
            toast.error(t('admin.mail_templates.messages.delete_failed'));
        }
    };

    const handleSendMassEmail = async (e: React.FormEvent) => {
        e.preventDefault();
        setProcessing(true);
        try {
            const { data } = await axios.post('/api/admin/mail-templates/mass-email', massEmailData);
            if (data.success) {
                toast.success(t('admin.mail_templates.messages.mass_email_queued', { count: data.data.queued_count }));
                setMassEmailOpen(false);
                setMassEmailData({ subject: '', body: '' });
            } else {
                toast.error(data.message || t('admin.mail_templates.messages.mass_email_failed'));
            }
        } catch (error: unknown) {
            const message =
                error instanceof Error ? error.message : t('admin.mail_templates.messages.mass_email_failed');
            toast.error(message);
        } finally {
            setProcessing(false);
        }
    };

    const openCreate = () => {
        setSelectedTemplate(null);
        setFormData({ name: '', subject: '', body: '' });
        setCreateOpen(true);
    };

    const openEdit = (template: MailTemplate) => {
        setSelectedTemplate(template);
        setFormData({ name: template.name, subject: template.subject, body: template.body });
        setEditOpen(true);
    };

    const openPreview = (template: MailTemplate) => {
        setSelectedTemplate(template);
        setPreviewOpen(true);
    };

    return (
        <div className='space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500'>
            <WidgetRenderer widgets={getWidgets('admin-mail-templates', 'top-of-page')} />
            <PageHeader
                title={t('admin.mail_templates.title')}
                description={t('admin.mail_templates.subtitle')}
                icon={Mail}
                actions={
                    <div className='flex gap-2'>
                        <Button variant='outline' onClick={() => setMassEmailOpen(true)}>
                            <Send className='w-4 h-4 mr-2' />
                            {t('admin.mail_templates.send_mass_email')}
                        </Button>
                        <Button onClick={openCreate}>
                            <Plus className='w-4 h-4 mr-2' />
                            {t('admin.mail_templates.create')}
                        </Button>
                    </div>
                }
            />

            <WidgetRenderer widgets={getWidgets('admin-mail-templates', 'after-header')} />

            <div className='flex flex-col sm:flex-row gap-4 items-center bg-card/40 backdrop-blur-md p-4 rounded-2xl shadow-sm'>
                <div className='relative flex-1 group w-full'>
                    <Search className='absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors' />
                    <Input
                        className='pl-10 h-11 w-full'
                        placeholder={t('admin.mail_templates.search_placeholder')}
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                    />
                </div>
            </div>

            <WidgetRenderer widgets={getWidgets('admin-mail-templates', 'before-list')} />

            {loading ? (
                <TableSkeleton count={5} />
            ) : templates.length > 0 ? (
                <>
                    <div className='grid grid-cols-1 gap-4'>
                        {templates.map((template) => (
                            <ResourceCard
                                key={template.id}
                                title={template.name}
                                subtitle={
                                    <div className='flex items-center gap-2 text-xs'>
                                        <Calendar className='h-3 w-3' />
                                        {new Date(template.updated_at).toLocaleDateString()}
                                    </div>
                                }
                                icon={Mail}
                                badges={[
                                    {
                                        label: template.subject,
                                        className: 'bg-primary/10 text-primary border-primary/20',
                                    },
                                ]}
                                actions={
                                    <div className='flex items-center gap-2'>
                                        <Button
                                            variant='ghost'
                                            size='sm'
                                            title='Preview'
                                            onClick={() => openPreview(template)}
                                        >
                                            <Eye className='h-4 w-4' />
                                        </Button>
                                        <Button
                                            variant='ghost'
                                            size='sm'
                                            title='Edit'
                                            onClick={() => openEdit(template)}
                                        >
                                            <Pencil className='h-4 w-4' />
                                        </Button>
                                        <Button
                                            variant='ghost'
                                            size='sm'
                                            title='Delete'
                                            className='text-destructive hover:text-destructive hover:bg-destructive/10'
                                            onClick={() => handleDelete(template.id)}
                                        >
                                            <Trash2 className='h-4 w-4' />
                                        </Button>
                                    </div>
                                }
                                description={
                                    <div className='flex flex-col gap-1 mt-2 text-sm text-muted-foreground'>
                                        <div className='flex items-center gap-2 truncate'>
                                            <FileText className='h-3 w-3 shrink-0 opacity-50' />
                                            <span className='truncate opacity-70 italic'>
                                                {template.body.replace(/<[^>]*>?/gm, '').substring(0, 100)}...
                                            </span>
                                        </div>
                                    </div>
                                }
                            />
                        ))}
                    </div>

                    {pagination.total > pagination.pageSize && (
                        <div className='flex items-center justify-center gap-2 mt-8'>
                            <Button
                                variant='outline'
                                size='icon'
                                disabled={!pagination.hasPrev}
                                onClick={() => setPagination((p) => ({ ...p, page: p.page - 1 }))}
                            >
                                <ChevronLeft className='h-4 w-4' />
                            </Button>
                            <span className='text-sm font-medium'>
                                {pagination.page} / {Math.ceil(pagination.total / pagination.pageSize)}
                            </span>
                            <Button
                                variant='outline'
                                size='icon'
                                disabled={!pagination.hasNext}
                                onClick={() => setPagination((p) => ({ ...p, page: p.page + 1 }))}
                            >
                                <ChevronRight className='h-4 w-4' />
                            </Button>
                        </div>
                    )}
                </>
            ) : (
                <EmptyState
                    title={t('admin.mail_templates.no_results')}
                    description={t('admin.mail_templates.subtitle')}
                    icon={Mail}
                    action={
                        <Button onClick={openCreate}>
                            <Plus className='w-4 h-4 mr-2' />
                            {t('admin.mail_templates.create')}
                        </Button>
                    }
                />
            )}

            <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 pt-6 border-t border-border/50'>
                <PageCard title={t('admin.mail_templates.help.what_is.title')} icon={FileText}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.mail_templates.help.what_is.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.mail_templates.help.mass_email.title')} icon={Send}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.mail_templates.help.mass_email.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.mail_templates.help.legal.title')} icon={Scale}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.mail_templates.help.legal.description')}
                    </p>
                </PageCard>
            </div>

            <Sheet open={createOpen} onOpenChange={setCreateOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>{t('admin.mail_templates.form.create_title')}</SheetTitle>
                        <SheetDescription>{t('admin.mail_templates.form.create_description')}</SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleCreate} className='space-y-4 pt-6'>
                        <div className='space-y-2'>
                            <Label htmlFor='create-name'>{t('admin.mail_templates.form.name')}</Label>
                            <Input
                                id='create-name'
                                value={formData.name}
                                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='create-subject'>{t('admin.mail_templates.form.subject')}</Label>
                            <Input
                                id='create-subject'
                                value={formData.subject}
                                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='create-body'>{t('admin.mail_templates.form.body')}</Label>
                            <Textarea
                                id='create-body'
                                className='min-h-[400px] font-mono text-xs'
                                value={formData.body}
                                onChange={(e) => setFormData({ ...formData, body: e.target.value })}
                                required
                            />
                            <p className='text-xs text-muted-foreground'>{t('admin.mail_templates.form.html_help')}</p>
                        </div>
                        <SheetFooter>
                            <Button type='submit' loading={processing}>
                                {t('admin.mail_templates.form.submit_create')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            <Sheet open={editOpen} onOpenChange={setEditOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>
                            {String(t('admin.mail_templates.form.edit_title', { name: selectedTemplate?.name || '' }))}
                        </SheetTitle>
                        <SheetDescription>
                            {String(
                                t('admin.mail_templates.form.edit_description', { name: selectedTemplate?.name || '' }),
                            )}
                        </SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleUpdate} className='space-y-4 pt-6'>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-name'>{t('admin.mail_templates.form.name')}</Label>
                            <Input
                                id='edit-name'
                                value={formData.name}
                                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-subject'>{t('admin.mail_templates.form.subject')}</Label>
                            <Input
                                id='edit-subject'
                                value={formData.subject}
                                onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label htmlFor='edit-body'>{t('admin.mail_templates.form.body')}</Label>
                            <Textarea
                                id='edit-body'
                                className='min-h-[400px] font-mono text-xs'
                                value={formData.body}
                                onChange={(e) => setFormData({ ...formData, body: e.target.value })}
                                required
                            />
                            <p className='text-xs text-muted-foreground'>{t('admin.mail_templates.form.html_help')}</p>
                        </div>
                        <SheetFooter>
                            <Button type='submit' loading={processing}>
                                {t('admin.mail_templates.form.submit_update')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            <Sheet open={previewOpen} onOpenChange={setPreviewOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>
                            {String(
                                t('admin.mail_templates.form.preview_title', { name: selectedTemplate?.name || '' }),
                            )}
                        </SheetTitle>
                        <SheetDescription>
                            {String(
                                t('admin.mail_templates.form.preview_description', {
                                    name: selectedTemplate?.name || '',
                                }),
                            )}
                        </SheetDescription>
                    </SheetHeader>
                    <div className='space-y-6 pt-6'>
                        <div className='space-y-4'>
                            <div className='space-y-1'>
                                <Label className='text-muted-foreground text-xs uppercase tracking-wider font-bold'>
                                    {t('admin.mail_templates.form.subject')}
                                </Label>
                                <p className='text-base font-semibold'>{selectedTemplate?.subject}</p>
                            </div>
                            <div className='space-y-1'>
                                <Label className='text-muted-foreground text-xs uppercase tracking-wider font-bold'>
                                    {t('admin.mail_templates.form.body')}
                                </Label>
                                <div className='rounded-xl border border-border/50 bg-white dark:bg-zinc-950 overflow-hidden min-h-[400px]'>
                                    <div
                                        className='p-6 prose prose-sm dark:prose-invert max-w-none'
                                        dangerouslySetInnerHTML={{ __html: selectedTemplate?.body || '' }}
                                    />
                                </div>
                            </div>
                        </div>
                        <SheetFooter>
                            <Button onClick={() => setPreviewOpen(false)}>Close</Button>
                        </SheetFooter>
                    </div>
                </div>
            </Sheet>

            <Sheet open={massEmailOpen} onOpenChange={setMassEmailOpen}>
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>{t('admin.mail_templates.form.mass_email_title')}</SheetTitle>
                        <SheetDescription>{t('admin.mail_templates.form.mass_email_description')}</SheetDescription>
                    </SheetHeader>
                    <form onSubmit={handleSendMassEmail} className='space-y-4 pt-6'>
                        <div className='space-y-4'>
                            <Alert variant='destructive' className='bg-destructive/5 border-destructive/20'>
                                <AlertTriangle className='h-4 w-4' />
                                <AlertTitle>{t('admin.mail_templates.messages.mass_email_warning_title')}</AlertTitle>
                                <AlertDescription>
                                    {t('admin.mail_templates.messages.mass_email_warning')}
                                </AlertDescription>
                            </Alert>
                            <div className='space-y-2'>
                                <Label htmlFor='mass-subject'>{t('admin.mail_templates.form.subject')}</Label>
                                <Input
                                    id='mass-subject'
                                    value={massEmailData.subject}
                                    onChange={(e) => setMassEmailData({ ...massEmailData, subject: e.target.value })}
                                    required
                                />
                            </div>
                            <div className='space-y-2'>
                                <Label htmlFor='mass-body'>{t('admin.mail_templates.form.body')}</Label>
                                <Textarea
                                    id='mass-body'
                                    className='min-h-[400px] font-mono text-xs'
                                    value={massEmailData.body}
                                    onChange={(e) => setMassEmailData({ ...massEmailData, body: e.target.value })}
                                    required
                                />
                                <p className='text-xs text-muted-foreground'>
                                    {t('admin.mail_templates.form.html_help')}
                                </p>
                            </div>
                        </div>
                        <SheetFooter>
                            <Button type='submit' variant='destructive' loading={processing}>
                                {t('admin.mail_templates.form.send')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>
            <WidgetRenderer widgets={getWidgets('admin-mail-templates', 'bottom-of-page')} />
        </div>
    );
}
