// featherpanel-frontendv2/src/app/admin/tickets/categories/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { useTranslation } from '@/contexts/TranslationContext';
import axios from 'axios';
import { Plus, Search, Pencil, Trash2, Ticket as TicketIcon, Tags, Info, HelpCircle } from 'lucide-react';
import Image from 'next/image';
import { PageHeader } from '@/components/featherui/PageHeader';
import { ResourceCard } from '@/components/featherui/ResourceCard';
import { TableSkeleton } from '@/components/featherui/TableSkeleton';
import { EmptyState } from '@/components/featherui/EmptyState';
import { Button } from '@/components/featherui/Button';
import { Input } from '@/components/featherui/Input';
import { Sheet, SheetDescription, SheetHeader, SheetTitle, SheetFooter } from '@/components/ui/sheet';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { PageCard } from '@/components/featherui/PageCard';
import { cn } from '@/lib/utils';

interface Category {
    id: number;
    name: string;
    icon: string | null;
    color: string;
    support_email: string;
    open_hours: string | null;
}

export default function TicketCategoriesPage() {
    const { t } = useTranslation();
    const [categories, setCategories] = useState<Category[]>([]);
    const [loading, setLoading] = useState(true);
    const [search, setSearch] = useState('');
    const [createOpen, setCreateOpen] = useState(false);
    const [editOpen, setEditOpen] = useState(false);
    const [selectedCategory, setSelectedCategory] = useState<Category | null>(null);

    const [formData, setFormData] = useState({
        name: '',
        icon: '',
        color: '#3B82F6',
        support_email: '',
        open_hours: '',
    });
    const [iconFile, setIconFile] = useState<File | null>(null);
    const [iconPreview, setIconPreview] = useState<string | null>(null);

    const fetchCategories = useCallback(async () => {
        setLoading(true);
        try {
            const response = await axios.get('/api/admin/tickets/categories');
            setCategories(response.data.data.categories || []);
        } catch (error) {
            console.error('Error fetching categories:', error);
            toast.error(t('admin.tickets.categories.fetch_error'));
        } finally {
            setLoading(false);
        }
    }, [t]);

    useEffect(() => {
        fetchCategories();
    }, [fetchCategories]);

    const handleCreate = async (e: React.FormEvent) => {
        e.preventDefault();
        try {
            let iconUrl = formData.icon;

            if (iconFile) {
                const uploadFormData = new FormData();
                uploadFormData.append('icon', iconFile);
                const uploadRes = await axios.post('/api/admin/tickets/categories/upload-icon', uploadFormData, {
                    headers: { 'Content-Type': 'multipart/form-data' },
                });
                if (uploadRes.data.success) {
                    iconUrl = uploadRes.data.data.url;
                } else {
                    toast.error(t('admin.tickets.categories.upload_error') || 'Failed to upload icon');
                    return;
                }
            }

            await axios.put('/api/admin/tickets/categories', { ...formData, icon: iconUrl });
            toast.success(t('admin.tickets.categories.create_success'));
            setCreateOpen(false);
            fetchCategories();
            resetForm();
        } catch (error) {
            console.error('Error creating category:', error);
            toast.error(t('admin.tickets.categories.create_error'));
        }
    };

    const handleUpdate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!selectedCategory) return;
        try {
            let iconUrl = formData.icon;

            if (iconFile) {
                const uploadFormData = new FormData();
                uploadFormData.append('icon', iconFile);
                const uploadRes = await axios.post('/api/admin/tickets/categories/upload-icon', uploadFormData, {
                    headers: { 'Content-Type': 'multipart/form-data' },
                });
                if (uploadRes.data.success) {
                    iconUrl = uploadRes.data.data.url;
                } else {
                    toast.error(t('admin.tickets.categories.upload_error') || 'Failed to upload icon');
                    return;
                }
            }

            await axios.patch(`/api/admin/tickets/categories/${selectedCategory.id}`, { ...formData, icon: iconUrl });
            toast.success(t('admin.tickets.categories.update_success'));
            setEditOpen(false);
            fetchCategories();
            resetForm();
        } catch (error) {
            console.error('Error updating category:', error);
            toast.error(t('admin.tickets.categories.update_error'));
        }
    };

    const handleDelete = async (id: number) => {
        if (!confirm(t('admin.tickets.categories.delete_confirm'))) return;
        try {
            await axios.delete(`/api/admin/tickets/categories/${id}`);
            toast.success(t('admin.tickets.categories.delete_success'));
            fetchCategories();
        } catch (error) {
            console.error('Error deleting category:', error);
            toast.error(t('admin.tickets.categories.delete_error'));
        }
    };

    const resetForm = () => {
        setFormData({
            name: '',
            icon: '',
            color: '#3B82F6',
            support_email: '',
            open_hours: '',
        });
        setSelectedCategory(null);
        setIconFile(null);
        setIconPreview(null);
    };

    const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file) {
            setIconFile(file);
            const reader = new FileReader();
            reader.onload = (e) => {
                setIconPreview(e.target?.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    const openEdit = (category: Category) => {
        setSelectedCategory(category);
        setFormData({
            name: category.name,
            icon: category.icon || '',
            color: category.color,
            support_email: category.support_email,
            open_hours: category.open_hours || '',
        });
        setIconPreview(category.icon);
        setEditOpen(true);
    };

    const filteredCategories = categories.filter(
        (c) =>
            c.name.toLowerCase().includes(search.toLowerCase()) ||
            c.support_email.toLowerCase().includes(search.toLowerCase()),
    );

    return (
        <div className='p-6 space-y-8 max-w-[1600px] mx-auto animate-in fade-in duration-700'>
            <PageHeader
                title={t('admin.tickets.categories.title')}
                description={t('admin.tickets.categories.description')}
                icon={Plus}
                actions={
                    <Button
                        onClick={() => {
                            resetForm();
                            setCreateOpen(true);
                        }}
                        className='rounded-2xl h-14 px-8 shadow-2xl shadow-primary/20 gap-3 text-lg font-black uppercase tracking-tighter transition-all hover:scale-[1.02] active:scale-[0.98]'
                    >
                        <Plus className='h-6 w-6' />
                        {t('admin.tickets.categories.create')}
                    </Button>
                }
            />

            <div className='flex flex-col md:flex-row gap-4 items-center justify-between bg-card/40 backdrop-blur-md p-4 rounded-4xl border border-border/5 shadow-xl shadow-primary/5'>
                <div className='relative w-full md:w-96 group'>
                    <Search className='absolute left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground group-focus-within:text-primary transition-colors' />
                    <Input
                        placeholder={t('admin.tickets.categories.search_placeholder')}
                        value={search}
                        onChange={(e) => setSearch(e.target.value)}
                        className='pl-11 h-12 bg-background/50 border-border/10 rounded-2xl focus:ring-primary/20 transition-all'
                    />
                </div>
            </div>

            {loading ? (
                <TableSkeleton count={5} />
            ) : filteredCategories.length === 0 ? (
                <EmptyState
                    title={t('admin.tickets.no_results')}
                    description={t('admin.tickets.search_placeholder')}
                    icon={Search}
                />
            ) : (
                <div className='grid grid-cols-1 gap-4'>
                    {filteredCategories.map((category) => (
                        <ResourceCard
                            key={category.id}
                            icon={({ className }: { className?: string }) => (
                                <div
                                    className={cn(
                                        'flex items-center justify-center rounded-xl bg-primary/10 overflow-hidden relative',
                                        className,
                                    )}
                                >
                                    {category.icon ? (
                                        <Image src={category.icon} alt={category.name} fill className='object-cover' />
                                    ) : (
                                        <div className='h-8 w-8 rounded-lg bg-primary/10 flex items-center justify-center text-primary'>
                                            <TicketIcon className='h-4 w-4' />
                                        </div>
                                    )}
                                </div>
                            )}
                            title={category.name}
                            subtitle={category.support_email}
                            style={{ borderLeft: `4px solid ${category.color}` }}
                            description={
                                <div className='flex items-center gap-4 text-sm text-muted-foreground'>
                                    <span>
                                        {t('admin.tickets.categories.form.open_hours')}: {category.open_hours || 'N/A'}
                                    </span>
                                </div>
                            }
                            actions={
                                <div className='flex items-center gap-2'>
                                    <Button size='sm' variant='ghost' onClick={() => openEdit(category)}>
                                        <Pencil className='h-4 w-4' />
                                    </Button>
                                    <Button
                                        size='sm'
                                        variant='ghost'
                                        className='text-destructive hover:text-destructive hover:bg-destructive/10'
                                        onClick={() => handleDelete(category.id)}
                                    >
                                        <Trash2 className='h-4 w-4' />
                                    </Button>
                                </div>
                            }
                        />
                    ))}
                </div>
            )}

            {/* Create/Edit Sheet */}
            <Sheet
                open={createOpen || editOpen}
                onOpenChange={(open) => {
                    if (!open) {
                        setCreateOpen(false);
                        setEditOpen(false);
                    }
                }}
            >
                <div className='space-y-6'>
                    <SheetHeader>
                        <SheetTitle>
                            {createOpen ? t('admin.tickets.categories.create') : t('admin.tickets.categories.edit')}
                        </SheetTitle>
                        <SheetDescription>{t('admin.tickets.categories.description')}</SheetDescription>
                    </SheetHeader>

                    <form onSubmit={createOpen ? handleCreate : handleUpdate} className='space-y-6'>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.name')}</Label>
                            <Input
                                value={formData.name}
                                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                                className='bg-background/50'
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.icon')}</Label>
                            <Input
                                type='file'
                                accept='image/*'
                                onChange={handleFileSelect}
                                className='bg-background/50 file:text-foreground'
                            />
                            {iconPreview && (
                                <div className='mt-2'>
                                    <Label className='text-xs text-muted-foreground'>{t('common.preview')}</Label>
                                    <div className='relative h-16 w-16 rounded-lg overflow-hidden border border-border/10'>
                                        <Image
                                            src={iconPreview}
                                            alt={t('common.preview')}
                                            fill
                                            className='object-cover'
                                        />
                                    </div>
                                </div>
                            )}
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.color')}</Label>
                            <div className='flex gap-2'>
                                <Input
                                    type='color'
                                    value={formData.color}
                                    onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                                    className='w-12 h-10 p-1 bg-background/50'
                                />
                                <Input
                                    value={formData.color}
                                    onChange={(e) => setFormData({ ...formData, color: e.target.value })}
                                    className='bg-background/50'
                                />
                            </div>
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.support_email')}</Label>
                            <Input
                                type='email'
                                value={formData.support_email}
                                onChange={(e) => setFormData({ ...formData, support_email: e.target.value })}
                                className='bg-background/50'
                                required
                            />
                        </div>
                        <div className='space-y-2'>
                            <Label>{t('admin.tickets.categories.form.open_hours')}</Label>
                            <Input
                                value={formData.open_hours}
                                onChange={(e) => setFormData({ ...formData, open_hours: e.target.value })}
                                className='bg-background/50'
                                placeholder='Mon-Fri 9AM-5PM'
                            />
                        </div>

                        <SheetFooter className='gap-2 sm:gap-0'>
                            <Button
                                type='button'
                                variant='outline'
                                onClick={() => {
                                    setCreateOpen(false);
                                    setEditOpen(false);
                                }}
                                className='flex-1 rounded-xl h-12'
                            >
                                {t('common.cancel')}
                            </Button>
                            <Button type='submit' className='flex-1 rounded-xl h-12 shadow-xl shadow-primary/20'>
                                {createOpen ? t('common.create') : t('common.save')}
                            </Button>
                        </SheetFooter>
                    </form>
                </div>
            </Sheet>

            {/* Help Cards */}
            <div className='grid grid-cols-1 md:grid-cols-3 gap-6 pt-8'>
                <PageCard title={t('admin.tickets.categories.help.managing.title')} icon={Tags}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.managing.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.tickets.categories.help.emails.title')} icon={Info}>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.emails.description')}
                    </p>
                </PageCard>
                <PageCard title={t('admin.tickets.categories.help.icons.title')} icon={HelpCircle} variant='warning'>
                    <p className='text-sm text-muted-foreground leading-relaxed'>
                        {t('admin.tickets.categories.help.icons.description')}
                    </p>
                </PageCard>
            </div>
        </div>
    );
}

// frontend/src/pages/admin/knowledgebase/Categories.vue
<template>
    <DashboardLayout
        :breadcrumbs="[{ text: 'Knowledgebase Categories', isCurrent: true, href: '/admin/knowledgebase/categories' }]"
    >
        <div class="min-h-screen bg-background">
            <!-- Plugin Widgets: Top of Page -->
            <WidgetRenderer v-if="widgetsTopOfPage.length > 0" :widgets="widgetsTopOfPage" />

            <!-- Loading State -->
            <div v-if="loading" class="flex items-center justify-center py-12">
                <div class="flex items-center gap-3">
                    <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                    <span class="text-muted-foreground">Loading categories...</span>
                </div>
            </div>

            <!-- Categories Table -->
            <div v-else class="p-6">
                <!-- Plugin Widgets: Before Table -->
                <WidgetRenderer v-if="widgetsBeforeTable.length > 0" :widgets="widgetsBeforeTable" />

                <TableComponent
                    title="Knowledgebase Categories"
                    description="Manage all knowledgebase categories in your system."
                    :columns="tableColumns"
                    :data="categories"
                    :search-placeholder="'Search by name...'"
                    :server-side-pagination="true"
                    :total-records="pagination.total"
                    :total-pages="Math.ceil(pagination.total / pagination.pageSize)"
                    :current-page="pagination.page"
                    :has-next="pagination.hasNext"
                    :has-prev="pagination.hasPrev"
                    :from="pagination.from"
                    :to="pagination.to"
                    local-storage-key="featherpanel-knowledgebase-categories-table-columns"
                    @search="handleSearch"
                    @page-change="changePage"
                >
                    <template #header-actions>
                        <Button
                            variant="outline"
                            size="sm"
                            data-umami-event="Create knowledgebase category"
                            @click="openCreateDrawer"
                        >
                            <Plus class="h-4 w-4 mr-2" />
                            Create Category
                        </Button>
                    </template>

                    <!-- Custom cell templates -->
                    <template #cell-icon="{ item }">
                        <div v-if="(item as Category).icon" class="flex items-center">
                            <img
                                :src="(item as Category).icon"
                                :alt="(item as Category).name"
                                class="h-8 w-8 rounded object-cover"
                                @error="handleImageError"
                            />
                        </div>
                        <span v-else class="text-muted-foreground text-sm">—</span>
                    </template>
                    <template #cell-description="{ item }">
                        <div
                            v-if="(item as Category).description"
                            class="max-w-md truncate"
                            :title="(item as Category).description"
                        >
                            {{ (item as Category).description }}
                        </div>
                        <span v-else class="text-muted-foreground text-sm">—</span>
                    </template>
                    <template #cell-actions="{ item }">
                        <div class="flex gap-2">
                            <Button
                                size="sm"
                                variant="outline"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="View category details"
                                data-umami-event="View knowledgebase category"
                                :data-umami-event-category="(item as Category).name"
                                @click="onView(item as Category)"
                            >
                                <Eye :size="16" />
                            </Button>
                            <Button
                                size="sm"
                                variant="secondary"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="Edit category"
                                data-umami-event="Edit knowledgebase category"
                                :data-umami-event-category="(item as Category).name"
                                @click="onEdit(item as Category)"
                            >
                                <Pencil :size="16" />
                            </Button>
                            <Button
                                size="sm"
                                variant="secondary"
                                class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                title="View category articles"
                                data-umami-event="View knowledgebase category articles"
                                :data-umami-event-category="(item as Category).name"
                                @click="onViewArticles(item as Category)"
                            >
                                <FileText :size="16" />
                            </Button>
                            <template v-if="confirmDeleteRow === (item as Category).id">
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    :loading="deleting"
                                    title="Confirm deletion"
                                    data-umami-event="Confirm delete knowledgebase category"
                                    :data-umami-event-category="(item as Category).name"
                                    @click="confirmDelete(item as Category)"
                                >
                                    Confirm Delete
                                </Button>
                                <Button
                                    size="sm"
                                    variant="outline"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    :disabled="deleting"
                                    title="Cancel deletion"
                                    @click="onCancelDelete"
                                >
                                    Cancel
                                </Button>
                            </template>
                            <template v-else>
                                <Button
                                    size="sm"
                                    variant="destructive"
                                    class="hover:scale-110 hover:shadow-md transition-all duration-200"
                                    title="Delete category"
                                    data-umami-event="Delete knowledgebase category"
                                    :data-umami-event-category="(item as Category).name"
                                    @click="onDelete(item as Category)"
                                >
                                    <Trash2 :size="16" />
                                </Button>
                            </template>
                        </div>
                    </template>
                </TableComponent>

                <!-- Plugin Widgets: After Table -->
                <WidgetRenderer v-if="widgetsAfterTable.length > 0" :widgets="widgetsAfterTable" />
            </div>

            <!-- Plugin Widgets: Bottom of Page -->
            <WidgetRenderer v-if="widgetsBottomOfPage.length > 0" :widgets="widgetsBottomOfPage" />
        </div>
    </DashboardLayout>

    <!-- View Drawer -->
    <Drawer
        class="w-full"
        :open="viewing"
        @update:open="
            (val: boolean) => {
                if (!val) closeView();
            }
        "
    >
        <DrawerContent v-if="selectedCategory">
            <DrawerHeader>
                <DrawerTitle>Category Info</DrawerTitle>
                <DrawerDescription>Viewing details for category: {{ selectedCategory.name }}</DrawerDescription>
            </DrawerHeader>
            <div class="px-6 pt-6 space-y-2">
                <div v-if="selectedCategory.icon" class="flex items-center gap-2">
                    <b>Icon:</b>
                    <img
                        :src="selectedCategory.icon"
                        :alt="selectedCategory.name"
                        class="h-12 w-12 rounded object-cover"
                    />
                </div>
                <div><b>Name:</b> {{ selectedCategory.name }}</div>
                <div>
                    <b>Description:</b>
                    <p class="mt-1 text-sm text-muted-foreground whitespace-pre-wrap">
                        {{ selectedCategory.description || '-' }}
                    </p>
                </div>
                <div><b>Position:</b> {{ selectedCategory.position }}</div>
                <div><b>Created At:</b> {{ selectedCategory.created_at }}</div>
                <div><b>Updated At:</b> {{ selectedCategory.updated_at }}</div>
            </div>
            <div class="p-4 flex justify-end">
                <DrawerClose as-child>
                    <Button variant="outline" @click="closeView">Close</Button>
                </DrawerClose>
            </div>
        </DrawerContent>
    </Drawer>

    <!-- Edit Drawer -->
    <Drawer
        :open="editDrawerOpen"
        @update:open="
            (val: boolean) => {
                if (!val) closeEditDrawer();
            }
        "
    >
        <DrawerContent v-if="editingCategory">
            <DrawerHeader>
                <DrawerTitle>Edit Category</DrawerTitle>
                <DrawerDescription>Edit details for category: {{ editingCategory.name }}</DrawerDescription>
            </DrawerHeader>
            <form class="space-y-4 px-6 pb-6 pt-2" @submit.prevent="submitEdit">
                <label for="edit-name" class="block mb-1 font-medium">Name</label>
                <Input id="edit-name" v-model="editForm.name" label="Name" placeholder="Name" required />
                <label for="edit-icon" class="block mb-1 font-medium">Icon (Required)</label>
                <div class="flex gap-2">
                    <Input
                        ref="editIconFileInput"
                        type="file"
                        accept="image/jpeg,image/png,image/gif,image/webp"
                        @change="handleCreateIconFileSelect"
                    />
                </div>
                <div v-if="editIconPreview" class="flex items-center gap-2 mt-2">
                    <img :src="editIconPreview" alt="Preview" class="h-12 w-12 rounded object-cover" />
                    <span class="text-sm text-muted-foreground">Preview</span>
                </div>
                <div v-else-if="editingCategory?.icon" class="flex items-center gap-2 mt-2">
                    <img :src="editingCategory.icon" alt="Current icon" class="h-12 w-12 rounded object-cover" />
                    <span class="text-sm text-muted-foreground">Current icon</span>
                </div>
                <label for="edit-description" class="block mb-1 font-medium">Description</label>
                <Input
                    id="edit-description"
                    v-model="editForm.description"
                    label="Description"
                    placeholder="Description"
                />
                <label for="edit-position" class="block mb-1 font-medium">Position</label>
                <Input
                    id="edit-position"
                    v-model.number="editForm.position"
                    type="number"
                    label="Position"
                    placeholder="0"
                />
                <div class="flex justify-end gap-2 mt-4">
                    <Button type="button" variant="outline" @click="closeEditDrawer">Cancel</Button>
                    <Button type="submit" variant="default">Save</Button>
                </div>
            </form>
        </DrawerContent>
    </Drawer>

    <!-- Create Drawer -->
    <Drawer
        :open="createDrawerOpen"
        @update:open="
            (val) => {
                if (!val) closeCreateDrawer();
            }
        "
    >
        <DrawerContent>
            <DrawerHeader>
                <DrawerTitle>Create Category</DrawerTitle>
                <DrawerDescription>Fill in the details to create a new knowledgebase category.</DrawerDescription>
            </DrawerHeader>
            <form class="space-y-4 px-6 pb-6 pt-2" @submit.prevent="submitCreate">
                <label for="create-name" class="block mb-1 font-medium">Name</label>
                <Input id="create-name" v-model="createForm.name" label="Name" placeholder="Name" required />
                <label for="create-icon" class="block mb-1 font-medium">Icon (Required)</label>
                <div class="flex gap-2">
                    <Input
                        ref="createIconFileInput"
                        type="file"
                        accept="image/jpeg,image/png,image/gif,image/webp"
                        required
                        @change="handleCreateIconFileSelect"
                    />
                </div>
                <div v-if="createIconPreview" class="flex items-center gap-2 mt-2">
                    <img :src="createIconPreview" alt="Preview" class="h-12 w-12 rounded object-cover" />
                    <span class="text-sm text-muted-foreground">Preview</span>
                </div>
                <label for="create-description" class="block mb-1 font-medium">Description</label>
                <Input
                    id="create-description"
                    v-model="createForm.description"
                    label="Description"
                    placeholder="Description"
                />
                <label for="create-position" class="block mb-1 font-medium">Position</label>
                <Input
                    id="create-position"
                    v-model.number="createForm.position"
                    type="number"
                    label="Position"
                    placeholder="0"
                />
                <div class="flex justify-end gap-2 mt-4">
                    <Button type="button" variant="outline" :disabled="uploadingCreateIcon" @click="closeCreateDrawer">
                        Cancel
                    </Button>
                    <Button type="submit" variant="default" :loading="uploadingCreateIcon">Create</Button>
                </div>
            </form>
        </DrawerContent>
    </Drawer>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { computed, ref, onMounted, watch } from 'vue';
import DashboardLayout from '@/layouts/DashboardLayout.vue';
import WidgetRenderer from '@/components/plugins/WidgetRenderer.vue';
import { usePluginWidgets, getWidgets } from '@/composables/usePluginWidgets';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Eye, Pencil, Trash2, Plus, FileText } from 'lucide-vue-next';
import { useRouter } from 'vue-router';
import axios from 'axios';
import {
    Drawer,
    DrawerContent,
    DrawerHeader,
    DrawerTitle,
    DrawerDescription,
    DrawerClose,
} from '@/components/ui/drawer';
import TableComponent from '@/components/ui/feather-table/TableComponent.vue';
import type { TableColumn } from '@/components/ui/feather-table/types';
import { useToast } from 'vue-toastification';

type Category = {
    id: number;
    name: string;
    slug: string;
    icon: string;
    description?: string;
    position: number;
    created_at: string;
    updated_at: string;
};

const toast = useToast();
const router = useRouter();

// Plugin widgets
const { fetchWidgets: fetchPluginWidgets } = usePluginWidgets('admin-knowledgebase-categories');
const widgetsTopOfPage = computed(() => getWidgets('admin-knowledgebase-categories', 'top-of-page'));
const widgetsBeforeTable = computed(() => getWidgets('admin-knowledgebase-categories', 'before-table'));
const widgetsAfterTable = computed(() => getWidgets('admin-knowledgebase-categories', 'after-table'));
const widgetsBottomOfPage = computed(() => getWidgets('admin-knowledgebase-categories', 'bottom-of-page'));

const categories = ref<Category[]>([]);
const searchQuery = ref('');
const pagination = ref({
    page: 1,
    pageSize: 10,
    total: 0,
    hasNext: false,
    hasPrev: false,
    from: 0,
    to: 0,
});
const loading = ref(true);
const deleting = ref(false);
const confirmDeleteRow = ref<number | null>(null);
const selectedCategory = ref<Category | null>(null);
const viewing = ref(false);
const editingCategory = ref<Category | null>(null);
const editDrawerOpen = ref(false);
const editForm = ref({
    name: '',
    description: '',
    position: 0,
});
const createDrawerOpen = ref(false);
const createForm = ref({
    name: '',
    description: '',
    position: 0,
});

// Icon upload
const createIconFileInput = ref<HTMLInputElement | null>(null);
const createIconPreview = ref<string | null>(null);
const createIconFile = ref<File | null>(null);
const uploadingCreateIcon = ref(false);

const editIconFileInput = ref<HTMLInputElement | null>(null);
const editIconPreview = ref<string | null>(null);
const editIconFile = ref<File | null>(null);
const uploadingEditIcon = ref(false);

const tableColumns: TableColumn[] = [
    { key: 'icon', label: 'Icon', searchable: false },
    { key: 'name', label: 'Name', searchable: true },
    { key: 'description', label: 'Description', searchable: true },
    { key: 'position', label: 'Position' },
    { key: 'created_at', label: 'Created' },
    { key: 'actions', label: 'Actions', headerClass: 'w-[160px] font-semibold' },
];

async function fetchCategories() {
    loading.value = true;
    try {
        const { data } = await axios.get('/api/admin/knowledgebase/categories', {
            params: {
                page: pagination.value.page,
                limit: pagination.value.pageSize,
                search: searchQuery.value || undefined,
            },
        });
        categories.value = data.data.categories || [];

        const apiPagination = data.data.pagination;
        pagination.value = {
            page: apiPagination.current_page,
            pageSize: apiPagination.per_page,
            total: apiPagination.total_records,
            hasNext: apiPagination.has_next,
            hasPrev: apiPagination.has_prev,
            from: apiPagination.from,
            to: apiPagination.to,
        };
    } finally {
        loading.value = false;
    }
}

onMounted(async () => {
    await fetchPluginWidgets();
    await fetchCategories();
});
watch([() => pagination.value.page, () => pagination.value.pageSize, searchQuery], fetchCategories);

function handleSearch(query: string) {
    searchQuery.value = query;
    pagination.value.page = 1;
    fetchCategories();
}

function changePage(page: number) {
    pagination.value.page = page;
    fetchCategories();
}

async function onView(category: Category) {
    viewing.value = true;
    try {
        const { data } = await axios.get(`/api/admin/knowledgebase/categories/${category.id}`);
        selectedCategory.value = data.data.category;
    } catch {
        selectedCategory.value = null;
        toast.error('Failed to fetch category details');
    }
}

function onEdit(category: Category) {
    openEditDrawer(category);
}

async function confirmDelete(category: Category) {
    deleting.value = true;
    let success = false;
    try {
        const response = await axios.delete(`/api/admin/knowledgebase/categories/${category.id}`);
        if (response.data && response.data.success) {
            toast.success('Category deleted successfully');
            await fetchCategories();
            success = true;
        } else {
            toast.error(response.data?.message || 'Failed to delete category');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to delete category';
        toast.error(errorMessage);
    } finally {
        deleting.value = false;
        if (success) confirmDeleteRow.value = null;
    }
}

function onDelete(category: Category) {
    confirmDeleteRow.value = category.id;
}

function onCancelDelete() {
    confirmDeleteRow.value = null;
}

function closeView() {
    viewing.value = false;
    selectedCategory.value = null;
}

async function openEditDrawer(category: Category) {
    try {
        const { data } = await axios.get(`/api/admin/knowledgebase/categories/${category.id}`);
        const c: Category = data.data.category;
        editingCategory.value = c;
        editForm.value = {
            name: c.name || '',
            description: c.description || '',
            position: c.position || 0,
        };
        editIconPreview.value = null;
        editIconFile.value = null;
        if (editIconFileInput.value) {
            editIconFileInput.value.value = '';
        }
        editDrawerOpen.value = true;
    } catch {
        toast.error('Failed to fetch category details for editing');
    }
}

function closeEditDrawer() {
    editDrawerOpen.value = false;
    editingCategory.value = null;
}

async function submitEdit() {
    if (!editingCategory.value) return;

    // If no new icon file selected, use existing icon
    let iconUrl = editingCategory.value.icon;

    // Upload new icon if one was selected
    if (editIconFile.value) {
        uploadingEditIcon.value = true;
        try {
            const formData = new FormData();
            formData.append('icon', editIconFile.value);

            const { data } = await axios.post('/api/admin/knowledgebase/upload-icon', formData, {
                headers: {
                    'Content-Type': 'multipart/form-data',
                },
            });

            if (data && data.success) {
                iconUrl = data.data.url;
            } else {
                toast.error(data?.message || 'Failed to upload icon');
                uploadingEditIcon.value = false;
                return;
            }
        } catch (e: unknown) {
            const errorMessage =
                (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
                'Failed to upload icon';
            toast.error(errorMessage);
            uploadingEditIcon.value = false;
            return;
        } finally {
            uploadingEditIcon.value = false;
        }
    }

    try {
        const patchData: {
            name: string;
            icon: string;
            description?: string;
            position?: number;
        } = {
            name: editForm.value.name,
            icon: iconUrl,
        };
        if (editForm.value.description !== undefined) {
            patchData.description = editForm.value.description || undefined;
        }
        if (editForm.value.position !== undefined) {
            patchData.position = editForm.value.position;
        }
        const { data } = await axios.patch(
            `/api/admin/knowledgebase/categories/${editingCategory.value.id}`,
            patchData,
        );
        if (data && data.success) {
            toast.success('Category updated successfully');
            await fetchCategories();
            closeEditDrawer();
        } else {
            toast.error(data?.message || 'Failed to update category');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to update category';
        toast.error(errorMessage);
    }
}

function openCreateDrawer() {
    createDrawerOpen.value = true;
    createForm.value = { name: '', description: '', position: 0 };
    createIconPreview.value = null;
    createIconFile.value = null;
    if (createIconFileInput.value) {
        createIconFileInput.value.value = '';
    }
}

function closeCreateDrawer() {
    createDrawerOpen.value = false;
    createIconPreview.value = null;
    createIconFile.value = null;
}

function handleCreateIconFileSelect(event: Event) {
    const target = event.target as HTMLInputElement;
    const file = target.files?.[0];
    if (file) {
        createIconFile.value = file;
        const reader = new FileReader();
        reader.onload = (e) => {
            createIconPreview.value = e.target?.result as string;
        };
        reader.readAsDataURL(file);
    } else {
        createIconFile.value = null;
        createIconPreview.value = null;
    }
}

async function submitCreate() {
    if (!createIconFile.value) {
        toast.error('Please select an icon file');
        return;
    }

    uploadingCreateIcon.value = true;
    let iconUrl = '';

    try {
        // Upload icon first
        const formData = new FormData();
        formData.append('icon', createIconFile.value);

        const uploadResponse = await axios.post('/api/admin/knowledgebase/upload-icon', formData, {
            headers: {
                'Content-Type': 'multipart/form-data',
            },
        });

        if (uploadResponse.data && uploadResponse.data.success) {
            iconUrl = uploadResponse.data.data.url;
        } else {
            toast.error(uploadResponse.data?.message || 'Failed to upload icon');
            uploadingCreateIcon.value = false;
            return;
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message || 'Failed to upload icon';
        toast.error(errorMessage);
        uploadingCreateIcon.value = false;
        return;
    } finally {
        uploadingCreateIcon.value = false;
    }

    try {
        const createData: {
            name: string;
            slug: string;
            icon: string;
            description?: string;
            position?: number;
        } = {
            name: createForm.value.name,
            slug: createForm.value.name
                .toLowerCase()
                .replace(/[^a-z0-9]+/g, '-')
                .replace(/^-|-$/g, ''),
            icon: iconUrl,
        };
        if (createForm.value.description) {
            createData.description = createForm.value.description;
        }
        if (createForm.value.position !== undefined) {
            createData.position = createForm.value.position;
        }
        const { data } = await axios.put('/api/admin/knowledgebase/categories', createData);
        if (data && data.success) {
            toast.success('Category created successfully');
            await fetchCategories();
            closeCreateDrawer();
        } else {
            toast.error(data?.message || 'Failed to create category');
        }
    } catch (e: unknown) {
        const errorMessage =
            (e as { response?: { data?: { message?: string } } })?.response?.data?.message ||
            'Failed to create category';
        toast.error(errorMessage);
    }
}

function handleImageError(event: Event) {
    const img = event.target as HTMLImageElement;
    img.style.display = 'none';
}

function onViewArticles(category: Category) {
    router.push(`/admin/knowledgebase/categories/${category.id}/articles`);
}
</script>
