// frontend/src/components/account/Activity.vue
<template>
    <div class="space-y-6">
        <div>
            <h3 class="text-lg font-medium">{{ $t('account.activity.title') }}</h3>
            <p class="text-sm text-muted-foreground">{{ $t('account.activity.description') }}</p>
        </div>

        <!-- Loading State -->
        <div v-if="loading" class="flex items-center justify-center py-12">
            <div class="flex items-center gap-3">
                <div class="animate-spin rounded-full h-6 w-6 border-2 border-primary border-t-transparent"></div>
                <span class="text-muted-foreground">{{ $t('account.activity.loading') }}</span>
            </div>
        </div>

        <!-- Error State -->
        <div v-else-if="message?.type === 'error'" class="flex flex-col items-center justify-center py-12 text-center">
            <div class="text-red-500 mb-4">
                <svg class="h-12 w-12 mx-auto" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.964-.833-2.732 0L3.732 16.5c-.77.833.192 2.5 1.732 2.5z"
                    />
                </svg>
            </div>
            <h3 class="text-lg font-medium text-muted-foreground mb-2">{{ $t('account.activity.loadError') }}</h3>
            <p class="text-sm text-muted-foreground max-w-sm">
                {{ message.text }}
            </p>
            <Button class="mt-4" @click="fetchActivity">{{ $t('account.activity.tryAgain') }}</Button>
        </div>

        <!-- Activity Timeline -->
        <div v-else class="space-y-4">
            <!-- Search Bar -->
            <div class="relative">
                <Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                    v-model="searchQuery"
                    :placeholder="$t('account.activity.searchPlaceholder')"
                    class="pl-10"
                    @input="handleSearch"
                />
            </div>

            <!-- Activity Count -->
            <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                <p class="text-sm text-muted-foreground text-center sm:text-left">
                    {{ $t('account.activity.totalActivities', { count: totalActivities }) }}
                </p>
                <Button variant="outline" size="sm" class="w-full sm:w-auto" @click="fetchActivity">
                    <RefreshCw class="h-4 w-4 mr-2" />
                    {{ $t('account.activity.refresh') }}
                </Button>
            </div>

            <!-- Timeline -->
            <div v-if="filteredActivities.length > 0" class="relative">
                <!-- Timeline line -->
                <div class="absolute left-6 top-0 bottom-0 w-0.5 bg-border"></div>

                <div class="space-y-4">
                    <div v-for="activity in filteredActivities" :key="activity.id" class="relative flex gap-4">
                        <!-- Timeline dot -->
                        <div
                            class="relative z-10 flex h-12 w-12 items-center justify-center rounded-full bg-primary/10 border-2 border-primary/20"
                        >
                            <div class="h-3 w-3 rounded-full bg-primary"></div>
                        </div>

                        <!-- Activity content -->
                        <div class="flex-1 space-y-2 pb-4">
                            <div class="space-y-2">
                                <div class="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2">
                                    <div class="space-y-1 flex-1">
                                        <h4 class="text-sm font-medium leading-none">
                                            {{ activity.name }}
                                        </h4>
                                        <p v-if="activity.context" class="text-sm text-muted-foreground">
                                            {{ activity.context }}
                                        </p>
                                    </div>
                                    <div class="flex items-center gap-2 text-xs text-muted-foreground flex-shrink-0">
                                        <Clock class="h-3 w-3" />
                                        {{ formatDate(activity.created_at) }}
                                    </div>
                                </div>
                            </div>

                            <!-- Activity metadata -->
                            <div class="flex items-center gap-4 text-xs text-muted-foreground">
                                <div v-if="activity.ip_address" class="flex items-center gap-1">
                                    <Globe class="h-3 w-3" />
                                    <span class="font-mono">{{ activity.ip_address }}</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Empty State -->
            <div v-else class="text-center py-12">
                <div class="mx-auto h-12 w-12 text-muted-foreground mb-4">
                    <Activity class="h-12 w-12" />
                </div>
                <h3 class="text-sm font-medium text-muted-foreground mb-2">
                    {{ searchQuery ? $t('account.activity.noSearchResults') : $t('account.activity.noActivities') }}
                </h3>
                <p class="text-xs text-muted-foreground">
                    {{
                        searchQuery
                            ? $t('account.activity.tryDifferentSearch')
                            : $t('account.activity.noActivitiesDescription')
                    }}
                </p>
            </div>
        </div>
    </div>
</template>

<script setup lang="ts">
// MIT License
//
// Copyright (c) 2025 MythicalSystems
// Copyright (c) 2025 Cassian Gherman (NaysKutzu)
// Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import { ref, onMounted, computed } from 'vue';
import { useI18n } from 'vue-i18n';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useSessionStore } from '@/stores/session';
import { Search, RefreshCw, Clock, Globe, Activity } from 'lucide-vue-next';
import axios from 'axios';

const { t } = useI18n();
const sessionStore = useSessionStore();

type Activity = {
    id: number;
    user_uuid: string;
    name: string;
    context?: string;
    ip_address?: string;
    created_at: string;
    updated_at: string;
};

const activities = ref<Activity[]>([]);
const loading = ref(false);
const message = ref<{ type: 'success' | 'error'; text: string } | null>(null);
const searchQuery = ref('');

const totalActivities = computed(() => activities.value.length);

const filteredActivities = computed(() => {
    if (!searchQuery.value) return activities.value;

    const query = searchQuery.value.toLowerCase();
    return activities.value.filter(
        (activity) =>
            activity.name.toLowerCase().includes(query) ||
            (activity.context && activity.context.toLowerCase().includes(query)) ||
            (activity.ip_address && activity.ip_address.toLowerCase().includes(query)),
    );
});

async function fetchActivity() {
    loading.value = true;
    message.value = null;

    try {
        // First ensure we have a valid session
        await sessionStore.checkSessionOrRedirect();

        const { data } = await axios.get('/api/user/session');
        if (data && data.success && data.data && data.data.activity) {
            activities.value = data.data.activity.data || [];
        } else {
            activities.value = [];
        }
    } catch (error) {
        console.error('Error fetching activity:', error);
        message.value = {
            type: 'error',
            text: t('account.activity.fetchError'),
        };
        activities.value = [];
    } finally {
        loading.value = false;
    }
}

function handleSearch() {
    // Search is handled by the computed filteredActivities
}

function formatDate(dateString: string): string {
    if (!dateString) return '-';

    try {
        const date = new Date(dateString);
        const now = new Date();
        const diffInHours = Math.abs(now.getTime() - date.getTime()) / (1000 * 60 * 60);

        if (diffInHours < 1) {
            return t('account.activity.justNow');
        } else if (diffInHours < 24) {
            const hours = Math.floor(diffInHours);
            return t('account.activity.hoursAgo', { hours });
        } else if (diffInHours < 48) {
            return t('account.activity.yesterday');
        } else {
            return (
                date.toLocaleDateString() +
                ' ' +
                date.toLocaleTimeString([], {
                    hour: '2-digit',
                    minute: '2-digit',
                })
            );
        }
    } catch {
        return dateString;
    }
}

onMounted(fetchActivity);
</script>

// featherpanel-frontendv2/src/app/admin/analytics/activity/page.tsx
/*
MIT License

Copyright (c) 2024-2026 MythicalSystems and Contributors
Copyright (c) 2024-2026 Cassian Gherman (NaysKutzu)
Copyright (c) 2018 - 2021 Dane Everitt <dane@daneeveritt.com> and Contributors

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

'use client'

import React, { useEffect, useState } from 'react'
import { useTranslation } from '@/contexts/TranslationContext'
import api from '@/lib/api'
import { ActivityTrendChart, ActivityBreakdownChart } from '@/components/admin/analytics/ActivityCharts'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Activity, Clock, Calendar } from 'lucide-react'

interface ActivityStats {
  total: number
  today: number
  this_week: number
  this_month: number
  active_users_today: number
  peak_hour: number
}

interface ActivityTrend {
  date: string
  count: number
}

interface ActivityBreakdown {
  activity_type: string
  count: number
}

export default function ActivityAnalyticsPage() {
  const { t } = useTranslation()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const [stats, setStats] = useState<ActivityStats | null>(null)
  const [trend, setTrend] = useState<ActivityTrend[]>([])
  const [breakdown, setBreakdown] = useState<ActivityBreakdown[]>([])

  const fetchData = React.useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const [statsRes, trendRes, breakdownRes] = await Promise.all([
        api.get('/admin/analytics/activity/stats'),
        api.get('/admin/analytics/activity/trend'),
        api.get('/admin/analytics/activity/breakdown'),
      ])

      setStats(statsRes.data.data)
      setTrend(trendRes.data.data.data || [])
      // Map API 'name' to 'activity_type' for the chart
      setBreakdown((breakdownRes.data.data.activities || []).map((a: { name: string; count: number }) => ({
        activity_type: a.name,
        count: a.count
      })))
    } catch (err) {
      console.error('Failed to fetch activity analytics:', err)
      setError(t('admin.analytics.activity.error'))
    } finally {
      setLoading(false)
    }
  }, [t])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[400px] text-center">
        <p className="text-red-500 mb-4">{error}</p>
        <button
          onClick={fetchData}
          className="px-4 py-2 bg-primary text-primary-foreground rounded-md hover:opacity-90 transition-opacity"
        >
          {t('admin.analytics.activity.retry')}
        </button>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold tracking-tight">{t('admin.analytics.activity.title')}</h1>
        <p className="text-muted-foreground">{t('admin.analytics.activity.subtitle')}</p>
      </div>

      {/* Overview Stats */}
      {stats && (
        <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card className="border-border/50 shadow-sm bg-card/50 backdrop-blur-sm">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {t('admin.analytics.activity.today')}
              </CardTitle>
              <Activity className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats.today}</div>
              <p className="text-xs text-muted-foreground">
                {t('admin.analytics.activity.active_users', { count: String(stats.active_users_today) })}
              </p>
            </CardContent>
          </Card>
          <Card className="border-border/50 shadow-sm bg-card/50 backdrop-blur-sm">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {t('admin.analytics.activity.this_week')}
              </CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats.this_week}</div>
              <p className="text-xs text-muted-foreground">
                {t('admin.analytics.activity.last_7_days')}
              </p>
            </CardContent>
          </Card>
          <Card className="border-border/50 shadow-sm bg-card/50 backdrop-blur-sm">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {t('admin.analytics.activity.this_month')}
              </CardTitle>
              <Calendar className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats.this_month}</div>
              <p className="text-xs text-muted-foreground">
                {t('admin.analytics.activity.last_30_days')}
              </p>
            </CardContent>
          </Card>
          <Card className="border-border/50 shadow-sm bg-card/50 backdrop-blur-sm">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                {t('admin.analytics.activity.peak_hour')}
              </CardTitle>
              <Clock className="h-4 w-4 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{stats.peak_hour}:00</div>
              <p className="text-xs text-muted-foreground">
                {t('admin.analytics.activity.most_active_time')}
              </p>
            </CardContent>
          </Card>
        </div>
      )}

      {/* Charts Section 1 */}
      <div className="grid gap-4 md:grid-cols-1 lg:grid-cols-3">
        <ActivityTrendChart data={trend} />
        <ActivityBreakdownChart data={breakdown} />
      </div>


    </div>
  )
}
